### ISSUE TITLE
Long Error

### ISSUE THREAD

**Issue by SwedzNet** [TheHolyWaffle/TeamSpeak-3-Java-API#103]
I put everything from the /src/ file into my project's /src/, along with putting the jar into my build path.

This is my code: http://pastebin.com/raw/M3uYbR2L
This is my error: http://pastebin.com/raw/hCP6HBXb

**Comment by Kakifrucht** [comment]
Caused by: java.net.ConnectException: Connection refused
Firewalled? Wrong port?

**Comment by SwedzNet** [comment]
I'm 99% sure it's not firewalled, because the code is being run on the same IP as I'm connected to the server right now. Port is fine, because I'm connected using that exact port and IP

**Comment by Scrumplex** [comment]
the port you have to enter has to be the server query port! defualt one it 10011

**Comment by SwedzNet** [comment]
Then what do I do for the actual TS3 server port?

**Comment by Firedroide** [comment]
TS3API#selectVirtualServerByPort

**Comment by Scrumplex** [comment]
nothing. That one isnt needed

**Comment by Firedroide** [comment]
Sure is, he's talking about the virtual server / voice port @Scrumplex :stuck_out_tongue:

**Comment by SwedzNet** [comment]
My server just crashed..

Crash log: http://pastebin.com/raw/rmwwvCxc

**Comment by Firedroide** [comment]
Wtf, is that some sort of deadlock watchdog?

We can't work around other software's weirdness. Do the startup in a separate thread if Spigot doesn't allow you to use the main thread.

**Comment by mohe2015** [comment]
Try something like:
  api.login(USERNAME, PASSWORD);
        api.selectVirtualServerById(1);
        api.setNickname("CubedBot");

instead of

    api.selectVirtualServerByPort(9316);
    api.login(USERNAME, PASSWORD);
    api.selectVirtualServerById(1);
    api.setNickname("CubedBot");

That works for me.

**Comment by Kakifrucht** [comment]
Yes, it is a watchdog.

@SwedzNet use the bukkit scheduler to dispatch a async thread.

**Comment by mohe2015** [comment]
For me it worked without a bukkit scheduler because after the initialisation everything is event based.

**Comment by Firedroide** [comment]
@mohe2015 The connect method is blocking. Spigots watchdog checks if all threads are currently blocked, waiting or timed-waiting. He can therefore not use the TS3Query#connect method in the main plugin enabling thread.

**Comment by SwedzNet** [comment]
The thing is @mohe2015, I need to have it connect to the server with the exact IP of 108.61.118.138:9316.. If it can't use the port then it can't work.

**Comment by mohe2015** [comment]
It works but the server will wait until you are connected (or crash if it takes to long).

**Comment by mohe2015** [comment]
Are you sure the host and port are correct? you can check it with something like telnet.

**Comment by Firedroide** [comment]
By the way @SwedzNet, you're currently selecting the virtual _twice_.

```
    api.selectVirtualServerByPort(9316);
    api.login(USERNAME, PASSWORD);
    api.selectVirtualServerById(1);
```

Remove the last line.

**Comment by mohe2015** [comment]
![ts](https://cloud.githubusercontent.com/assets/13287984/15865908/ded725d8-2cdc-11e6-93b9-d9b7e8ec654a.png)
I don't think so, but maybe there is a firewall.

**Comment by Firedroide** [comment]
@SwedzNet I don't assume you're hosting your TS3 server yourself.

You need to know _Server Query Port_ to connect via the server query interface. Either look that information up online or contact whoever is hosting your TS3 server.

**Comment by mohe2015** [comment]
@SwedzNet It looks like you are not using the default port. Why? It's password protected.

**Comment by SwedzNet** [comment]
Because when I bought the TS server it decided to give me a port rather than default.

**Comment by mohe2015** [comment]
And which port?

**Comment by SwedzNet** [comment]
9316 is the port

**Comment by Firedroide** [comment]
That is your __voice__ port, not the __query__ port. These two differ. Find out which __query__ port your server uses. Yes, you need to know __both__ ports.

**Comment by mohe2015** [comment]
If you can look into the log files there should be something like:
`INFO    |Query         |   |listening on 0.0.0.0:10011`

**Comment by SwedzNet** [comment]
I looked into the server log and there's nothing about that

**Comment by Firedroide** [comment]
He meant the log of your __TeamSpeak server__, not your Spigot server log.

**Comment by SwedzNet** [comment]
I'm aware, I looked there. Nothing about it.

**Comment by Scrumplex** [comment]
Then just try to use 10011 as the port and not your ts3 port.

**Comment by Firedroide** [comment]
Huh, that's weird. I don't think you can turn off the server query, so the log files should include that information :confused:

**Comment by mohe2015** [comment]
If you have linux you can scan for open ports:
nmap -p 0-65535 -v -sT <your-ip>
The you have to try all unknown ports using telnet.
The right one should print something like:
`TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.`

**Comment by SwedzNet** [comment]
The TS3 server is not hosted on my linux server.

**Comment by mohe2015** [comment]
Can you post your TeamSpeak server log please (remove private information)?

**Comment by Firedroide** [comment]
Got it, it's port `9100`. I did some IP lookups and then a search on your TS3 hoster's forums :stuck_out_tongue:

**Comment by SwedzNet** [comment]
Okay, thanks. I was just getting the log ready xD I'll try that port

**Comment by SwedzNet** [comment]
It apparently loaded without errors, how do I get it to show as a user on the server named "CubedBot"

**Comment by mohe2015** [comment]
The server query isn't a directly visible user, i think.

**Comment by Firedroide** [comment]
Well, you can't directly. A server query is not really a user.

**Comment by SwedzNet** [comment]
Am I able to do that though?

**Comment by mohe2015** [comment]
I don't think so, you can just let it send messages. Then it will appear in the messages section.

**Comment by Firedroide** [comment]
Yes, but only for yourself. You can go to the favorites menu (where you can edit the favorites), select your server and then there should be a checkbox that will make server query clients visible.

**Comment by Firedroide** [comment]
![image](https://cloud.githubusercontent.com/assets/1472572/15866989/6deb998a-2ce1-11e6-9b96-56ef53c8207d.png)

Yay for paint

**Comment by SwedzNet** [comment]
What does api.setNickname() do though?

**Comment by Firedroide** [comment]
Changes the name of your query, which will show up if you receive a message from the server query or have server queries visible.

**Comment by SwedzNet** [comment]
Ahah. I see, thanks a TON guys! :smile:

**Comment by Firedroide** [comment]
You're welcome! :smile:

By the way, we also have a [gitter channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) for this kind of support. Sends way less e-mails to all contributors :stuck_out_tongue_winking_eye:
