### ISSUE TITLE
Default Nickname Question

### ISSUE THREAD

**Issue by SwedzNet** [TheHolyWaffle/TeamSpeak-3-Java-API#105]
Is there a way to set the default nickname of your server query? Because when it boots up, and it has sent a private message to someone, it changes the name to "*my name* - *the ip its coming from*". Which I don't want. I just want it to join and already be nicknamed as "CubedBot".

**Comment by mohe2015** [comment]
api.setNickname("CubeeBot");
should work. Put it after selectVirtualServer...

**Comment by Firedroide** [comment]
Or even before `selectVirtualServer`, that way you'll already have the correct name once you become visible to other clients.

**Comment by SwedzNet** [comment]
I know, that's what I'm using for it. But it still shows the ip it's coming from for like a millisecond. And if someone has a chat open with it, the name will stay like that in their chat. So they can get the IP of the bot.

**Comment by Firedroide** [comment]
It's all about the order of your instructions. Don't join a virtual server before you've set your nickname. Don't register any event handlers before you've set your nickname. Don't send chat messages before you've set your nickname. This is not an API issue.

**Comment by SwedzNet** [comment]
If I put api.setNickname("CubedBot"); before api.selectVirtualServerByPort(9316);, it doesn't even set the nickname at all.

**Comment by Firedroide** [comment]
Just tested it, you're right. Just set the nickname immediately after selecting the virtual server then :blush:
