### ISSUE TITLE
Changing Client Description

### ISSUE THREAD

**Issue by SteuerungC** [TheHolyWaffle/TeamSpeak-3-Java-API#106]
At the moment, Im working with your API, and there are many cool features, but there is one thing missing:
I've tried to change a Clients description, but it is seemingly not possible. I started to look for an option to implement a solution on my own and Ive checked out the Query-Commands and found the "clientedit"-command (http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf#25).
Is it possible to integrate an option to change changeaple properites of a client or is there an option to change the description I have disregarded?

**Comment by Firedroide** [comment]
Using [`TS3Api#editClient`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1192-L1195) works for me. Are you sure that you have all the required permissions to edit a client's description?

**Comment by SteuerungC** [comment]
Thanks a lot! This works for me too, I have just disregarded this function.

**Comment by TheKryZan** [comment]
I'm kinda new to Programming but I have some struggle with it, maybe you can help me here

```
			public void onTextMessage(TextMessageEvent e) {
				
				Client c = Load.api.getClientInfo(e.getInvokerId());
				
				if(e.getMessage().equalsIgnoreCase("!event")) {
					if(c.isInServerGroup(19025) ) {
					    Load.api.editClient(1, Collections.singletonMap(ClientProperty.CLIENT_DESCRIPTION, "Test"));
					}
				}
				

> // TODO Auto-generated method stub
				

			}
```
so I want to change the Client description by typing in a text message
would be nice to hear something thx

**Comment by rogermb** [comment]
@TheKryZan You need to use the client's ID as the first argument to editClient 😃 

If you're only going to edit a single client property, you could also just use the `editClient(int, ClientProperty, String)` overload which has been added in the 2 years that this issue has been closed for.

Example:

```java
api.editClient(e.getInvokerId(), ClientProperty.CLIENT_DESCRIPTION, "Test");
```
