### ISSUE TITLE
Example of the new ReconnectingConnectionHandler

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#108]
Hello there,
I would like to see an example of the new ReconnectingConnectionHandler.

Kind regards

**Comment by Firedroide** [comment]
[ReconnectExample](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ReconnectExample.java) is already up-to-date :stuck_out_tongue:

**Comment by Firedroide** [comment]
Closed due to no further input; the issue has probably been resolved.
