### ISSUE TITLE
Create Channel with JoinPower

### ISSUE THREAD

**Issue by jorio2311** [TheHolyWaffle/TeamSpeak-3-Java-API#109]
Hey,

is there a possibility to create a channel with join power? I don't found any ChannelProperty that fits.

LG

**Comment by Firedroide** [comment]
Join power (and other powers) are actually not channel properties but rather channel permissions.
You can update these like so:

[`addChannelPermission(channelId, "i_channel_needed_join_power", yourValueHere)`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L223)  

This will overwrite the current join power, provided of course that your server query has the required permissions to do so.

Does this resolve your issue?

**Comment by jorio2311** [comment]
Hi,

it does! Thank you very much!

**Comment by Firedroide** [comment]
You're welcome! :smile:

By the way, we also have a [gitter channel ](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) for this repository that is especially well suited for these short question that don't really require the formality of a issue report. :stuck_out_tongue:
