### ISSUE TITLE
moveChannel

### ISSUE THREAD

**Issue by Chlastak** [TheHolyWaffle/TeamSpeak-3-Java-API#110]
Hello,
is here way how can I move channel and keep channel parent ?
Because if I use method api.moveChannel(channelId, parentId, channelOrder);
I keep getting this error
[channelmove] < error id=770 msg=already\smember\sof\schannel
If I change parentId it work fine but I want keep channel in that same subchannel list.

**Comment by Firedroide** [comment]
The JavaDoc of that method (that I wrote) actually mentions

> Also note that a channel cannot be re-ordered without also changing its parent channel.

So it might actually be impossible or maybe there's just some kind of trick I don't know about already. Anyways, for now you're probably best off just moving the channel to the root level and then moving it back into the desired position.

**Comment by Firedroide** [comment]
After some google-fu it seems there **is** actually a way to do this!
It seems like you can just use `editChannel` to change the channel property.

I'll leave this issue open to remind me to add this to the documentation of that method.

Thank you very much for creating this issue. If any other issues crop up, feel free to open another issue on GitHub or join us over on [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API), which is especially well-suited for shorter questions. :smile:

**Comment by Chlastak** [comment]
It work great thanks

**Comment by Firedroide** [comment]
Added a note to the JavaDoc of `moveChannel` in 52cc06eb7c2f4c66009201de9a46aa55be51609c

Closed.
