### ISSUE TITLE
Edit client to client volume

### ISSUE THREAD

**Issue by Cristaling** [TheHolyWaffle/TeamSpeak-3-Java-API#111]
Is there a way to mute some clients for other clients or to change the 3D sound position of a client to another?

**Comment by Kakifrucht** [comment]
This is client side, so no.

**Comment by Cristaling** [comment]
So the server always sends all the voice over to each client?

I was expecting that it would be possible to manage voices sent over as it would've been more efficient than sending the whole data packet...

**Comment by Kakifrucht** [comment]
The only way to mute a client server side is by adding talk power to a channel. Teamspeak does not support server sided client muting, Mumble for instance does.
