### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by ElDzi** [TheHolyWaffle/TeamSpeak-3-Java-API#114]
How to add group for client? I need add new group for player but idk how ;D

**Comment by Firedroide** [comment]
- Adding a server group with [addClientToServerGroup(int, int)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L268)
- Setting the channel group for a client inside a channel with [setClientChannelGroup(int, int, int)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3412)
- Please also consider using some kind of search function inside TS3Api. I always help if I can, but I'm not a search engine.
