### ISSUE TITLE
getClientDatabaseId?

### ISSUE THREAD

**Issue by Assassins88** [TheHolyWaffle/TeamSpeak-3-Java-API#117]
Is there a way, that i can use getClientDatabaseId from the ClientJoinEvent in the TextMessageEvent?

**Comment by Firedroide** [comment]
You can't get the database ID from that event directly, but you can get the client's client ID with [`getInvokerId`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/BaseEvent.java#L39) and their unique ID with [`getInvokerUniqueId`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/BaseEvent.java#L47).

After that, you can use `getClientInfo`, `getClientByUId`, `getDatabaseClientInfo` or `getDatabaseClientByUId` from [`TS3Api`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java) to get a `ClientInfo` or `DatabaseClientInfo`, all of which contain the client's database ID.

**Comment by Assassins88** [comment]
Yeah, it work's. Thx. <3
