### ISSUE TITLE
How to get Clients in a Channel ? 

### ISSUE THREAD

**Issue by Spined** [TheHolyWaffle/TeamSpeak-3-Java-API#118]
I was wondering about if you could get all the clients of a Channel ?
pls anwer asap

**Comment by Firedroide** [comment]
1. Call `TS3Api.getClients()`
2. Use your brain

**Comment by Spined** [comment]
I thought there was an Method for that. I know how to do it like this, Allthough it would be easier if you would do an Method for that , thank you.

**Comment by Firedroide** [comment]
It was decided that we would not add any methods which would only deal with collections, mostly because it would add tons of boilerplate code that we would have to maintain while not providing any real benefits. If you have Java 8, you can get the same kind of functionality quite easily:

```java
List<Client> clients = ts3Api.getClients();
clients.removeIf(client -> client.getChannelId() != yourChannelIdHere);
```
