### ISSUE TITLE
Channel Parent

### ISSUE THREAD

**Issue by dnagl** [TheHolyWaffle/TeamSpeak-3-Java-API#119]
Is it possible create a channel which has a parent channel?

**Comment by Firedroide** [comment]
That should be possible, yeah :smile:

Just add [`ChannelProperties.CPID`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/ChannelProperty.java#L62) and the ID of your parent channel to the map of channel properties you pass along to [`createChannel`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L700).

`CPID` is just the abbreviation TeamSpeak uses for "channel parent ID", by the way :smile:

**Comment by dnagl** [comment]
Ah ok thanks ;)
While reading again your example I came to the same result ;)

btw nice API :)

**Comment by Firedroide** [comment]
Thanks! :smile:

Have a nice day!
