### ISSUE TITLE
Grant

### ISSUE THREAD

**Issue by nfacha** [TheHolyWaffle/TeamSpeak-3-Java-API#120]
There is is no option to modify or remove the grant value of a server group permission

**Comment by Firedroide** [comment]
Sorry for not responding to this earlier, I overlooked this issue.

TS3's grant permissions aren't actually special permissions values, they are just another permission with a prefix that correlate with the actual permission.

For a permission `i_x` or `b_x` there will always be (or at least should always be) a permission called `i_needed_modify_power_x`, which is basically your grant permission.

The TS3 permissions GUI hides these permissions from you and just shows you their values as that "grant" value.

More info [in this document](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Permissions%20Guide.txt) explaining the TS3 permission system.

**Comment by nfacha** [comment]
Thanks :)
