### ISSUE TITLE
Set banner on server

### ISSUE THREAD

**Issue by Assassins88** [TheHolyWaffle/TeamSpeak-3-Java-API#133]
How i can set a new serverbanner on a virtual server?

**Comment by Firedroide** [comment]
Use [`TS3Api#editServer`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1614) and give it a map containing `VirtualServerProperty.VIRTUALSERVER_HOSTBANNER_GFX_URL` mapping to the URL of your graphics.

That URL must be a normal HTTP(2) link as far as I can tell, links to files on the TS3 file repository (`ts3file://`) don't seem to work.

**Comment by Assassins88** [comment]
Ok, nice. Thanks for your fast answer. :)

**Comment by Firedroide** [comment]
You're welcome! 😄 

By the way, there's also `VIRTUALSERVER_HOSTBANNER_URL` that controls what URL you're sent to when you click on the banner and `VIRTUALSERVER_HOSTBANNER_MODE` that controls whether the banner is resized to fit, which might be of interest to you.
