### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by T0biii** [TheHolyWaffle/TeamSpeak-3-Java-API#138]
Hey,

i want to edit the Client Icon ID.
But i dont know how to edit this ID :( 

I Tried this:
api.editDatabaseClient(tclientId, mapOf(ClientProperty.CLIENT_ICON_ID, IconID));
and this:
api.editClient(tclientId, mapOf(ClientProperty.CLIENT_ICON_ID, IconID));

Any idee how i can change the id?

**Comment by rogermb** [comment]
Icon IDs are managed as *client permissions* on the TS3 server.
You'll need to use
```java
TS3Api#addClientPermission(int clientDBId, String permName, int value, boolean skipped)
```
to change it, where `clientDBId` is the client's *database* ID, `permName` is `"i_icon_id"`, `value` is the ID of the icon and `skipped` doesn't really matter can just be set to `false`.

Note that there is a difference between a "client (session) ID" and a "client database ID". If you do not have access to the client's database ID directly, you'll need to get a Client(Info) object from `TS3Api#getClientInfo(int clientId)` (or alternatively from `TS3Api#getClients()`) and call `getDatabaseId()` on that object.

Also note that *every* 32-bit integer value can be a valid icon ID, therefore `value` can also be negative or 0. Make sure you handle these cases correctly.

**Comment by Ventix** [comment]
@rogermb How can i get the icon and how can i upload the icon (.png file format)
