### ISSUE TITLE
Not visible?

### ISSUE THREAD

**Issue by Seltrox** [TheHolyWaffle/TeamSpeak-3-Java-API#139]
Hey!
1. Im Sorry for my bad english im german
2. I have made me a Bot with your API.
It works :)! But if my bot joins, he is not visible how can i fix it? :/

**Comment by Kakifrucht** [comment]
This API uses the Teamspeak query interface, it is not a standard client. You should still see it in the query count if you click on your server name in the interface on the right panel.

**Comment by rogermb** [comment]
Thanks for the fast and correct response @Kakifrucht :smile:
