### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by v0jf4x** [TheHolyWaffle/TeamSpeak-3-Java-API#144]
Hello, I would have the opportunity to optimize api?
it is terribly slow and eats a lot of resources.

For example, the method of execution sendPrivateMessage x10, send in 5 seconds, and in phpapi in 1-2 seconds

**Comment by Kakifrucht** [comment]
Set floodrate to unlimited [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Config.java#L64).

**Comment by v0jf4x** [comment]
@Kakifrucht thanks. close
