### ISSUE TITLE
Cannot register event on selected Channel ID

### ISSUE THREAD

**Issue by xNarkon** [TheHolyWaffle/TeamSpeak-3-Java-API#146]
Hello,

I'm trying to set the `api.registerEvent(TS3EventType.TEXT_CHANNEL, 3);` on channel ID 3 but It is not working properly, because even when I set the different channel, it always works only on the default server channel which is the ID 1. How can I force the query to be on the selected channel and listening there?

Am I doing something wrong?

**Comment by Henny022** [comment]
As far as i know the bot can only listen to the chat of the channel he is
in himself so you need to move him to channel 3 an try again

Am 15.12.2016 08:46 schrieb "xNarkon" <notifications@github.com>:

**Comment by xNarkon** [comment]
Sure, so the next question is, can I force him to connect to the specified channel instead of the default (1)?

**Comment by somefriggnidiot** [comment]
To the best of my knowledge, you'd have to just move the query to that channel after connecting. I don't believe it's possible to connect directly to a channel.

**Comment by Henny022** [comment]
You can there is a method called moveQuarry or something like that which
moves the bot to the given channel

Am 15.12.2016 15:07 schrieb "somefriggnidiot" <notifications@github.com>:

**Comment by xNarkon** [comment]
Ah, you are right, I'm just blind 👍 

Thx guys for fast response.

**Comment by rogermb** [comment]
The function to move the query is called [`TS3Api#moveQuery`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3620) 😛

Questions seem to have been answered, so I'll close this issue for now. If you have any other short-ish questions @xNarkon, we also have a [Gitter channel](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) where such questions can be asked a bit less formally.

Thanks for helping out so quickly @Henny022 and @somefriggnidiot :smile:

**Comment by rogermb** [comment]
Closed - questions seem to have been answered.
