### ISSUE TITLE
Question: events

### ISSUE THREAD

**Issue by Hakens** [TheHolyWaffle/TeamSpeak-3-Java-API#149]
Hi!

Can someone explain me how to get TargetChannelId() in onTextMessage event?

I want do chatbot that speak with user who join specific channel, but i dont know how to listen private chat in bot

2nd Question:
How to add now answer from user to a variable in clientmoventevent?

**Comment by somefriggnidiot** [comment]
You can determine with which method the user contacted the bot by checking `messageEvent.getTargetMode()` and comparing it to either `TextMessageTargetMode.CLIENT` for private chat, `TextMessageTargetMode.SERVER` for global chat, or `TextMessageTargetMode.CHANNEL` for channel chat.

You can then reply generically by using `api.sendTextMessage()` or by a specific method by using the other "send message" commands.

**Comment by Hakens** [comment]
Hmm, i have TextMessageTargetMode in event public void onTextMessage(TextMessageEvent e) 
but this not work in onClientMoved(ClientMovedEvent e)
I want something like this:
User join to channel id 2675
bot sends him some messages on private chat   // this is already done
now i want message what user write in private to bot add to a variable in onClientMoved event

**Comment by somefriggnidiot** [comment]
I am not entirely sure that is possible (though there are those more familiar with the API than I.) 

From my understanding, the `onClientMoved` event no longer exists once everything within it ends execution. To edit a variable within `onClientMoved` with contents received in an `onTextMessage` event, I believe you would need some sort of external variable/class/object that persists through those events.

**Comment by Hakens** [comment]
I will wait for answer someone who is more familiar with this api
maybe @rogermb will answer:D

**Comment by somefriggnidiot** [comment]
There is also [the Gitter chat](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). You may find others who have attempted the same. He is fairly active there, as well. Sorry I could not help.

**Comment by rogermb** [comment]
Heyo :smile:

First of all, about the code snippet you've posted:
- Calling `api.getClientInfo` multiple times is inefficient. Every time you call a method on a `TS3Api` object, a command must be sent to the TS3 server, which takes time. Instead, store the answer like this: `ClientInfo client = api.getClientInfo(event.getClientId());`
- `event.getClientId()` returns the client ID of the client who sent that message. `ClientInfo#getId` also returns the client ID. Therefore the first line (`api.getClientInfo(event.getClientId()).getId();`) is even more redundant.  Just replace it with `event.getClientId()`.
- Consider using English variable and function names throughout your program. It makes it so much easier to understand what's going on for people who don't speak your language.

> To edit a variable within onClientMoved with contents received in an onTextMessage event, I believe you would need some sort of external variable/class/object that persists through those events.

Yes, exactly that. You're lucky Java isn't a purely stateless functional programming language 😛 

> Can someone explain me how to get TargetChannelId() in onTextMessage event

Clients who send text messages don't have "target channels". They are *in* a channel.
So you could just - again - get a `ClientInfo` object, from which you could retrieve the ID of the client's current channel by using `ClientInfo#getChannelId`.

e.g.

```java
ClientInfo client = api.getClientInfo(event.getClientId());
int channelId = client.getChannelId();
```

> How to add now answer from user to a variable in clientmoventevent?

So if the answer is a `String` and the user can be identified by their client ID, we could simply make a `HashMap<Integer, String>` to store their answers. You're not giving me much to work with, so I've freely interpreted some things 😛   
Let's use that in the code example below.

---

We'll make the `TS3Listener` / `TS3EventAdapter` a full fledged class with instance variables

```java
// This is just an example to demonstrate how this *could* work
public class TS3ResponseListener /* better name needed */ extends TS3EventAdapter {

	private final TS3Api api;
	private final Map<Integer, String> lastAnswer;

	public TS3ResponseListener(TS3Api api) {
		this.api = api;
		this.lastAnswer = new HashMap<>();
	}

	@Override
	public void onTextMessage(TextMessageEvent e) {
		if (e.getTargetMode() != TextMessageTargetMode.CLIENT) {
			return; // We only want private messages here
		}

		// getInvokerId gets the ID of the client who CAUSED
		// this event to happen. Doesn't work for all events!
		ClientInfo client = api.getClientInfo(e.getInvokerId());
		int channelId = client.getChannelId();

		// I don't know, stupid example is stupid
		String answer = e.getMessage() + " " + channelId;
		lastAnswer.put(client.getId(), answer);
	}

	@Override
	public void onClientMoved(ClientMovedEvent e) {
		int clientId = e.getClientId();

		if (e.getTargetChannelId() == 2675) {
			String answer = lastAnswer.remove(clientId);
			if (answer == null) answer = "(none)";
			api.sendPrivateMessage(clientId, "Your last answer was: " + answer);
		}
	}
}
```

---

Please note that I didn't test that code and it wouldn't do anything useful anyways. Just use it as an illustration how one could bring state into such a listener.

**Comment by Hakens** [comment]
Thanks for reply!
I will make something tommorow based on knowledge what u give to me and will reply here :)
And of course will test this code:)
Good night!

**Comment by Hakens** [comment]
> ```
if(newChannel==2675){
	            		int idclient = api.getClientInfo(event.getClientId()).getId();
	            		String nickuserwhojoin= api.getClientInfo(event.getClientId()).getNickname(); 
		            	String channel_name= api.getChannelInfo(event.getTargetChannelId()).getName();
		            	
	            		api.sendPrivateMessage(idklienta, "Witaj "+nickwchodzacegoo+ " na kanale pomocy!");// Hello + nickuserwhojoin+ on channel Help
	            		api.sendPrivateMessage(idklienta, "Jeżeli potrzebujesz nowego kanału napisz 1");// If u need new channel write 1
	            		api.sendPrivateMessage(idklienta, "Jeżeli potrzebujesz nowych ikonek napisz 2");// if u need new icons write 2
	            		api.sendPrivateMessage(idklienta, "Jeżeli potrzebujesz pomocy w związku z Craftcore  napisz 3");// etc etc
```
Translated for english :D

**Comment by Hakens** [comment]
Hey,
I tested this all, and still after write to bot nothing happend,
```
private final TS3Api api;
		private static Map<Integer, String> lastAnswer;

		public CreateChannelExample(TS3Api api) {
			this.api = api;
			this.lastAnswer = new HashMap<>();
		}
```
Eclipse change ur code to that cuz Cannot make a static reference to the non-static field lastAnswer
I rly dont know why but its not work
