### ISSUE TITLE
[Question] Command args

### ISSUE THREAD

**Issue by RyuZocktAT** [TheHolyWaffle/TeamSpeak-3-Java-API#151]
Can someone send me a code snippet or tutorial for command args?

I want to make the command "!check <USER>" to show information about the specific user, but dont know how to make an arg ^^

Thanks in advance
Ryu

**Comment by Henny022** [comment]
I use String.split, you can look it up in the java docs for details on how
it works.

**Comment by RyuZocktAT** [comment]
`String message = e.getMessage().toLowerCase();
						String[] args = message.split(" ");
						String args0 = args[0];
						String args1 = args[1];
						String args2 = args[2];

						if (message.equals("!upgrade")) {
							if(args0 != null && args1 != null && args2 == null){
                                                             //Stuff Here
                                                        }
`

Wahts my error?

**Comment by Henny022** [comment]
```
        String message = event.getMessage().toLowerCase();
        String[] arguments = message.split(" ");
        if(arguments.length == 0)
            //TODO send an error to the user, that no command was given
        if(arguments[0].equals("!upgrade"))
        {
            try
            {
                //TODO Insert your Code here. If the user gives too few Arguments, java throws an exception and runs the catch block
            }
            catch(ArrayIndexOutOfBoundsException e)
            {
                //TODO Send an error to the client that there were to few Arguments
                //example message "Too few arguments were given too command \"!upgrade\".\nUsage: \"!upgrade <insert the arguments you want the user to give>\"."
            }
        }
        else if(arguments[0].equals("your other commands"))
        {
            //TODO insert your other commands with their code
        }
        else
        {
            //TODO send an error message, that no valid command was given
        }
```
I marked the things you need to change with TODO
Don't access the array without checking the length of the array or catching an ArrayIndexOutOfBoundsException, or one might be thrown on incorrect command usage and breaks your bot.

**Comment by RyuZocktAT** [comment]
Nice thanks now it works :)

Can you help me with another thing?
I want to make the Bot visible(Like a client in a channel)

**Comment by somefriggnidiot** [comment]
Query accounts cannot be made universally visible. Users must enable the showing of query connections from the server's bookmark on their end of they have the permissions to do so.

**Comment by RyuZocktAT** [comment]
Ok but is der a way to create a FakeClient wich interact to tje commands?

**Comment by somefriggnidiot** [comment]
There are ways to go about doing such, I imagine, but it would most likely involve running another client and having the text read from that application. If you're simply looking to have the bot be easily accessible, consider instead messaging users on connection, or establishing an easy trigger (such as joining a certain channel, or using a certain command.)

**Comment by Henny022** [comment]
If you want your bot to be visible you should make a client bot and not a
querry one, but I don't know how to do that or if it's even possible.

You could try using a plugin

**Comment by RyuZocktAT** [comment]
Ok thanks going to close this thread now :)
