### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by RyuZocktAT** [TheHolyWaffle/TeamSpeak-3-Java-API#152]
Here is a Screenshot: http://prntscr.com/dri3zu

Can someone help me?

**Comment by rogermb** [comment]
Important part of that stack trace

    java.net.ConnectException: Connection timed out

Obviously, either the IP or **query** port you're using is incorrect, or your TS3 server is not reachable from your machine.

- To set the IP, use `TS3Config#setHost(String)`
- To set the query port, use `TS3Config#setQueryPort(int)`
- Make sure to pass your TS3Config instance to the constructor of TS3Query

The [examples directory](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/master/example) also contains some good resources to get started.

**Comment by RyuZocktAT** [comment]
Ok thank you :)
