### ISSUE TITLE
Is there any way:

### ISSUE THREAD

**Issue by CrzassassinPrivate** [TheHolyWaffle/TeamSpeak-3-Java-API#154]
Is there anyway to make code have a physical representation like make it show as an actual account on the teamspeak server instead of an invisible ghost?

**Comment by rogermb** [comment]
Not by default and only for those with the required permissions (*i_client_serverquery_view_power*), but there is a way. You need to create a bookmark for the server, show the advanced options and then check "Show ServerQuery Clients".

If you want to make the query visible to everyone, you'll probably need a normal TS3 client that you're "remote-controlling" via the Client Query protocol. This API only supports the Server Query protocol, so you'll have to find another way to do that.

Or you could adapt this API and maybe even submit a pull request, which would also be great 😛
