### ISSUE TITLE
Listen to all channels

### ISSUE THREAD

**Issue by metrickstar** [TheHolyWaffle/TeamSpeak-3-Java-API#159]
Is there a way to listen to **all** Channels?
I want to thank you for this awesome Api, I really appreciate the work.

Regards,
Stephan

**Comment by MCelements** [comment]
You have to connect a query in each channel

**Comment by Henny022** [comment]
As far as i know, the querry only gets events for the channel he is in,
because teamspeak does not provide information about other channels.

**Comment by rogermb** [comment]
As @MCelements and @Henny022 have already mentioned: This is, unfortunately, a limitation of the TS3 server query interface itself. Every query can only listen to the channel they're currently in. So if you really *need to* listen to each channel's chat, you'll have to use multiple queries.

Alternatively - if you just need clients to be able to contact your query - you could either set up a "bot channel" somewhere, or you could send each client a PM when they join.
