### ISSUE TITLE
[Question] How to get client IP?

### ISSUE THREAD

**Issue by DiscowZombie** [TheHolyWaffle/TeamSpeak-3-Java-API#161]
Hello,

I would like to `getClientIP()` when they joined. How can I do this?

**Comment by rogermb** [comment]
Heyo!

If the event object doesn't contain the information you need, you'll have to request it from the server:

```java
TS3Api api = /* Declared somewhere */
int clientId = e.getClientId();
ClientInfo client = api.getClientInfo(clientId);
String ipAddress = client.getIp();
```

**Comment by DiscowZombie** [comment]
Ok, thank you :D
