### ISSUE TITLE
[Question] How to join another Channel

### ISSUE THREAD

**Issue by nikkimas** [TheHolyWaffle/TeamSpeak-3-Java-API#162]
Hey, very nice API!

How do I change the channel of the Query Client? 
Atm I'm doing it via YaTQA, and I cand find the method.
Am I blind or does it not exist?

-Dj

**Comment by rogermb** [comment]
Heyo!

I believe you're looking for [`TS3Api#moveQuery(int)`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/165739aa9b0d2255f3e48a4d0137ed7e6ad8c53a/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3620) :smile:

**Comment by nikkimas** [comment]
Thank you! That helped!

For everyone needing it aswell: 
`final TS3Api api = query.getApi();`
`api.login("serveradmin", "querypassword");`
`api.selectVirtualServerById(1);`
`api.setNickname("Bot Bot");`	
`api.moveQuery(ChannelID);`
`api.sendChannelMessage("Bot ist online!");`

-Dj
