### ISSUE TITLE
Reconnect on restart

### ISSUE THREAD

**Issue by stephan-strate** [TheHolyWaffle/TeamSpeak-3-Java-API#164]
Is there a possibility to let the bot reconnect, when server restarts?
The normal client trys to reconnect aswell. It's a little bit stupid, that the whole bot shutdowns right as the server shutdowns.

**Comment by rogermb** [comment]
The API has a built-in reconnect feature. Check out an example application [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ReconnectExample.java).
