### ISSUE TITLE
get Message

### ISSUE THREAD

**Issue by JackboyPlay** [TheHolyWaffle/TeamSpeak-3-Java-API#166]
Hello folks, why wouldn't the TextMessageEvent called, if I write a message back to the server query?
Is it pssible to make it that it would be detected?

**Comment by Kakifrucht** [comment]
It will be called, if configured correctly. Did you register your listeners?

**Comment by somefriggnidiot** [comment]
Ensure you're registered to listen for that event with `api.registerEvent(TS3EventType.TEXT_PRIVATE)` if you're registering specifically, or `api.registerAllEvents()` if you're registering generally. After that, a `TextMessageEvent` should be fired if you've set up a listener for it. If you have not, see the [event listener example](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/EventListenerExample.java), specifically lines 57-60:
```
@Override   
public void onTextMessage(TextMessageEvent e) {   
    System.out.println("Text message received in " + e.getTargetMode());   
}
