### ISSUE TITLE
how to registerEvent as anonymous client ?

### ISSUE THREAD

**Issue by CharlZG** [TheHolyWaffle/TeamSpeak-3-Java-API#173]
I get the following error when registering an event without logging in, just connected as anonymous client:
`[2017-03-20 02:15:54.965] > servernotifyregister event=textchannel id=0
[2017-03-20 02:15:54.968] [servernotifyregister] < error id=2568 msg=insufficient\sclient\spermissions failed_permid=43
[2017-03-20 02:15:54.970] [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=43}`

it happens when this code is executed: `api.registerEvent(TS3EventType.TEXT_CHANNEL, 0);`
im able to send messages but cant recieve any, please help. thanks.

**Comment by MCelements** [comment]
The Query need the permission "b_virtualserver_notify_register"

**Comment by CharlZG** [comment]
How can i set that permission ?

**Comment by rogermb** [comment]
From your TS3 client's permissions manager (in advanced mode). Remember that to modify permissions you'll *also* need lots of permissions, so you'll most likely have to be a server administrator on this server to accomplish this. You might even need to use the `serveradmin` query account.
