### ISSUE TITLE
Use slf4j instead of java.util.logging

### ISSUE THREAD

**Issue by Kakifrucht** [TheHolyWaffle/TeamSpeak-3-Java-API#174]
This allows us to use whatever logging framework we want (log4j2 for example), as slf4j chooses the best available logger in classpath at Runtime. Users who rather want to stay with java.util.logging can do so, as that would be slf4j's default logging framework if no other was found.

Performance impact would be negliglible, however I guess the current [log file writer](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/log/LogHandler.java) would have to be removed, it could easily be replaced with log4j's async implemententation via .xml file and adding log4j(2) to classpath/dependencies.

**Comment by rogermb** [comment]
Hmm, I don't really know about this one. Maybe @TheHolyWaffle can chime in.

On the plus side, this would certainly make configuring logging easier. It may make the API integrate with other APIs / frameworks / whatever on the classpath better.

On the other hand, we currently don't have any dependencies yet. Adding SLF4J would introduce that dependency as well as any transitive dependencies that project may have (if there are any). I'm worried that this might make the API more difficult to distribute and it might complicate our own build scripts, as well.

I'm also uncertain if this is even necessary, as j.u.logging is already quite extendable and customizable. There's also a project that acts as a bridge from j.u.logging to SLF4J, so people who rely on SLF4J might be able to just use that bridge.

But I really feel like I shouldn't be the one making the decision on this issue - I lack the complete picture when it comes to logging.

**Comment by Kakifrucht** [comment]
It appears to be pretty standard that especially API's don't rely on a given logging implementation.
Seems to be some kind of standard to use slf4j here, but I also lack quite some experience. It doesn't come with any additional dependencies.

Additonally I don't feel that, while convenient for some, it is not the responsibility of this API to provide additional log writing implementations. Setting these up with log4j2 is really simple and far more performant. Besides shipping a log4j xml file as resource with the jar there is nothing else that needs to be added.

Using jul-to-slf4j module for now, however generally I'm not a fan of like the idea of forcing a logging implementation on users. Especially since log4j2 has so many benefits compared to jul.

**Comment by TheHolyWaffle** [comment]
I'd be OK with adding the slf4j dependency. Also, I don't think adding this dependency will make it harder for us to distribute the dependency. 
- Those who reference us through their pom will get the sfl4j dependency for free, because that's how maven works. 
- And for those who add the jar manually to their build path: we can add an extra section to the pom to also make a "fat" jar on deploy. The fat jar would include all dependencies and can be used standalone. Can be done through the maven-shade-plugin.

What might require more thought is how we would handle the current LogHandler, as this would become redundant. (https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/log/LogHandler.java)

**Comment by Kakifrucht** [comment]
Are you opposed to just dropping it? In my opinion the log writer is redundant.

**Comment by TheHolyWaffle** [comment]
I agree with your points. This is something we should do for next release.

**Comment by Kakifrucht** [comment]
Another thing I'm wondering about, why are command errors logged at level SEVERE? If a command execution is not successful the API returns false already, so we can handle that case. I thing it should be INFO or even lower at FINE/DEBUG.

[Ref](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/da0475833e07898ec692f82ef4c30152b03cefa5/src/main/java/com/github/theholywaffle/teamspeak3/SocketReader.java#L119)

**Comment by TheHolyWaffle** [comment]
I don't agree with that. Not receiving a response from the server is
unexpected and should never happen. It usually indicates a connection issue.

2017-04-14 19:02 GMT+02:00 Fabian <notifications@github.com>:

**Comment by Kakifrucht** [comment]
I'm talking about command errors, as in invalid id as parameter etc.

**Comment by rogermb** [comment]
Resolved by merging #185.
