### ISSUE TITLE
Channel creator

### ISSUE THREAD

**Issue by lucaazalim** [TheHolyWaffle/TeamSpeak-3-Java-API#178]
Hello,

I would like to get who created the channel on ChannelCreateEvent. Is it possible?

**Comment by Scrumplex** [comment]
You can use `event.getInvokerId()` to get the id of the client who created the channel. Use `api.getClientInfo(event.getInvokeId());` to get other Information like nickname

**Comment by lucaazalim** [comment]
Oh, that was right on my face. Thanks!
