### ISSUE TITLE
Method "on Virtual Server stop"

### ISSUE THREAD

**Issue by Luckycleri** [TheHolyWaffle/TeamSpeak-3-Java-API#181]
Hello! Is there any way to check if the virtual server is still running? The Bot is using SID 5, and i am trying to establish some way to handle a stopped virtual server as errorhandling. 
```
// Use default exponential backoff reconnect strategy
		config.setReconnectStrategy(ReconnectStrategy.exponentialBackoff());

		// Methoden für connect und disconnect
		config.setConnectionHandler(new ConnectionHandler() {
			@Override
			public void onConnect(TS3Query ts3Query) {
				
			}

			@Override
			public void onDisconnect(TS3Query ts3Query) {
                            System.out.println("Disconnected");
                            try {
                                dateSaver.saveFile((HashMap) dateMap);
                            } catch (IOException ex) {
                                // ERROR
                            }
			}
		});
``` 
Does seem to work only on full Serverstop or complete disconnect from query account. Th onDisconnect() method does not get triggered on stopped virtual server for some reason. Am i doing it wrong?

Thanks for your help in advance.

**Comment by TheHolyWaffle** [comment]
You are correct. This handler only applies to a connection made with the query server.

Does the server send some data back to use when the virtual server closes? If that is the case, we could add separate handlers that are triggered on **virtual** server (dis)connections.  @rogermb ?

**Comment by rogermb** [comment]
Hi! Sorry for taking so long to get to your issue, I hope you can forgive me :blush:

As far as I know, there's no event for when a virtual server is started or stopped. In other words: the query likely wouldn't even know it if they got booted off a virtual server.

I'm unfortunately unable to test any of this locally, as starting and stopping virtual servers is impossible with the free server license and I don't know anyone who owns a commercial TS3 license and who would let me fool around on their server. I also wasn't able to find any first- or third-party documentation about this issue.

The only other way of simulating this that came to mind would be kicking a query from the server - but unfortunately, the `clientkick` command does not support kicking server queries...

If there's any way you could start a query, join your virtual server with it, then register all events and finally stop your virtual server and send the logs of the communication between the server query client and the TS3 server to me, I'd be extremely grateful.

---

Now, for some (terrible) workarounds:

If you call [`TS3Api#whoAmI`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4655), the response will contain an [entry](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/ServerQueryInfo.java#L153) with your current virtual server ID - however, this is a poor replacement for a real event.

There's also the [`TS3Api#getVirtualServers`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3015) method, which should return a list of all virtual servers and whether those are online or not.

**Comment by Luckycleri** [comment]
Hello!
 I would love to somehow help to improve this wonderfull api. I am not exactly sure what you mean by: 

> If there's any way you could start a query, join your virtual server with it, then register all events and finally stop your virtual server and send the logs of the communication between the server query client and the TS3 server to me, I'd be extremely grateful.

Should i let my bot register all events, manually stop the virtual server and then send the java console log to you? Else i would need a small explaination about how to help you out! 

Anyway to anybody may reading this before a potential Event is developed: 
This may also be an ugly solution but you could also create a timer which checks if "api.getServerInfo().getId()" is "-1". -1 seems to be the placeholder-Id for not being on any server. 

Greeting and thanks for your help!

**Comment by rogermb** [comment]
Hi again! Sorry for the long delay, I've been away from home for a few days.

> Should i let my bot register all events, manually stop the virtual server and then send the java console log to you?

Yup, exactly that :smile:

That way I'll know if the server actually sends any information back to us when a virtual server is stopped or not.
