### ISSUE TITLE
i guess you speld Server Wrong

### ISSUE THREAD

**Issue by K0IN** [TheHolyWaffle/TeamSpeak-3-Java-API#182]
"[SEVERE] Command sendtextmessage was not answered in time."(just example)

**Comment by somefriggnidiot** [comment]
That is a debug message of "Severe" severity.

**Comment by TheHolyWaffle** [comment]
Haha, this is quite the bug report :) It's indeed "severe", as in "info" and "warning". I guess I can close this.
