### ISSUE TITLE
PrivateMessageListener?

### ISSUE THREAD

**Issue by tei06398** [TheHolyWaffle/TeamSpeak-3-Java-API#183]
I think it would be nice to open Private Messages as a mode of input to any, bot for example, running on the TS server, due to the fact that one could do much more interesting things with the added features...

Thanks :+1:

**Comment by Kakifrucht** [comment]
Just listen to TextMessageEvent and check if ```TextMessageEvent::getTargetMode().equals(TextMessageTargetMode.CLIENT)```

**Comment by tei06398** [comment]
Thanks for the quick reply - I couldn't figure that out for the life of me :laughing:
