### ISSUE TITLE
TS3Api/Async code duplication

### ISSUE THREAD

**Issue by Kakifrucht** [TheHolyWaffle/TeamSpeak-3-Java-API#186]
Right now the API duplicates a whole lot of code in it's async implementation. There surely is a more pretty way to achieve this functionality. How about using TS3Api as a simple wrapper for TS3ApiAsync? Caveat is additional overhead.

**Comment by TheHolyWaffle** [comment]
Totally correct, we've been thinking the same.

**Comment by rogermb** [comment]
Every TS3Api call could basically be replaced by calling the same method in TS3ApiAsync and adding `.getUninterruptibly()` at the end, yeah.

We'd need to either switch TS3Api from using `null` or `-1` to throwing exceptions, or alternatively do some kind of translation between TS3ApiAsync's and TS3Api's return values, though.

**Comment by Kakifrucht** [comment]
> We'd need to either switch TS3Api from using null or -1 to throwing exceptions, or alternatively do some kind of translation between TS3ApiAsync's and TS3Api's return values, though.

I don't quite understand, can you elaborate on why that would be necessary? Aren't the return values always the same?

**Comment by rogermb** [comment]
> Aren't the return values always the same?

They return the same thing if the command succeeds, yes. But if it fails, the synchronous API will silently discard the error after doing some logging and return `null`, `-1` or similar. The asynchronous API, on the other hand, throws an exception with details about what exactly went wrong.

Returning `null` or `-1` is (in my opinion) bad design, as these erroneous return values just cause exceptions further down in the code, but it's what we're currently using, hence we'd need to add some translation layer.

**Comment by Kakifrucht** [comment]
So ```getUninterruptibly()``` might throw a RuntimeException, why do further changes have to be made to the code? Why not just silently pass it on?

**Comment by rogermb** [comment]
Fixed, see a1957178ebe989a996a49725f9d9a2c9540d6680 and 0776532cbc956f2b7c91d9f7095eba9fd798b5f1 :smile:
