### ISSUE TITLE
NullPointerException in SocketWriter

### ISSUE THREAD

**Issue by Nitwel** [TheHolyWaffle/TeamSpeak-3-Java-API#187]
At the moment, I´m working on a project witch creates channels automaticly, but sometimes the api throws this exception and stops working. I´ve even used a 10 second delay timer for each channel to create but it just throws this exception randomly and then totaly stops working. 

Here´s the Exception but you can also view it at: https://paste.myplayplanet.net/otuvilaziq.avrasm
Exception in thread "[TeamSpeak-3-Java-API] SocketWriter"
12:18:29 [SEVERE] java.lang.NullPointerException
12:18:29 [SEVERE]     at com.github.theholywaffle.teamspeak3.commands.CommandEncoding.encode(CommandEncoding.java:34)
12:18:29 [SEVERE]     at com.github.theholywaffle.teamspeak3.commands.parameter.KeyValueParam.build(KeyValueParam.java:55)
12:18:29 [SEVERE]     at com.github.theholywaffle.teamspeak3.commands.parameter.Parameter.toString(Parameter.java:35)
12:18:29 [SEVERE]     at java.lang.String.valueOf(String.java:2994)
12:18:29 [SEVERE]     at java.lang.StringBuilder.append(StringBuilder.java:131)
12:18:29 [SEVERE]     at com.github.theholywaffle.teamspeak3.commands.Command.toString(Command.java:127)
12:18:29 [SEVERE]     at com.github.theholywaffle.teamspeak3.SocketWriter.run(SocketWriter.java:56)

**Comment by TheHolyWaffle** [comment]
Based upon the log, it looks like you're missing an expected value when sending a command. Can you show us what command you're using and how you use it?

**Comment by Nitwel** [comment]
Hm, I thought about it and I thing its our Bot that creates the problem, I´ll try to find it and maybe I´ll be able to fix it by myself because at the fact that we uptaded the api version, our bot uses maybe old commands I guess. So thank you for your quick support

**Comment by rogermb** [comment]
I've made sure `KeyValueParam` can handle `null` correctly (see 42a8b01750ef9912bf6cb5771f80390af03cdd78) - but usually you shouldn't be passing `null` into any API methods anyways. ¯\\\_(ツ)_/¯

There hasn't been a release that includes that fix yet, but it hopefully shouldn't be too long until the next one.

Closed. Thank you very much for your bug report :smile:

**Comment by Nitwel** [comment]
Well thank you, after this one day this issue never occured again and everything works fine, even I dont know why this happened but it´s great to see that you´re working on this project so active. 😄 
best regards Nitwel
