### ISSUE TITLE
Beginning

### ISSUE THREAD

**Issue by krcanin** [TheHolyWaffle/TeamSpeak-3-Java-API#188]
Yo, I pretty know how to write code but I'm not sure how to work with java and how I can import the code inserted there... Can anyone give me the first steps?

**Comment by somefriggnidiot** [comment]
Are you at all familiar with Maven?

**Comment by krcanin** [comment]
Well, now I tried it with NetBeans... And no, I'm not. Btw, I just tried a simple script which connects and it says following:

run:
Exception in thread "main" com.github.theholywaffle.teamspeak3.api.exception.TS3ConnectionFailedException: Could not connect to the TeamSpeak3 server
	at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:85)
	at com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:116)
	at Test.main(Test.java:11)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:69)
	... 2 more
C:\Users\Gamer\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 1 second)

**Comment by rogermb** [comment]
Heyo! :smile:

First of all, you should download the [latest release of this API](https://search.maven.org/remote_content?g=com.github.theholywaffle&a=teamspeak3-api&v=LATEST&c=with-dependencies) and place the jar file into your project directory.

What happens next depends a lot on what IDE you're using. (Side note: if you're new at Java I'd really recommend using an IDE. They make writing code easier)

Basically, you need to add the jar file as a library in your IDE.

I've collected some stackoverflow links on how to do this in
1. [IntelliJ IDEA](http://stackoverflow.com/a/32853178)
1. [Eclipse](http://stackoverflow.com/a/2824531)
1. [Netbeans](http://stackoverflow.com/a/41552171)

After that, I'd recommend recreating one of the examples in the [examples directory](/examples). That way you can figure out whether you've included the library correctly without having to worry too much about bugs.

I hope this was helpful 😃 

@somefriggnidiot I don't think that starting with Maven is a good idea

**Comment by krcanin** [comment]
The next problem I get is that if I wanna connect to my local ts3 it puts no error but the bot doesn't appear as well.

TS3Config config = new TS3Config();
        config.setHost("FR3.ts-3.cx");
        config.setQueryPort(15772);
        
        TS3Query query = new TS3Query(config);
        query.connect();

And roger, I use Netbeans and if I'm not wrong I did nothing wrong. Maybe the real ts3 (local was just to test) makes problems because of the port I need ot change? It's FR3.ts-3.cx:15772 and I tried to change the port by config.setQueryPort(15772);

**Comment by somefriggnidiot** [comment]
RE: Maven
I find it's a good practice to start learning Maven as soon as possible. 😛 It greatly helps in long-lived and/or large projects. (That's not to say I may have forgotten there are relatively easier ways to do things... but we'll not talk about that.)

Also...
I highly recommend moving this subject to [the Gitter chat](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) just to cut down on response times.

**Comment by somefriggnidiot** [comment]
Note that your Virtual Server port (the one YOU use when connecting) is not necessarily your Query port.

**Comment by rogermb** [comment]
Well derp. Seems like you've already correctly added the project as a dependency.

The error you're getting is due to the host and / or the port not being correctly. You'll need to use the *query port* of the TS3 server. That port number is different from the *voice port* that you use to connect to your server with a regular TS3 client.

**Comment by krcanin** [comment]
Oh, so I don't need to change the query port right?

**Comment by somefriggnidiot** [comment]
You might, depending on what query port your server listens on.

**Comment by krcanin** [comment]
WTF... [2017-05-06 01:26:10.288] [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=217}

**Comment by rogermb** [comment]
Remember that, by default, you have close to no permissions on the TS3 server. You'll need to log in by using `TS3Api#logIn(username, password)` first :smile:

**Comment by somefriggnidiot** [comment]
So it appears that you've managed to at least connect to the physical server... Make sure you're using a username and password for a query account created by a privileged TS3 user.

**Comment by krcanin** [comment]
Ye but. As I'm on a sponsored ts3 I have not such login data.

**Comment by krcanin** [comment]
Is there something like a "guest login" in query data?

**Comment by somefriggnidiot** [comment]
You can create that login data from the client if you have the permissions to. (Tools->Server Query Login)

**Comment by krcanin** [comment]
I cannot, all server query things denied

**Comment by somefriggnidiot** [comment]
A guest login would essentially be logging in without a username/password. If your server allows that, then yes.

**Comment by somefriggnidiot** [comment]
I would recommend contacting your sponsor, explaining your situation, and asking for access. Should that fail, consider setting up a local server for testing purposes (or finding a better sponsor.)

**Comment by krcanin** [comment]
Well ok, on my local one it's all working...

**Comment by rogermb** [comment]
Well, in the end it all comes down to this permissions issue.

Your options are either to somehow acquire a server query login with the required permissions, or to modify the permissions of the default (guest) query server group.

**Comment by somefriggnidiot** [comment]
On the subject of acquiring a server query login... You may also be able to convince your sponsor to allow you a query account with basic admin permissions (move, message, kick, manage channels, etc.) if you can detail what you'll need it for. I've had similar issues with hosts in the past, and some may need to be walked through exactly which permission values you'll need...

**Comment by krcanin** [comment]
@rogermb are there any default data for the guest query server grup?
@somefriggnidiot it's actually just a test for me to see how this engine works... but in the end I maybe set up sth. like user joins my ts3, bot writes him, he writes back and gets added to "registered" group then or something like this, maybe if I connect to another server where it checks login data or something like that
