### ISSUE TITLE
How to create a channel with permissions?

### ISSUE THREAD

**Issue by dm94** [TheHolyWaffle/TeamSpeak-3-Java-API#189]
I want to create channels with the permission "i_channel_needed_join_power" and I do not know how to do it

**Comment by rogermb** [comment]
First, call `TS3Api#createChannel` to create a new channel. This command will return the ID of the newly created channel. Then use that ID when calling `TS3Api#addChannelPermission` to set the value of `i_channel_needed_join_power`.

There is no way to do both of these things atomically with 1 command. So a client *might* be able to get into the channel between its creation and you adjusting the needed join power. Thus if you must absolutely prevent a client from getting into a channel, you need to change the default join power - or just get a list of all clients after you've edited `i_channel_needed_join_power` and kick any clients that have snuck into the new channel 😛

**Comment by dm94** [comment]
Thank you very much now i prove it
