### ISSUE TITLE
ClientNicknameChangedEvent

### ISSUE THREAD

**Issue by Simonsator** [TheHolyWaffle/TeamSpeak-3-Java-API#190]
Would it be possible to implement a ClientNicknameChangedEvent?

**Comment by Kakifrucht** [comment]
Thsi API is a wrapper to the Teamspeak 3 Query Interface, which doesn't support said event, so no.

**Comment by rogermb** [comment]
Yup, you'd have to ask the TeamSpeak devs for that feature directly.

And while you could always try, I really doubt they'd introduce such a new feature this late into TeamSpeak's product lifecycle.

You'll need to solve your problem by getting a list of all clients in a fixed interval and detecting any changes to their nicknames.
