### ISSUE TITLE
Cant create channels???

### ISSUE THREAD

**Issue by pascal25565** [TheHolyWaffle/TeamSpeak-3-Java-API#194]
Hello i can't create channels, i have server admin permissions...

```java
		HashMap<ChannelProperty, String> map = new HashMap<>();
		map.put(ChannelProperty.CHANNEL_NAME, "Channel");
		map.put(ChannelProperty.CHANNEL_FLAG_PERMANENT, "1");
		getConnection().getApi().createChannel("Channel", map);
```
[2017-05-20 20:58:41.769] [SEVERE] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=83}

**Comment by rogermb** [comment]
The problem is likely just that  `ChannelProperty.CHANNEL_NAME` does not belong in the properties map. In other words, remove line 2 and it should work 😄

**Comment by pascal25565** [comment]
Thanks :D
