### ISSUE TITLE
Get dirname from the teamspeak?

### ISSUE THREAD

**Issue by pascal25565** [TheHolyWaffle/TeamSpeak-3-Java-API#195]
How can i get the dir name from the teamspeak?

Screen:
https://puu.sh/vWWRM/c23e757514.png

**Comment by rogermb** [comment]
First of all, what exactly would you need this for?

And second, it looks like this might be something specific to your hosting provider.

The name looks a bit like a UId, so it **might be** the unique ID of the virtual server.
To get that, you'd use

```java
TS3Api api = [...];
// Make sure you're logged in and on the correct virtual server!
VirtualServerInfo serverInfo = api.getServerInfo();
String uid = serverInfo.getUniqueIdentifier();
```

**Comment by pascal25565** [comment]
`TS3Api api = [...];
// Make sure you're logged in and on the correct virtual server!
VirtualServerInfo serverInfo = api.getServerInfo();
String uid = serverInfo.getUniqueIdentifier();`

this is unfortunately not the right one :(

**Comment by rogermb** [comment]
In that case, you will probably have to ask your hosting provider if there is a way to retrieve this folder name programmatically.

**Comment by pascal25565** [comment]
the icons from the server become in the Appdata dir

Look:
https://puu.sh/vWYfz/d9be2c7861.png

**Comment by rogermb** [comment]
Ah, I think I found out what it is! 😄 

It's the virtual server UId, but encoded with base 64 *again*.

So after the original code, add

```java
String folderName = Base64.getEncoder().encodeToString(uid.getBytes(StandardCharsets.UTF_8));
```

**Comment by pascal25565** [comment]
lmao omg thanks!

**Comment by rogermb** [comment]
You're welcome :blush:

Issue resolved, closed. If you have any other questions, feel free to re-open this issue, create a new one, or contact us in our chat room on [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) :smile:
