### ISSUE TITLE
identifying channel hopper

### ISSUE THREAD

**Issue by Assassins88** [TheHolyWaffle/TeamSpeak-3-Java-API#197]
Dear developer,
I was trying to identifying channel hopper. Now I am wondering if it is possible to track client channel movements but haven't found a way yet. Your API provides the ClientMovedEvent. Nevertheless we couldn't find a way to see the client movement. Is it just for moving a client by the Querry and do you might know a answer to our problem?

**Comment by KarlTheBee** [comment]
The ClientMoveEvent is fired _every time_ a client moves, not just when a query moves the client.
So just make a map containing the client id as key and the times the client fired the move event as the value and kick him, if he reaches a specific amount as value
Remember to decrease the value by time, so no one gets kicked if he's switching channels over a long period of time.
If you can't see the client move event, check if you registered all events, got the rights to subscribe every channel or provide an log

**Comment by Kakifrucht** [comment]
I think the ClientMovedEvent only handles moves into and out of the query's current channel.

**Comment by somefriggnidiot** [comment]
Karl is on the right path. Due to limitations of TS's query interface, we don't get information about where the moving client came from---only where they're going. As such, you'll have to track that all yourself.
