### ISSUE TITLE
HI how do i change the Channel Name?

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#200]
Hi i code an Ts3-Administration Bot and i cant rename an Channel:

Load.api.editChannel(642, --------)?
http://prntscr.com/fd0nu8

I tried Everything

-PS
Im German

**Comment by Kakifrucht** [comment]
That method takes a Map with a ``ChannelProperty`` as key and String as value.
Look into which ChannelProperties there are, you will find the one you need (hint, it's ``CHANNEL_NAME``), value would be the name.

**Comment by rogermb** [comment]
Or to put it more concisely: use `Collections.singletonMap(ChannelProperty.CHANNEL_NAME, "new name here")`

**Comment by mnjg123** [comment]
Thanks
