### ISSUE TITLE
How can i move an Random picked Client?

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#202]
http://prntscr.com/fd2r6y

It doesnt Work.

**Comment by Henny022** [comment]
1. your editor is telling you what's wrong, read its error message
2. stuff like this is better of in the gitter chat, there are people, that can help you, and this is not an issue with the API

**Comment by mnjg123** [comment]
@Henny022 

But i dont know what "channel" means.

http://prntscr.com/fd2y4c

I also Googled it.
