### ISSUE TITLE
What does ChannelBase channel mean

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#203]
But i dont know what "channel" means.
(ChannelBase channel)

http://prntscr.com/fd2y4c

I also Googled it.

-PS  Wer Deutsch kann kann bitte auch so schreiben ^^

**Comment by Kakifrucht** [comment]
No, we don't use German here. Anybody should be able to understand without third party tools for translation.
It means that the method you are using is taking a parameter named "channel" which is a ``ChannelBase`` object.

**Comment by Henny022** [comment]
something german to help you
http://openbook.rheinwerk-verlag.de/javainsel/javainsel_01_001.html
