### ISSUE TITLE
Get sender of TextMessageEvent

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#204]
Hi I want to Know how i get the sender of the TextMessageEvent

So i can Move someone to the Channel of the sender

**Comment by Henny022** [comment]
event.getInvoker*()
choose whichever method you need

**Comment by mnjg123** [comment]
@Henny022 
Thanks i  will do that in Future but,
i cant get the channel from the InvokerId?

**Comment by Henny022** [comment]
Use the id to get the client and then the channel from that.
Look into the javadoc to get the exact function names

**Comment by somefriggnidiot** [comment]
Since this is still open, I'll get a bit more specific... 

```
int clientId = event.getInvokerId();                 //Grabbing and storing the invoker's ID for later use.
ClientInfo client = api.getClientInfo(clientId);     //Calling the API to get the ClientInfo matched to that client ID.
int channelId = client.getChannelId();               //Pulling the user's channel from the ClientInfo object.
ChannelInfo channel = api.getChannelInfo(channelId); //Calling the API to get the ChannelInfo matched to that channel ID.
```
This is the generic/synchronous way of getting the invoker's channel in an event.
