### ISSUE TITLE
Is there a way to get a channel by ID?

### ISSUE THREAD

**Issue by jakeob28** [TheHolyWaffle/TeamSpeak-3-Java-API#205]
My current code changes the channel name of certain channels. Is it possible to just store their ID and get the channel by ID? It is a pain to get the channels by name, as I have multiple channels with each name, so I have to get the list then check if the ID matches the requested ID for each channel. Is this implemented in the API, and I'm missing something? Or do I have to do this myself?

**Comment by rogermb** [comment]
Yes, of course, please use `TS3Api#getChannelInfo(int channelId)`.

The reason why this function is called "getChannelInfo" and not e.g. "getChannelById" is because the server query command that is sent to the TS3 server is called `channelinfo` :smile:

**Comment by jakeob28** [comment]
Oops! Can't believe I missed that! Thanks.
