### ISSUE TITLE
Mute Players in Channel or even more

### ISSUE THREAD

**Issue by Taankly** [TheHolyWaffle/TeamSpeak-3-Java-API#207]
Hey, 

i try to make an ingame Voice Chat with your API. Is there any possible way to mute a player in a channel. Or even better, is there a possible way to mute a certain Client for another Client? 

Thanks for your response and your help!

Greetings Taankly

**Comment by somefriggnidiot** [comment]
<i><b>PREFACE: </b> For future reference, questions such as this are better suited for [the Gitter chat](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). The repo's "Issues" tab should be reserved only for problems with the API itself.</i>
<hr/>
I do not believe there is a way to mute a specific client for individuals; this is solely a user-end action. 

If you wish to mute a user in a channel, you should set their `i_client_talk_power` permission to be lesser than that of the `i_client_needed_talk_power` for the channel. With this, the user will not be able to speak at all within that channel.
