### ISSUE TITLE
Cannot get target from TextMessageEvent when TargetMode is "Client"

### ISSUE THREAD

**Issue by somefriggnidiot** [TheHolyWaffle/TeamSpeak-3-Java-API#209]
When targetmode=1 and target=X, you should be able to get X.

`[2017-06-12 19:31:18.550] < [event] notifytextmessage targetmode=1 msg=asdf target=5 invokerid=4 invokername=somefriggnidiot invokeruid=IxvaZIhWDu8PVn9NNs3Ryh\/j8hE=`

EDIT 1: API consumers can work around this by using: `api.getClientInfo(Integer.parseInt(event.get("target")))`

EDIT 2: Note that the above workaround may cause issues if you're applying it to message events without targets (i.e: those to channel/server.)

**Comment by rogermb** [comment]
Added in 40d05e8053d1a25cbd3c983756f3a1c3fe7aba48 🎉
