### ISSUE TITLE
Client ban event

### ISSUE THREAD

**Issue by Schmiddinger** [TheHolyWaffle/TeamSpeak-3-Java-API#213]
Hey,
Is there a way to check when a client was banned from the server? (ClientBanEvent or something else).
This event should have the parameters:
 - e.getBanMessage();
 - e.getAuthor();
 - e.getClient();
 - e.setBanMessage();

Thanks,
Schmiddinger

P.S.: Sorry for mistakes, I'm a 14 years old german boy

**Comment by somefriggnidiot** [comment]
This API supports all events fired the TeamSpeak. Since there is no event
for that in this API, it is not sent to us. It may however be part of
ClientLeaveEvent. I can't check at the moment, but it may be good to look
into.

**Comment by Schmiddinger** [comment]
Ok, thanks.
But is there a way to get a ban? The methode "api.getBans()" already exists, but how can I get a existing ban from a client?

**Comment by somefriggnidiot** [comment]
I can't tinker with anything at the moment, so I'm just speculating...

API.getBans returns a list of bans. Those will likely have the banned
user's database ID. With that DBID, you should be able to get their UID.

Regardless of how exactly this works, there's a 99% chance you'll be
linking things via Database ID since we're not necessarily dealing with
active connections.

**Comment by iProGamer** [comment]
Please answer this.
How can I detect bans?

**Comment by rogermb** [comment]
@iProGamer If a client is banned, a regular `ClientLeaveEvent` will be fired.

You can then use the reason id (`getReasonId`) to check whether the client was kicked or banned. You can find a list of known reason IDs in [the documentation](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/755c740523fe03b342f9940cc92166b755f2afa4/src/main/java/com/github/theholywaffle/teamspeak3/api/event/BaseEvent.java#L94-L114) of that getter.

There can also be a ban message, which you can access with the `getReasonMessage` getter.

If a client was kicked or banned, there *should* also be an invoker - a client that caused the event. You can get more information about that client by using the `getInvokerId`, `getInvokerUniqueId`, and `getInvokerName` getters.

Please let me know if this answered your question 😄

**Comment by iProGamer** [comment]
WOW! Thanks for the fast reply
What about offline bans?

**Comment by rogermb** [comment]
There's no event for those. You'll have to check the server's ban list (`TS3Api#getBans`) ever so often.

**Comment by iProGamer** [comment]
Thanks for the help <3
