### ISSUE TITLE
Do I need the Query

### ISSUE THREAD

**Issue by simpleC0de** [TheHolyWaffle/TeamSpeak-3-Java-API#217]
Hey there, I'm just trying to make a bot for common use - chat only mostly.
I don't need the Query for that, do I need it for the API though?
Well, basically I don't want to ask everybody to enter their queries.

Hopefully, it is working without :)!

**Comment by rogermb** [comment]
Yes, you do need a logged-in server query to send chat messages via the server query interface.
Take a look at the examples for how to connect to a TS3 server via this interface and take a look at the FAQ for [how to create a server query login](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#how-do-i-create-a-server-query-login) (in case you don't want to use the `serveradmin` account).

I am not sure what you mean by
> Well, basically I don't want to ask everybody to enter their queries.

Could you elaborate further on this?

**Comment by simpleC0de** [comment]
Well, I just want them to enter an IP into a File and then the bot connects and works. No need for a login, basically just a normal client. They would need to make an extra group or something for it maybe, but I do not want them to enter the Query.

**Comment by rogermb** [comment]
There's no way to make that work. I mean, consider the implications if this worked. People could deploy hundreds of instances of this across multiple machines and completely flood any TeamSpeak server with text messages.

If your users need to take the time to enter an IP into a configuration file, you can just as well make them take the time to create a Server Query login and enter that into the configuration file, too.

**Comment by simpleC0de** [comment]
Well, that's not the problem. But some guys think that that's not safe.

**Comment by rogermb** [comment]
If people can access arbitrary files on their machines, that's their problem, not yours.
Might still be a good idea not to use the `serveradmin` account then, if these people are so concerned about security.

And the telnet interface server queries uses to communicate with the TeamSpeak server is extremely insecure anyways, so queries should only be run on the same machine the TeamSpeak server runs on.

**Comment by simpleC0de** [comment]
Well, I mean there must be a way to make this work. A bot called "SinusBot" (might be a name for you) works without query as well.

**Comment by somefriggnidiot** [comment]
From my understanding, SinusBot is a program that utilizes the TeamSpeak's
actual client application rather than the query interface. That is why it
can send audio to the server and why it appears to be virtually present as
a user.

**Comment by simpleC0de** [comment]
Well, it's running on Linux. Probably not Java though.. I don't know.
Well, I just want to chat with that bot, there must be anything without query.

**Comment by rogermb** [comment]
So if I read that correctly, you open an issue on an API for the server query interface, asking if there's a way *not* to use our API? ...

You could implement your own TeamSpeak3 client, that's about the only option you have left.
There's no public documentation for the protocol the TS3 client and server use to communicate with each other, though, so that might prove to be a little tricky to implement.

**Comment by simpleC0de** [comment]
Well, I hoped there's an option here. Searched a while, haven't found a thing, asked, still not a thing.
But thanks for your great help :). Will keep searching!

**Comment by rogermb** [comment]
... or you could just convince your users to provide a server query login. It's really not that hard.
Tons of bots use the server query interface everyday without problems.
