### ISSUE TITLE
Cancel an Event

### ISSUE THREAD

**Issue by M4exy** [TheHolyWaffle/TeamSpeak-3-Java-API#220]
Hi!

Is there a way to cancel a fired event? 
For example I want to be able to write commands in the textchat but the actual written command should not appear in the textline when the message is sent.
Or I want some specific Clients force to stay in one channel. So I want to cancel the onClientMoved Event.

Is there a way to cancel these events?

Regards

**Comment by Frigerius** [comment]
No, otherwise TeamSpeak would have to wait for ur Bots response. Why u don't message the bot directly, so u don't need to stay in one channel and no one else can read the message. and the stay in channel thing, discard move rights or just move the client back.

**Comment by M4exy** [comment]
Thanks a lot!
