### ISSUE TITLE
Add event onClientRename

### ISSUE THREAD

**Issue by Tristiisch74** [TheHolyWaffle/TeamSpeak-3-Java-API#222]
Hi,

Can you add a event when the client want to rename itself ?
I want to prohibit this.

**Comment by rogermb** [comment]
Exactly. As such, we can't add any events that don't already exist in the interface.

You'd have to get the TeamSpeak developers to create that new event, so you'd need to request this specifically from them. I know that you're not the first person to ask for this, though, so it's likely that it was already decided not to add any more events.
