### ISSUE TITLE
How can i set a ClientIcon?

### ISSUE THREAD

**Issue by Ventix** [TheHolyWaffle/TeamSpeak-3-Java-API#224]
Hello? There is no method, to set a client icon?

**Comment by rogermb** [comment]
Answered in [#138](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/138#issuecomment-257111457).

**Comment by rogermb** [comment]
Response to the comment in #138:

Check out [TS3Api#uploadIcon(InputStream, long)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4600-L4639) or [TS3Api#uploadIconDirect(byte[])](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4641-L4668) :smile:

As far as I know, PNG is a / the correct format for icons already, so you won't have to convert any data. You'll just need to either open a `FileInputStream` for `uploadIcon` or read the whole file as a byte array for `uploadIconDirect`, e.g. by calling [java.nio.file.Files.readAllBytes(Path)](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAllBytes(java.nio.file.Path)). The second method is probably a bit easier to use.

Both of these methods will return the ID of the uploaded icon, which you can then use in `TS3Api#addClientPermission` (you might have to cast the IDs to `int`)
