### ISSUE TITLE
get time Client is connected

### ISSUE THREAD

**Issue by repte** [TheHolyWaffle/TeamSpeak-3-Java-API#225]
Using your wrapper I asked myself how to get the time a Client is connected to a server?
I only found getLastConnectedDate()

for (int i = 0; i < clients.size(); i++) {
			 System.out.println(clients.get(i).getLastConnectedDate());
}

**Comment by rogermb** [comment]
I'm not sure I understand what the problem is. `getLastConnectedDate` does include the time the client last connected, with a resolution of 1 second.

And at least on my machine, this method works for all clients except for the `serveradmin` account.

**Comment by repte** [comment]
I had a mistake in my thinking process - you are right. Thanks
