### ISSUE TITLE
 How can i remove the permission value??

### ISSUE THREAD

**Issue by Ventix** [TheHolyWaffle/TeamSpeak-3-Java-API#231]
How can i remove the permission value of i_icon_id?
```
               */CENSORED*/  
               
		api.deleteIcon(v);
		v = api.uploadIconDirect(output.toByteArray());
		api.addClientPermission(client.getDatabaseId(), "i_icon_id", 0, true);`
		api.addClientPermission(client.getDatabaseId(), "i_icon_id", (int) v, true);`
```

The Problem is: if i set the client icon its works. but if i change with a another identity its doesnt works.

**Comment by rogermb** [comment]
I think the method you're looking for is [`TS3Api#removeClientPermission(int, String)`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L980-L997). The method is named after the TS3 command called `clientdelperm`.

In your case, you'd probably want to call `api.removeClientPermission(client.getDatabaseId(), "i_icon_id");`. :smile:
