### ISSUE TITLE
Add support for Java 8

### ISSUE THREAD

**Issue by wrycu** [TheHolyWaffle/TeamSpeak-3-Java-API#234]
Java 7 was End of Life'd in April of 2015 and is no longer supported.  Please add support for a supported version of Java.

https://www.java.com/en/download/faq/java_7.xml

**Comment by rogermb** [comment]
Hi!

Thanks to Java's excellent forward compatibility, you should be able to use this library with both Java 8 and Java 9. You can even use lambdas where applicable.

Are there any specific compatibility issues you're experiencing?

**Comment by Kakifrucht** [comment]
Using this with Java 8 works without issues on my end.

**Comment by wrycu** [comment]
Embarassing! I wrote up this issue before testing with Java 8.  I can confirm that I've used the library with Java 8 without issue.

Perhaps just add a blurb that notes that it does/should work with future versions as well?

In any case, sorry for the trouble and thanks for the clear explanation as to why I'm wrong :)

**Comment by Henny022** [comment]
You dont need a note for that because its a basic java principle, that
everything from older versions works in newer ones

**Comment by TheHolyWaffle** [comment]
I agree with Henny, that is why I'm closing this issue.
