### ISSUE TITLE
Changing the Nickname of a Client

### ISSUE THREAD

**Issue by nimataeb** [TheHolyWaffle/TeamSpeak-3-Java-API#235]
Hi 
guys im totally new to both Java and this API, and my english sucks a little :P.
I have a bot that moves the afk people to a channel that i made for them. now i want it to automaticly move the afk people to the channel that they were speaking before they went afk. so to do that, I wanted to store the channel id in their nickname. Problem is, idk how to change their nickname using this api. My question is, how can I do this? Im also open to any suggestions about the whole channel id storing thing. Thx :*

**Comment by Frigerius** [comment]
Hey man, I use a HashMap with my custom Client class to store who is afk and where he was before. Just take a look at my code, if u want [https://github.com/Frigerius/Gw2FrostBot/blob/master/src/main/java/de/frigerius/frostbot/AfkMover.java](url)

**Comment by nimataeb** [comment]
@Frigerius hey man, sry to say this but the link doesn't work, idk why. and btw idk what a HashMap is cuz im totally new to programming and Java xD. but thx for the comment

**Comment by Frigerius** [comment]
@nimataeb Ahh I'm sorry, failed using Markdown xD Hm maybe you should then first lern some Java before? HashMap in simple: You store pairs of keys and values. Example: ClientID and ClientName. The key would be ID and value the name. After storing those in the map you can ask the map for getting the ClientName for a specific ID.

**Comment by rogermb** [comment]
Hi!

First of all, it's not possible to change another client's nickname through the server query API.

As @Frigerius mentioned, you'll want to look into using some kind of data structure, like a `HashMap`.
There are certainly dozens of tutorials out there that'll introduce you to these data structures. Data structures in general are extremely important to programming, so I'd really recommend you to teach yourself about them :smile:

**Comment by nimataeb** [comment]
@Frigerius @rogermb thx for the info guys, it meant a lot :*
