### ISSUE TITLE
Set a ClientIcon

### ISSUE THREAD

**Issue by DKPlugin** [TheHolyWaffle/TeamSpeak-3-Java-API#243]
I want to set a ClientIcon.
My code:

.editClient(client.getId(), mapOf(ClientProperty.CLIENT_ICON_ID, iconid));

private static Map<ClientProperty, String> mapOf(ClientProperty property, Object value){
      return Collections.singletonMap(property, String.valueOf(value));
}
It doesn't works.

**Comment by rogermb** [comment]
Hi! I can't really tell what's wrong with that little information.
Could you please include the relevant section of the communications log? Moreover, what do you mean by "it doesn't work"? Does the server respond with an error (and a TS3CommandFailedException is thrown), or does it just not change the client's icon?

**Comment by rogermb** [comment]
Closed - no response with more information for 30 days.
