### ISSUE TITLE
Setting a client's icon

### ISSUE THREAD

**Issue by xFirestorm** [TheHolyWaffle/TeamSpeak-3-Java-API#249]
I'm trying to use the addClientPermission method to set a user's client icon. Since the method takes an integer as value argument i'm not able to use it because teamspeak icon ids have a size of 10.

So how am i able to set them?

**Comment by rogermb** [comment]
All client icons are 32-bit integers - they're the result of applying a CRC32 hash to the bytes that make up the icon. However, TeamSpeak sometimes treats those as unsigned and sometimes as signed integers: it displays the icon IDs as unsigned integers, but the permissions system uses signed integers.

If you're just trying to use a constant value, you could get the signed integer value by casting a long constant to an integer, e.g.

```java
int iconId = (int) 3793896448L;
```

**Comment by xFirestorm** [comment]
Oh i see. That seems to be working. Thank you very much ^^

**Comment by rogermb** [comment]
You're welcome! I'm glad I was able to help 😄
