### ISSUE TITLE
addClientPermission is returning false

### ISSUE THREAD

**Issue by xFirestorm** [TheHolyWaffle/TeamSpeak-3-Java-API#250]
Hey guys,
I'm trying to set client icons with the addClientPermission method.

api.addClientPermission(pair.databaseId, "i_client_id", icons.get(newLevel), false);
where icons.get(newLevel) is for Example (int) 4216653173L

Why is the method returning false and there is no icon set?

**Comment by rogermb** [comment]
There should be an entry in the console starting with "TS3 command error:" that tells you what went wrong.

It may also help to turn on all logging, since that'll let you see what commands are being sent and what the responses to those commands are.

**Comment by xFirestorm** [comment]
Well there was no entry. I just printed out what the method was returning since it returns a bool. So i thought that false meanse something like it didn't work. But i'll try turning on all logging and see what the problem is

**Comment by xFirestorm** [comment]
Well log functions are already implemented and i'm not getting any output from the method call. Is there any function you have to activate it with in the api? It's kinda late but i'm really trying to get this working before going to bed so if you know the answer i would be very happy .

**Comment by rogermb** [comment]
There's `TS3Config#setEnableCommunicationsLogging` to turn on logging of everything transmitted between the client and the server.

**Comment by xFirestorm** [comment]
Well that method is not there somehow although i'm running the newest version

**Comment by rogermb** [comment]
Ah, right, my bad. In 1.0.14 it's still `setDebugLevel(Level)`. If you set that to `Level.ALL`, everything the API will log should show up.

**Comment by xFirestorm** [comment]
Okay got it fixued with the Level.ALL output. There was just something wrong with the permission name. Thank you very much :)

**Comment by rogermb** [comment]
Oh man, I should've seen that! Anyway, glad to hear everything's working again :smile:
