### ISSUE TITLE
New Events

### ISSUE THREAD

**Issue by Ausgeben** [TheHolyWaffle/TeamSpeak-3-Java-API#253]
Hello, can you pls add These Events:

-> OnGetServerGroup
- when a Client get an Group then ...

-> AllAround
- All the time do ...

**Comment by Kakifrucht** [comment]
The server query interface does not notify us if these events occur, so no, they can't be added.

**Comment by rogermb** [comment]
@Ausgeben, we don't control the TS3 Server Query interface. This is just a Java wrapper around that interface. If you want to have new events added, you'll have to ask the TeamSpeak development team for those.
