### ISSUE TITLE
Question: Offline client description

### ISSUE THREAD

**Issue by glains** [TheHolyWaffle/TeamSpeak-3-Java-API#254]
Is there any possible way to fetch the description of a client, altough he is not connected to the server? Client and subclasses need the client to be online and DatabaseClient provides some other form of description, which did not match the one i was looking for.

I am aware that this is a server query related question (probably not related to this api), but the manuals didnt help me out. If this is not possible, i have already considered caching the clients.

I hope you can help me out, thanks a lot in advance!

**Comment by Kakifrucht** [comment]
The field ``client_description`` for an ``DatabaseClientInfo`` object reveals the correct description on my end, ``DatabaseClient::getDescription`` should return that information.

**Comment by glains** [comment]
Then, for some reason, the description i got did not match what i excpected. I will report this evening and close this issue. Thanks for your help!
