### ISSUE TITLE
Async "getClientsByName(String)" throwing error on no results.

### ISSUE THREAD

**Issue by somefriggnidiot** [TheHolyWaffle/TeamSpeak-3-Java-API#258]
# When is this happening? / How can it be recreated?
When attempting to query a list of users by name, but no matching users are found.

# What is happening?
`apiAsync.getClientsByName(queryString)` is resulting in a CommandFailedException when no users match the query.
> [2018-03-26 21:31:36.224] > clientfind pattern=nobody
> [2018-03-26 21:31:36.224] [clientfind] < error id=512 msg=invalid\sclientID
> [2018-03-26 21:31:36.224] [SEVERE] TS3 command error: {msg=invalid clientID, id=512}

When users do match the query, for comparison:
> [2018-03-26 21:32:52.329] > clientfind pattern=idiot
> [2018-03-26 21:32:52.329] [clientfind] < clid=4 client_nickname=somefriggnidiot
> [2018-03-26 21:32:52.330] [clientfind] < error id=0 msg=ok

# What's expected to be happening?
Command should return an empty list if no online users match the query.

**Comment by Kakifrucht** [comment]
Yeah, once again stupid behaviour by the query interface we are wrapping. Might have to handle this case seperately.
