### ISSUE TITLE
Create Channel with join Power rights ?

### ISSUE THREAD

**Issue by Finnlife** [TheHolyWaffle/TeamSpeak-3-Java-API#259]
How can i create Channel with Needed join Power etc. ?

In the ChannelProperty is no entry like this.

How i do it ?

**Comment by rogermb** [comment]
Hi!

The join power is actually implemented as channel permission called `i_channel_needed_join_power` that you need to set by using `TS3Api#addChannelPermission`. I've gone into a bit more detail in #109 and #189 :smile:
