### ISSUE TITLE
Viewing bot

### ISSUE THREAD

**Issue by jameserose** [TheHolyWaffle/TeamSpeak-3-Java-API#26]
Is there any way to view the bot in teamspeak like a real user?
If someone needs to message the bot then I can't think how they could do it easily.

**Comment by Mikeichhalt** [comment]
it is possible:
set i_client_serverquery_view_power in your server group and
make the check mark in the server favorite at "server query clients anzeigen"
in english: "show server query clients" or something like that

sorry for my bad english :D
![28-01-_2015_21-00-14](https://cloud.githubusercontent.com/assets/6721776/5945718/d051df54-a730-11e4-8aa2-ab22ad72dbaa.png)

**Comment by jamesterjim** [comment]
It works! thank you very much.
