### ISSUE TITLE
invalid clientID with ID=512

### ISSUE THREAD

**Issue by Kavatch** [TheHolyWaffle/TeamSpeak-3-Java-API#260]
Hey,
I have my own little TeamSpeak bot using this API here, it works really well but I, constandly get this error:
`[SEVERE] TS3 command error: {msg=invalid clientID, id=512}`
And it looks something like this in the Logs: 
https://paste.grv.sh/read/Mm2p8
What could cause this issue? Is it something I have done wrong or is its just normal? And how can I remove it?

**Comment by somefriggnidiot** [comment]
Can you recreate this with a more sensitive TS3 logging level? It'd help to see what you're sending before getting that.

**Comment by rogermb** [comment]
And since we've just had a very similar issue, please make sure you're not creating duplicate TS3Query instances that you aren't actually using.

**Comment by Kavatch** [comment]
@somefriggnidiot Im sorry to ask, but how do activate a more senstiive TS3 logging level?
@rogermb what do you mean by creating duplicate TS3Query? Do you mean that I should not call query.connect(); multiple times? If that's what it means, no, I'm not.
Just to be sure here is the code in my main methode: https://paste.grv.sh/read/pGl5H

**Comment by somefriggnidiot** [comment]
`TS3Config#setDebugLevel(Level.ALL);`

**Comment by rogermb** [comment]
> Im sorry to ask, but how do activate a more senstive TS3 logging level?

Sorry, we should've went into more detail :smile:

To log the commands sent to and the responses received from the TS3 server, you'll need to call `config.setDebugLevel(Level.ALL)` before passing the config object to the TS3Query constructor.

Speaking of which: You really shouldn't modify a TS3Config object after having passed it to the constructor of TS3Query (like you're doing in line 2 of your paste).

> Do you mean that I should not call query.connect(); multiple times? If that's what it means, no, I'm not.

Alright, then we can at least exclude that possibility.

From looking at the timestamps of those errors, there are intervals of less than a minute in there, so it's definitely not the keep alive that's doing that. They also don't occur in fixed 30 second increments, so your "myTask" timer task is off of the hook.

If I had to guess, it's most likely one of your event handlers.

And if I had to guess even further, could it be that you're using an "invoker" ID when you meant to use a "client ID"? :smile:

The difference between the two is explained [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#what-is-the-difference-between-an-events-client-and-invoker).

**Comment by Kavatch** [comment]
config.setDebugLevel(Level.ALL) is not valid? https://4lex.de/pics/files/idea64_2018-03-27_23-15-52.png

In many cases I used the invoker ID but only at the TextMessageEvent event. Otherwise I only use the Client ID as in the ClientMovedEvent.

**Comment by Kavatch** [comment]
Strangely enough, it doesn't work either? https://4lex.de/pics/files/idea64_2018-03-27_23-37-49.png
My IDE only shows me the error when compiling and not before.

**Comment by rogermb** [comment]
Hmm, not really sure about that one. What version of the API are you using, exactly?

Maybe re-downloading the API and re-compiling everything could work.

**Comment by Kavatch** [comment]
Version: 1.0.14
And re-downloading could be difficult because I use it with maven. 
But I have used everything that does something similar with maven.

**Comment by rogermb** [comment]
So if you're using maven, you're guaranteed to actually have v1.0.14, so you should have [this version](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/3323092d315415e8e21a5d94621b10d6370101a4/src/main/java/com/github/theholywaffle/teamspeak3/TS3Config.java#L77-L81) of TS3Config that still includes `setDebugLevel(Level)`.

Maybe it's downloading the sources from somewhere else and that's why your IDE tells you that `setDebugLevel` isn't valid? I'll go check whether our binaries are all correct.

**Comment by Kavatch** [comment]
um yes you're right, the method is also shown in the source of maven: https://4lex.de/pics/files/idea64_2018-03-28_00-05-40.png

**Comment by rogermb** [comment]
There should be a button in the maven panel labelled "Update project" or similar that might work.

Or maybe we should just skip the log files seeing how your IDE isn't cooperating and just try to find the bug by looking at the source code of the event listeners?

**Comment by Kavatch** [comment]
> There should be a button in the maven panel labelled "Update project" or similar that might work.
I have actually already used but unfortunately not changed anything.
Okay, here's the whole class. I removed some things like passwords, names etc. but that shouldn't change much. https://paste.grv.sh/read/OxnLG

**Comment by somefriggnidiot** [comment]
Have you traced through this / can you tell us the line where this is happening? Debug mode should be helpful.

**Comment by Kavatch** [comment]
To yes I tried to debug and find out but could not find a pattern. Therefore I do not know in which line the error could occur.

**Comment by rogermb** [comment]
So it's hard to say for sure without the logs, but I think there's a fair chance your problems originate from the timer task you're spawning in your onClientMoved listener at lines 405-413.

You're only running that task after 60 seconds. By that time, there's a fair chance that the client with that ID has already left the server. If you then call `TS3Api#kickClientFromChannel` with the ID of a client who's no longer online, you'd get exactly such a "invalid clientID" error.

To get around this, you could test whether the client is still on the server by calling `TS3Api#getClientInfo`. That method will return null if the client is no longer online.

**Comment by Kavatch** [comment]
The funny thing is that it is always the same client id and it occurs at times when no player leaves the server.
//EDIT: wth? I just tried a little more with the log and now it works? I'll send you the logs as soon as I can. (And I have no idea what I did that it debugs now after all)

**Comment by rogermb** [comment]
> The funny thing is that it is always the same client id

That's the numerical ID of the "invalid clientID" error, not the invalid client ID :blush:

> I just tried a little more with the log and now it works? I'll send you the logs as soon as I can.

Very nice! Thank you very much!

**Comment by Kavatch** [comment]
Okay here is the debug Log: https://paste.grv.sh/read/suAQK
Error in line: 46

**Comment by rogermb** [comment]
Which technically shouldn't be a problem, the function just returns null as specified - but it still logs a warning to standard out, which is the main issue here. @Kavatch, you could always just turn off all logging to get rid of those messages by using `setDebugLevel(Level.OFF)`, but I feel like that kinda defeats the purpose of having error logging in the first place :smile:

Not sure if that behavior still exists in 1.1-dev, though.

**Comment by Kavatch** [comment]
Okay then I thank you ^^ I'll take a look at it and if there's anything new I'll get back to you :D
