### ISSUE TITLE
Server group event

### ISSUE THREAD

**Issue by InZaneDanii** [TheHolyWaffle/TeamSpeak-3-Java-API#261]
is there an event if a users server group got added / removed? e.g I remove someone from group "admin" and they server should trigger it and do something I want eg send a message

**Comment by rogermb** [comment]
No, there's no way for us to do that.

This project is just a Java wrapper around the Server Query interface provided by TeamSpeak. And as we don't control the Server Query interface, we can't make changes to it (like adding events).

A polling loop, while not the prettiest implementation, is probably the only way to currently detect such changes on a TS3 server.

Duplicate of #255, #253, #245, #222, #220, #190, #181, and so on.

**Comment by InZaneDanii** [comment]
oh ok, thanks for the answer! 

i've got another question: 
it is possible to get someones ping? Dont think so because of the say reason, right?

**Comment by rogermb** [comment]
Yeah, I don't think we have access to that value. There are a bunch of connection metrics (like the amount of data sent and received) in ClientInfo, but the client's ping unfortunately isn't one of them 😞

**Comment by InZaneDanii** [comment]
Thats a same :/ but thank you very much for you awesome api! :)
