### ISSUE TITLE
Uploaded Icon Error

### ISSUE THREAD

**Issue by Maxdola** [TheHolyWaffle/TeamSpeak-3-Java-API#262]
Hi, I tried to upload an Icon for an user but some code does not get triggered when the Icon upload Succeeds.

`                                                URL url = null;
                                                long iconId = -1;
                                                String surl = "https://minotar.net/helm/" + vc.getCorePlayer().getUsername().toLowerCase() + "/16.png";
                                                TeamspeakDiscord.log("§aHi");
                                                try {
                                                    url = new URL(surl);
                                                    InputStream in = new BufferedInputStream(url.openStream());
                                                    ByteArrayOutputStream out = new ByteArrayOutputStream();
                                                    byte[] buf = new byte[1024];
                                                    int n = 0;
                                                    while (-1 != (n = in.read(buf))) {
                                                        out.write(buf, 0, n);
                                                    }
                                                    out.close();
                                                    in.close();
                                                    byte[] response = out.toByteArray();

                                                    iconId = tsapi.uploadIconDirect(response);
                                                } catch (IOException e1) {
                                                    e1.printStackTrace();
                                                    TeamspeakDiscord.log("§eError");
                                                }
                                                int intId = Math.toIntExact(iconId);
                                                tsapi.addClientPermission(c.getClientInfo().getDatabaseId(),"i_icon_id", intId,false);
                                                TeamspeakDiscord.log(surl);
                                                TeamspeakDiscord.log(iconId);
                                                TeamspeakDiscord.log(intId);
                                                TeamspeakDiscord.log("§cBaum");`
if the upload works the Code after the try/catch does not get triggerd.

**Comment by rogermb** [comment]
I can assure you that this API neither calls `System.exit` in that call to `tsapi.uploadIconDirect`, nor does it violate the specifications of the Java Virtual Machine.

What I'm trying to say is: it's quite likely that there is an exception *somewhere* in your code that you're not catching and that is being swallowed. I'd suggest also adding a catch clause for a `TS3Exception` to your try block.

Moreover... why are you going through the trouble to manually read out the input stream into a byte array when you could just pass your `InputStream in` to `TS3Api#uploadIcon`?

**Comment by Maxdola** [comment]
Thanks I found the Issue Math#toIntExact was causing the Issue but thanks anyways.

**Comment by Maxdola** [comment]
But another Question is there a way to get the icon ID if it is already uploaded ?

**Comment by rogermb** [comment]
Calculate the CRC32 hash of the icon's bytes. That *should be* your icon ID.

```java
final CRC32 crc32 = new CRC32();
crc32.update(iconData);
int iconId = crc32.getValue();
```
