### ISSUE TITLE
How to unban the Uid, not only the ip?

### ISSUE THREAD

**Issue by Bxnnet** [TheHolyWaffle/TeamSpeak-3-Java-API#264]
Hey,

I want to unban a client and therefor I go through all bans so I can delete the Ban the ban using a banId, but I have the problem that it only unbans the IP and not the Uid, the user still can't join. How can I also delete the Uid from a ban?

Greeetings 
Bennet

**Comment by rogermb** [comment]
Hi! Sorry for taking so long to get back to you, I had quite a busy weekend 😅 

And yeah, this is just some strange design decision on behalf of the TeamSpeak developers: Whenever you ban a client, the server actually creates two entries in the ban list: one for the IP, another one for the UId. 

So if you want to unban a client as a server query, you'll need to delete both ban list entries by calling `TS3Api#deleteBan(int)` on each of them. As you discovered, removing just one doesn't do the trick 😊

There is no obvious link between two of these ban entries. However, they both seem to share the same date (`Ban#getCreatedDate`), duration (`Ban#getDuration`), reason message (`Ban#getReason`), and creator / invoker (`Ban#getInvokerName`, `Ban#getInvokerClientDBId`, `Ban#getInvokerUId`). So if you only know the IP or the UId, you could get a list of all bans by calling `TS3Api#getBans` and use these properties to find the other matching ban.
