### ISSUE TITLE
Problem at Uploading an Icon

### ISSUE THREAD

**Issue by Jopeeee** [TheHolyWaffle/TeamSpeak-3-Java-API#266]
Hey guys,
I am just trying to download an picture by an Website and upload it as an Icon but it won't work. I've already seen the other Articles here but they didn't helped me.
Can you maybe help me?

(Sorry for my bad English)

**Comment by Henny022** [comment]
please provide a sample of your code, where you are trying this, so we can help you to spot the problem.
remember to remove you ip and login information

**Comment by Jopeeee** [comment]
`URL url = new URL("https://minotar.net/avatar/" + p.getName() + "/16.png");
        InputStream in = new BufferedInputStream(url.openStream());
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        int n = 0;
        while (-1 != (n = in.read(buf))) {
            out.write(buf, 0, n);
        }
        out.close();
        in.close();
        byte[] response = out.toByteArray();
        Main.api.uploadIcon(in, getInstance().getIconId(response));`

` public long getIconId(byte[] data) {
        final CRC32 crc32 = new CRC32();
        crc32.update(data);
        return crc32.getValue();
    }`

**Comment by Henny022** [comment]
the uploadIcon method takes the lenght of the data as a second argument, and returns the id

**Comment by Henny022** [comment]
you are using the method wrong, you need to get the length of the buffer and use that the second argument, not the the value returned by your getIconId method

**Comment by Jopeeee** [comment]
how can i get the buffer length?

**Comment by Henny022** [comment]
there is no direct way to get it from the input buffer, and i do not know a good, reliable way of doing so.
im would wait for someone who did more with this api than me to come and answer how to do this properly.
you can also go to the gitter chat of this api (linked in the readme) and ask there, that is a better place for questions and also usually gets faster responses

**Comment by Jopeeee** [comment]
okay, thank you

**Comment by rogermb** [comment]
You're already downloading the whole file manually and storing its data in a byte array, so you should just use `TS3Api#uploadIconDirect(byte[])`. That method takes a byte array, uploads it as an icon and returns the ID of the created icon.

If you wanted to keep using the `TS3Api#uploadIcon`, you could remove all your manual download code, but you'd need a way to figure out the size of the file you're downloading. I don't think there's an easy way to do this using the old Java IO library, so I think the best option is to just switch to using `TS3Api#uploadIconDirect(byte[])`.

**Comment by Jopeeee** [comment]
I already tried this, but in the Log is that the Uploading failed.

**Comment by rogermb** [comment]
Huh, interesting! Could you send us the relevant part of that log file?
And while we're at it, may I ask which version of the API you're using?

**Comment by Jopeeee** [comment]
`[WARNING] [Upload 1] Upload failed: Connection refused (Connection refused)`

I use Version 1.0.14

**Comment by rogermb** [comment]
"Connection refused" - are you sure that you can actually reach the file transfer port of your TS3 server? Maybe the server is behind a router with NAT and the file transfer port isn't forwarded.

**Comment by rogermb** [comment]
Hmm, I guess the simplest way to check would be to launch a TS3 client from the machine your query application is running on and to try uploading an icon with it.

**Comment by Jopeeee** [comment]
I just checked Yatqa and at Icons is an Blank icon with a size of 0 bytes. And if i click on it it says "DL-Fehler".

**Comment by rogermb** [comment]
This also indicates that there is a problem with your file transfer port.

I can't really comment on how to fix this - this depends a lot on what kind of network your TS3 server is running in. If you're hosting your own TS3 server in your own network, you'll probably have to check if you're also forwarding the file transfer port (30033, TCP by default). If you're using some third party TS3 service, you'll most likely have to contact their support team or change some kind of setting in your management interface.

**Comment by Jopeeee** [comment]
I just use an Root Server from an Hoster where i installed my Teamspeak-Server.

**Comment by rogermb** [comment]
Hmm, that's tricky. It could well be that a misconfigured firewall is blocking all traffic on port 30033. But since fixing this could be quite tricky, let's first explore some other possible causes.

Could you please turn on communications logging by setting the debug level in TS3Config to ALL and then send me the last few lines (5-10) of your debug log just prior to getting "Upload failed: Connection refused"? Let's see if the TS3 server correctly responds to the command asking to initiate a file transfer.

**Comment by Jopeeee** [comment]
I already have it at ALL. In the Log from the Teamspeak is: "2018-05-30 19:20:12.413021|INFO    |VirtualServerBase|2  |file upload to (id:0), '/icon_1310189290' by client 'Klerix | ServerBot'(id:790)" but this is all.

**Comment by rogermb** [comment]
Sorry, I should have made myself clearer. I didn't mean the entry in TeamSpeak's own log, but rather the logging output of your query application. I'm mostly interested in what ftinitupload command the query sends to the server and what the server's response to that command is.

**Comment by Jopeeee** [comment]
Where can I see this log?

**Comment by rogermb** [comment]
Unless you redirected System.out, you should see that output in the console / terminal window.

**Comment by Jopeeee** [comment]
There's nothing in the Log. Maybe its important to know. I start the Bot via an Minecraft Bungeecord Server. (As an Plugin) Maybe this is the Problem.

**Comment by rogermb** [comment]
As a quick workaround, you could try calling `ts3Config.setDebugToFile(true)`. That should also write all log messages to a file called "teamspeak.log".

In the future, it might be a good idea to upgrade to version 1.1.0 of this API. It has both improved logging support and handles some icon upload edge cases a bit better (those are not the cause of your issues, though).

**Comment by Jopeeee** [comment]
I tried it, but no log file was created.

**Comment by rogermb** [comment]
Make sure that you're calling `ts3Config.setDebugToFile(true)` before passing the TS3Config object to TS3Query's constructor. If that doesn't help, might be a good idea to upgrade version 1.1.0 of the API - I really don't want to diagnose logging issues with old versions of the API :smile:

**Comment by Jopeeee** [comment]
Can i just change the version of the API or can this cause Problems at other functions in the Bot which already are finished

**Comment by rogermb** [comment]
I mean, I really can't give you any guarantees. All the logging stuff and TS3Config have changed, so you'll certainly need to edit a few lines of code. But I'm confident that most of your code should continue to work.

But please just keep in mind what the actual issue we're trying to tackle here is: the file transfer port isn't reachable. There are certainly also other ways of checking your TS3 server config and the traffic on port 30033 if updating to the newer API version and then checking the log take too much time.

**Comment by rogermb** [comment]
Closed due to inactivity.
