### ISSUE TITLE
Audio recording 

### ISSUE THREAD

**Issue by korteksz** [TheHolyWaffle/TeamSpeak-3-Java-API#271]
Hello there!

I'm totally new in the world of TS3 API and I'm just curious if I were able to the following scenario with this API:
- Login to a server as client
- Switch to the channel which I need
- Record the discussion in the room (for a while, eg. for 1 hour) 
- Save the recorded audio and log off the server

I was looking for the audio recording in the documentation but I haven't found anything about it

Thanks for your answer :)

**Comment by rogermb** [comment]
Hi! Unfortunately, the server query API is a text-only interface. There's no way to transmit audio data, so there's also no way to record audio. As far as I'm aware, there isn't even a way to do this with the client query interface.

If you really need to record audio like that, you'll probably have to write some kind of client or server plugin in C++.

Finally, please be aware that - depending on jurisdiction - your clients may have to give consent to being recorded for this to be legal.
