### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by lewysDavies** [TheHolyWaffle/TeamSpeak-3-Java-API#28]
I am getting this error 05.01 14:51:06 [Server] WARN [SEVERE] [ERROR] {id=1024, msg=invalid serverID} and I can't work out why. 

My code:
http://pastebin.com/4CmqXjWK

(I'm making a minecraft bukkit plugin with teamspeak so users can talk to each other in a certain radius.) This is just a test. Everything it's getting from the config is all correct. Do you know how to fix this?

**Comment by TheHolyWaffle** [comment]
You're using the wrong server id to connect to. Try using
selectVirtualServerByPort
and use it with the port you'd normally use to connect to the server.

2015-01-05 22:59 GMT+01:00 lewysDavies <notifications@github.com>:

**Comment by lewysDavies** [comment]
I'll give it a try soon, I'm sure it will work :) also I know why the other guy failed with bukkit :P

**Comment by lewysDavies** [comment]
AMAZING! Works like a charm <3
