### ISSUE TITLE
TeamSpeak Server Version

### ISSUE THREAD

**Issue by Likqez** [TheHolyWaffle/TeamSpeak-3-Java-API#280]
I coded a Verify System with this API and as i updated the Teamspeak³Server to the Veriosn : 3.2.0 on Linux the Code didn't do what he should. The Querry Connected but did not gave Ranks... 

Can The Ts³ API run on a 3.2.0 Server from Ts³?

**Comment by rogermb** [comment]
Hi! Sorry about the late response, I completely missed your message 😞 

Yes, this API should work fine on 3.2.0 servers, and we haven't heard about any issues.

Can you go into detail what problems you're encountering?
A code snippet and the communications log (enable by calling `setEnableCommunicationsLogging(true)` on your `TS3Config` object) should let us help you figure out what's causing these issues :smiley:

**Comment by Likqez** [comment]
No Problem for your late response. I fixed the issue and probably forgot that I asked here on GitHub. I don't know why it wasn't working but now it works.

Thank You.

**Comment by rogermb** [comment]
Phew! Good to hear that it's working now 😄 

Please don't hesitate to contact us again if you're having any other issues. I promise it won't take me that long to get back to you again 😅
