### ISSUE TITLE
Secretly editing channel description

### ISSUE THREAD

**Issue by GeRaged** [TheHolyWaffle/TeamSpeak-3-Java-API#283]
Is it possible to editing secretly channel descriptions?

**Comment by GeRaged** [comment]
@rogermb i want to edit the channel but hide it in the server log

**Comment by rogermb** [comment]
You can't hide things from the server log by using the server query. You might be able to edit the server's logging settings if you're the administrator, but I'm not even sure whether such a setting exists.
