### ISSUE TITLE
Get client size in channel

### ISSUE THREAD

**Issue by GeRaged** [TheHolyWaffle/TeamSpeak-3-Java-API#284]
The question is how can I get the current client size in a specified channel

This thread don't help me. https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/143

**Comment by rogermb** [comment]
Yeah, that's one of many shortcomings in the Server Query interface. The `channelinfo` command doesn't tell you how many clients there are in a channel. The only way to get that number is to ask for more information than you actually need:

- If you're just interested in the amount of clients in one specific channel, you could get a list of all clients using `TS3Api#getClients` and count all clients c whose `c.getClientId() == yourChannelId`.
- But perhaps it's a better idea to get a list of all channels using `TS3Api#getChannels`. The channel information the TS3 server sends back when you use the `channellist` command **does** include the amounts of clients in each channel.

  So you can find the matching channel in that list and then call either `getTotalClients` or `getTotalClientsFamily` on it. `getTotalClients` counts just the clients in that specific channel, while `getTotalClientsFamily` includes the clients in the channel and all of its sub-channels 😃

**Comment by rogermb** [comment]
Closed due to inactivity.

**Comment by LUF3N** [comment]
Hi i am new to this but have the same problem. I can get my ChannelInfo like this 
`ChannelInfo channelInfo = Main.api.getChannelInfo(channelId);`
But i need the totalClients in a channel so i tried this:
`Channel channel = Main.api.getChannel(channelId);`
with the idea of doing something like this:
`int totalclients = channel.getTOtalclients(channelID);`

but it tells me that this part: 
`Channel channel = Main.api.getChannel(channelId);`
Cannot resolve a method. So how do i do it? :)
