### ISSUE TITLE
How can i enable debug mode

### ISSUE THREAD

**Issue by dshimen** [TheHolyWaffle/TeamSpeak-3-Java-API#286]
I would like to see what the query console returns to bot.

**Comment by Kakifrucht** [comment]
On your ``TS3Config`` object, call the method ``setEnableCommunicationsLogging(true)``.

**Comment by dshimen** [comment]
https://pastebin.com/t4d2pKEz

https://pastebin.com/1YCM3aLq

i enable this in two places

**Comment by Kakifrucht** [comment]
Are you using a custom logger? Do you add this API via Maven or the given .jar file?

**Comment by rogermb** [comment]
He did neither. He downloaded the entirety of our source code and is trying to use this API by modifying our code.

**Comment by dshimen** [comment]
Thank you rogermb, i created new project, imported your api jar and add slf4j logger ;) It's working, sorry for problem im just learing java on something i like.

**Comment by rogermb** [comment]
I'm glad to hear that. Sorry for the unfriendly response, I kinda had a bad day yesterday 😞

If you have any other questions, please don't hesitate to ask us over on [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). You'll usually don't have to wait for a response for quite as long there, as it's a bit more informal 😃
