### ISSUE TITLE
join leave event

### ISSUE THREAD

**Issue by Mikeichhalt** [TheHolyWaffle/TeamSpeak-3-Java-API#29]
Hi,
when I connect or disconnecte from server, it is recognized 2 times.
why?

[DEBUG] < [event] notifyclientleftview cfid=1230 ctid=0 reasonid=8 reasonmsg=Verlassen clid=5
[DEBUG] < [event] notifyclientleftview cfid=1230 ctid=0 reasonid=8 reasonmsg=Verlassen clid=5

[DEBUG] < [event] notifycliententerview cfid=0 ctid=1230 reasonid=0 clid=8 client_unique_identifier=...
[DEBUG] < [event] notifycliententerview cfid=0 ctid=1230 reasonid=0 clid=8 client_unique_identifier=...

[DEBUG] < [event] notifycliententerview cfid=0 ctid=1230 reasonid=0 clid=9 client_unique_identifier=...
[DEBUG] < [event] notifycliententerview cfid=0 ctid=1230 reasonid=0 clid=9 client_unique_identifier=...

**Comment by Firedroide** [comment]
Additional info for @TheHolyWaffle from someone who dealt with this issue before:

This happens because when one registers to both "server" and "channel", the query is first notified about the *client joining the server* (caused by "server") and then the *client entering the channel by joining the channel* (caused by "client).

**Comment by Mikeichhalt** [comment]
oh thanks :D

**Comment by Firedroide** [comment]
Uhm, this doesn't mean the issue is actually fixed, so I'd be glad if you re-opened it.

In fact, I'd really like to see this problem fixed on the API side ^^

**Comment by TheHolyWaffle** [comment]
Implementing this api side is too much of a hassle. Just don't register for
both channel and server.

2015-01-30 17:37 GMT+01:00 Firedroide <notifications@github.com>:

**Comment by Mikeichhalt** [comment]
It is rather not a bug, it's just something weird made from TeamSpeak :D
