### ISSUE TITLE
Invisible Bot in Chat

### ISSUE THREAD

**Issue by Jopeeee** [TheHolyWaffle/TeamSpeak-3-Java-API#292]
Hello,

I got a small Problem. My querry connects to the Teamspeak and works completely fine but after some Time the bot can't be reached by some users in Chat. Then it says the Bot is offline. 
Can you help me fixing this Problem?

Johannes

**Comment by rogermb** [comment]
That's very little information to go off. There was a bug where the query could randomly disconnect even when it was still connected in v1.1.0.

So I think first of all, you should just try updating to version 1.2.0 of this API. If that doesn't fix the issue, we'll do some more in-depth troubleshooting 😃

**Comment by Jopeeee** [comment]
Hey,

the issue is still existing. It even got worse and happends more often.

**Comment by rogermb** [comment]
Interesting! Do you have any other information that you could share with me?

Specifically, I'm interested in your log files and maybe even parts of your code. Do you see any messages that would indicate that the query has been disconnected in your log? And if you haven't done so already, could you turn on communications logging by calling `TS3Config#setEnableCommunicationsLogging`?
