### ISSUE TITLE
An Bot with own Version and Ontime?

### ISSUE THREAD

**Issue by blombler008** [TheHolyWaffle/TeamSpeak-3-Java-API#295]
Hi, 
I would like to decide myself how long the bot is online and what version it is using
is there an way to do it because the bot always shows up with

> Online since: 48 years 351 days 18 hours 53 minutes 23 seconds 
Version: ServerQuery on ServerQuery

because i want to bring like a label on the bot to separate them and still have a custom name
(my friends got one bot on my ts as well to watch users, updates from clan etc [privacy]).
What im thinking about is in the config two methods like...

``` java
public boolean setVersion(String vLabel) {
 //Code
}
public boolean setOnTime(long time) {
 //Code
}
```
and getters same...
or is there a way i can write it my self?

PS: The "online since goes from the 1.1.1970"

**Comment by rogermb** [comment]
This honestly doesn't sound like an API issue. Or, could you elaborate why you'd need this API to store and print something as trivial as a version string? I'm kind of at a loss here...

**Comment by blombler008** [comment]
Just askin ... Idk where this issue is comming from, on normal server query it shows the playform and the correct ontime... it is not so necessary but it gets me really confused ... and sorry for the broken englsih

**Comment by blombler008** [comment]
Ok ... i will close this because there is no way you can change it ... im sorry :D
