### ISSUE TITLE
Client flood level

### ISSUE THREAD

**Issue by Finnlife** [TheHolyWaffle/TeamSpeak-3-Java-API#297]
How i can get the flood Level of an Client?

I mean the flood points or something else.

I need it because i want to make an antispam between serverquery clients.

**Comment by rogermb** [comment]
I don't think there's a way to query the current flood points, no, I'm afraid.

Is the TeamSpeak3 flood system not feature-rich enough for you? There's a few settings you can change, as @GebesPlays hinted at.
