### ISSUE TITLE
Question: Set the formatter of the debugger

### ISSUE THREAD

**Issue by Gebes** [TheHolyWaffle/TeamSpeak-3-Java-API#298]
In 1.0.14 you could get the logger, remove all handlers and add your own handler with your own formatter. How do i do it on 1.2.0? It would be nice to have the same formatter in the same console

Like this:
		GebesFormatter formatter = new GebesFormatter();
		ConsoleHandler handler = new ConsoleHandler();
		handler.setFormatter(formatter);

		for (final Handler h : TS3Query.log.getHandlers())
			TS3Query.log.removeHandler(h);

		TS3Query.log.addHandler(handler);

**Comment by rogermb** [comment]
Hi!

You can either edit the [configuration file](https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html) of the SLF4J-Simple logger included in the `-with-dependencies` JAR, or you can use the JAR file without an included logging provider and add some other logging provider of your choice. The [SLF4J Manual](https://www.slf4j.org/manual.html) has a lot of information about how these logging providers work.

If you want to use a different logging provider, I'd strongly encourage you to use Maven or Gradle to manage your dependencies. If you want to manually manage your dependencies, here's a [direct link to the JAR file](http://central.maven.org/maven2/com/github/theholywaffle/teamspeak3-api/1.2.0/teamspeak3-api-1.2.0.jar) of this API without an included logger. If you were to use the java.util.logging binding, you could continue to use your existing `GebesFormatter`, but I have a feeling that other logging providers already contain the features you're manually re-implementing in your formatter class 😄
