### ISSUE TITLE
Kick Players

### ISSUE THREAD

**Issue by Badetuch** [TheHolyWaffle/TeamSpeak-3-Java-API#300]
Hey Guys,

How can i kick a player who wrote !deny to the bot?
Here is my code: https://gist.github.com/Badetuch/6e570190b653db52be24311ea82af3ef

(i couldn´t however paste the code in the Issue Report)

I know its a realy short Issue Report but i don´t know what i should add.

Hope somebody can help me :)

**Comment by rogermb** [comment]
If you want to kick the client who wrote the message, just use `e.getInvokerId()` as the client ID 😄 

I.e. in your code, `Load.api.kickClientFromServer(e.getInvokerId());` should work

**Comment by Badetuch** [comment]
WOW WT# u where sooo f##king fast LOL. Normaly it takes like no joke 3 Weeks. Tanks for the fast help!
btw. where i live its right now 3:55 am xd
But thanks now it works!
But how can i make a custom kick message?

**Comment by rogermb** [comment]
Yeah, same here, I was just about to get some sleep 😛 

Custom message: Message as the first argument, client IDs (one or multiple) after that.

```
Load.api.kickClientFromServer("You did this to yourself.", clientid);
```

**Comment by Badetuch** [comment]
Thanks man, i will go to sleep to :)

**Comment by Badetuch** [comment]
Last Problem i have: When i typed in "!verify" and got the "verified" Rank. I cant write the Bot "unverify". When i type it in my teamspeak says the Bot is offline. How can i fix this?
Heres my code: https://gist.github.com/Badetuch/376f4c934606342b501d9042aea81730       
So! Now im going to sleep!

**Comment by Badetuch** [comment]
So, idk but now it works.
I just did nothing xd

**Comment by Badetuch** [comment]
ok im so sorry for writing so much but it now doesnt work anymore

**Comment by Badetuch** [comment]
Another Question: How can i let the bot wait with one action? I tried thread.sleep(1000); but it didnt work.
I want that my Bot writes me that i get kicked in a few seconds, then the bot should poke me with"please join now again!" and then the bot should kick me.

**Comment by rogermb** [comment]
> I cant write the Bot "unverify". When i type it in my teamspeak says the Bot is offline.

Huh, that's weird. Are you sure that's not some kind of permissions mistake where group 14 prevents you from interacting with server queries?

> Another Question: How can i let the bot wait with one action?

I'd recommend using something like Java's [`ScheduledThreadPoolExecutor`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html). To get an instance of that executor, you could call [`Executors.newScheduledThreadPool(1)`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newScheduledThreadPool-int-). 😄

**Comment by Badetuch** [comment]
> Huh, that's weird. Are you sure that's not some kind of permissions mistake where group 14 prevents you from interacting with server >

I don´t  find a permission that should effect this. Which Permission could it be?

>I'd recommend using something like Java's ScheduledThreadPoolExecutor. To get an instance of that executor, you could call Executors.newScheduledThreadPool(1). >

Sorry i´m completely now with coding so i don´t know what you mean with this. Im sorry but can you explain it?

**Comment by rogermb** [comment]
I can't really teach you Java here, but maybe this will help:
https://www.baeldung.com/java-executor-service-tutorial

**Comment by rogermb** [comment]
> Can you help me with this?

Honestly, that was just a wild guess. I have no clue what could be causing this. Adding or removing a client to/from a server group doesn't prevent me from talking to a server query on my test server. Could you send me more information about what you see happening? Screenshots, maybe chat logs from your clients, server query logs from your application?

> Thanks i will read it soon!

Awesome 😄

**Comment by Badetuch** [comment]
> Honestly, that was just a wild guess. I have no clue what could be causing this. Adding or removing a client to/from a server group doesn't prevent me from talking to a server query on my test server. Could you send me more information about what you see happening? Screenshots, maybe chat logs from your clients, server query logs from your application?>

Im i sady right now can´t because my Teamspeak is down right now i have only tomorrow time :(

**Comment by rogermb** [comment]
No worries 😄 

It might take me a bit longer to respond to you tomorrow, though, I have some IRL stuff going on. Sorry about that 😅

**Comment by Badetuch** [comment]
> It might take me a bit longer to respond to you tomorrow, though, I have some IRL stuff going on. Sorry about that 😅>

No Problem :=)

**Comment by Badetuch** [comment]
Hey, dude i have a new Question, how can i let the Bot send a Message to somebody who joins a specified Channel?

**Comment by Tumbledore** [comment]
Hey,
first you need to Register the EventListener `onClientMoved(ClientMovedEvent e)` and there check if the `e.getTargetChannelId()` is the same as the ChannelId of the Specific Channel. If they are the same you can simply `Api.sendPrivateMessage(e.getClientId, "Message you want");`

i hope i could help you.
