### ISSUE TITLE
Weird error message i never got.

### ISSUE THREAD

**Issue by mnjg123** [TheHolyWaffle/TeamSpeak-3-Java-API#305]
Hi, i made an Teamspeak bot and 2-4 Weeks everything went well, but now i get this error Message:

> 2019-01-19 07:16:41.021 [DEBUG] TS3 command error: {msg=insufficient client permissions, id=2568, failed_permid=222}
> 2019-01-19 07:16:41.025 [ERROR] Event listener threw an exception
> com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "clientpoke" command returned with a server error.
> >> insufficient client permissions (ID 2568), failed permission with ID 222
>         at com.github.theholywaffle.teamspeak3.api.CommandFuture.checkForFailure(CommandFuture.java:415)
>         at com.github.theholywaffle.teamspeak3.api.CommandFuture.getUninterruptibly(CommandFuture.java:356)
>         at com.github.theholywaffle.teamspeak3.TS3Api.pokeClient(TS3Api.java:3436)
>         at me.mnjg123.events.EventList$1.onClientMoved(EventList.java:244)
>         at com.github.theholywaffle.teamspeak3.api.event.ClientMovedEvent.fire(ClientMovedEvent.java:56)
>         at com.github.theholywaffle.teamspeak3.EventManager$ListenerTask.run(EventManager.java:169)
>         at com.github.theholywaffle.teamspeak3.TS3Query.lambda$submitUserTask$0(TS3Query.java:232)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

what could it be?

My Bot asks at every Move if someone moved into a specific channel and then pokes Staff on the Server,

**Comment by Tumbledore** [comment]
Hey, this „insufficient client permissions (ID 2568), failed permission with ID 222“ sounds more like an Error with the Permissions on your TS Group or that the Server Query doesn‘t have the Permissions anymore.

**Comment by rogermb** [comment]
I agree. Permission 222 is the `i_client_needed_poke_power`, too. @mnjg123 you should check whether your username + password login works correctly and whether the server group that your server query belongs to has the required permissions to poke clients. You should also check whether someone has changed the `i_client_needed_poke_power` power for a server group that your **target** clients belong to. A server query is allowed to poke a client if its `i_client_poke_power` is equal to or larger than the target client's `i_client_needed_poke_power`.

**Comment by Tumbledore** [comment]
as an Addition: 
I had some problems with it, as the Server Group was unassigned from my Client who created the ServerQueryLogin. As my Identity got the ServerGroup back, the ServerQuery got it back too.
