### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by Finnlife** [TheHolyWaffle/TeamSpeak-3-Java-API#308]
I dont have an Issue withe the api i think.
But i think here are people, who can help me.
I cant connect to my ts3 Server. When i start the bot from my pc it works.
But when i start the bot on my Linux Server, there is an Connection timeout issue.
But how could that happend ?
I think the IP was blacklistet
Thinks i tryed:
- Watching in the Iptables (Not in it)
- Watching in the Ts3 Query blacklist (Not in it)

I'm using CloudFlare

I hope somebody could help me.

**Comment by Tumbledore** [comment]
Hey,
Im not familiar with CloudFlare but there could be multiple Issues here. 
Is the Linux Server your RootServer for the TS? If it is not then maybe some Problems with the Firewall or the Ports?

I Hope i could help you a bit or atleast could help you to get on the right path.

**Comment by rogermb** [comment]
Yeah, I'm also not familiar with CloudFlare. Maybe they're blocking the port that the query usually uses to communicate with the TS3 server (10011)? You could try setting the query port to some generic port like 80, 20, or 21 if you don't need HTTP or FTP.

You could also try connecting to your TS3 server using the Windows `telnet` utility or some other program, just to make sure it's not an issue with your code.

The issue could also be your DNS records. Maybe they're only set up for port 9987, the voice port? You should definitely also try connecting to your TS3 server using its IP if you've been using the hostname up until now.
