### ISSUE TITLE
Can not set channel permission

### ISSUE THREAD

**Issue by NIFO43** [TheHolyWaffle/TeamSpeak-3-Java-API#309]
I want to set the description power but this not work.

if i do `api.addChannelPermission(291, "i_channel_needed_join_power", 70)` it work
but this work not `api.addChannelPermission(291, "i_channel_description_view_power", 70)`

**Comment by rogermb** [comment]
Hi @GeRaged 

Could you please describe what doesn't work in a bit more detail? Are you getting an exception?

**Comment by GeRaged** [comment]
@rogermb I have described what does not work. There is no error message

**Comment by rogermb** [comment]
Either the command is executed successfully and you're not getting an exception, or the command returns with an error, in which case an exception is thrown.

Could you please turn on communications logging by calling `ts3Config.setEnableCommunicationsLogging(true)`, re-run your code, and then send me the console output this produced? 😃

**Comment by hashtagMrice** [comment]
Maybe use `api.addChannelPermission(291, "i_channel_needed_description_view_power", 70)`
