### ISSUE TITLE
bug api.getClientByUId

### ISSUE THREAD

**Issue by Mikeichhalt** [TheHolyWaffle/TeamSpeak-3-Java-API#31]
Hi,
i found a bug at api.getClientByUId("...")

This code:
System.out.println("1: ");
System.out.println( api.getClientByUId("o5mMbQVxuY+H6+xqDFC6IMeOSsI=") );
System.out.println("2: ");
System.out.println( api.getClientByUId("/faJROK+K5/luQN/CSpkoP85n3I=") );

gives me this:

1: 
[DEBUG] > clientgetids cluid=o5mMbQVxuY+H6+xqDFC6IMeOSsI=
[DEBUG] [clientgetids] < cluid=o5mMbQVxuY+H6+xqDFC6IMeOSsI= clid=22 name=\pCoN\pMike
[DEBUG] [clientgetids] < error id=0 msg=ok
[DEBUG] > clientinfo clid=22
[DEBUG] [clientinfo] < cid=3 client_idle_time=408366 client_unique_identifier=o5mMbQVxuY+H6+xqDFC6IMeOSsI= client_nickname=...
[DEBUG] [clientinfo] < error id=0 msg=ok
{client_channel_group_id=8, client_security_hash=, client_nickname=...
2: 
[DEBUG] > clientgetids cluid=\/faJROK+K5\/luQN\/CSpkoP85n3I=
[DEBUG] [clientgetids] < error id=1281 msg=database\sempty\sresult\sset[DEBUG] [SEVERE] [ERROR] {msg=database empty result set, id=1281}

[DEBUG] > clientinfo clid=-1
[DEBUG] [clientinfo] < error id=1540 msg=convert\serror
[DEBUG] [SEVERE] [ERROR] {msg=convert error, id=1540}
{}

The first works without problems.
I think it is because the / character in cluid.
right?
Or am I doing something wrong?

thanks :D

**Comment by Mikeichhalt** [comment]
oh ok I have found the error.
The error occurs when the person is not connected.
Is this normal ?

**Comment by Firedroide** [comment]
TS3Api#getClientByUId(String) gets information about a currently online client.

If you really need offline information about a client, you can use TS3Api#getDatabaseClientByUId(String).

**Comment by Likqez** [comment]
Hey, i got the same thing and i wonder how could i check if the person with the Identifier is online or not?
`if(api.getClientByUId(UniqueIdentifier) != null)` does not work there

**Comment by rogermb** [comment]
@Likqez [TS3Api#isClientOnline(String clientUId)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/68807a93de23cd3fde1efdf36c29823992fd72ce/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L2816-L2833) should do what you're looking for 😄
