### ISSUE TITLE
[Question] If message equals

### ISSUE THREAD

**Issue by 0x0foriv** [TheHolyWaffle/TeamSpeak-3-Java-API#310]
Hi guys, i have a question do any one know who to do if message equals(fsfds) i was trying to do this for like 3 hours please quick help.

**Comment by rogermb** [comment]
Hi

Could you give me a bit more information about what you're trying to do and what doesn't work?

If you're trying to make something like a chat bot, maybe take a look at [example/ChatBotExample.java](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ChatBotExample.java) 😃

**Comment by foriv** [comment]
I Am trying to do something like this if message equals !m it will give a rank !g it will give a girl rank

**Comment by rogermb** [comment]
In that case, please check out the example I've linked. That should help get you going 😄
