### ISSUE TITLE
Debug and other Querys

### ISSUE THREAD

**Issue by Galileon-venta** [TheHolyWaffle/TeamSpeak-3-Java-API#318]
Does anyone know a way to prevent a Console-Spam by Debugger with `[DEBUG] TS3 command error: {msg=invalid clientID, id=512}` because of something like this:
![image](https://user-images.githubusercontent.com/48894231/54920004-6edcbe00-4f02-11e9-8388-9c714f539bff.png)

**Comment by FLOODY88** [comment]
Hi @Galileon-venta, looks like this is a query and somewhere in your code, you try to get the query's clientID, most likely in `TS3Listener#onClientJoin`. You can prevent such an error by checking whether the joined client is a server query and if so, simply do nothing.

This is just a guess and it would help if you could provide a minimal, complete, and verifiable example of your code.

**Comment by Galileon-venta** [comment]
@FLOODY88 did so, but the Query mentioned in my screenshot connects and disconnects faster than my Bot reacts...
Code for my Listener starts like this:

`public void onClientJoin(ClientJoinEvent clientJoinEvent) {
                try {
                    Client c = load.api.getClientInfo(clientJoinEvent.getClientId());
                    // Queryfilter
                    if (c.getType() == 1) return;`
Problem: c.getType() cant get the Client anymore because he?!/it is already offline again.

**Comment by FLOODY88** [comment]
This should do the trick. I did not test it, if this snippet still fails, I'll set up a test bot to look into your issue.

```java
@Override
public void onClientJoin(ClientJoinEvent e) {
	// Get the client's information based on the clientId.
	Client client = api.getClientInfo(e.getClientId());

	if(client.isServerQueryClient()) {
		// If the connected client is a query, do nothing.
		return;
	}
}
```

**Comment by Galileon-venta** [comment]
Ok, you are up for method is Query Client, but getType() is nearly similar... It just returns 0(Client) or 1(Query) instead of True(Query) or False(no Query)... I believe, its running into the same problem, client.getType / .isServerQueryClient will check for a client which already disconnected again :o

**Comment by FLOODY88** [comment]
> Ok, you are up for method is Query Client, but getType() is nearly similar... It just returns 0(Client) or 1(Query) instead of True(Query) or False(no Query)... I believe, its running into the same problem, client.getType / .isServerQueryClient will check for a client which already disconnected again :o

Did you try my snippet? I just tried it and it works like a charm. I know you're basically doing the same thing there, but just using `Client#isServerQueryClient()` or `Client#isRegularClient()` is easier and more efficient. Also, you may try to delete your `try/catch` block, since it's unnecessary.

**Comment by Galileon-venta** [comment]
Try Catch Block is just around everything in my Listener... and its a huge one... up to 80 Lines i think...

Il try for your Code... Please wait some Minutes for Feedback :D

**Comment by Galileon-venta** [comment]
Ok, somehow there are no Querys acting like described in my first comment at the moment... il leave your version of the Code on for Tonight and if my Log is full of [Debug] messages tomorrow morning we can go on with deeper discussions, if not, we can close this problem :d

**Comment by FLOODY88** [comment]
@Galileon-venta it will most likely be fixed. However, you can force a query to connect by connecting to your server via telnet and see how it behaves.
Anyway, having a `try/catch`-block around your whole is usually no a good idea. You may look up how to use `try/catch`. If you want, you can commit your code to GitHub and I'll look into it and do some clean ups with you.

**Comment by FLOODY88** [comment]
I had a little chat with @rogermb and we figured out that the **only** way to get rid of the debug message is to increase your log level, which will prevent you from receiving any debug messages at all. However, my solutions above will not catch the thrown exception, you still need to catch `TS3CommandFailedException` when trying to get the client's information.

**Comment by Galileon-venta** [comment]
So I tried to compare your code and my code...
Your code has thrown a debug 4 times, while my code has thrown about 30...

TryCatch is just while im in dev... i got like ~15 of them just to lead me to the Position in Code the error comes from... ill remove them after I finished my code i want to dev.
