### ISSUE TITLE
How does the reconnect work?

### ISSUE THREAD

**Issue by Motzkiste** [TheHolyWaffle/TeamSpeak-3-Java-API#319]
Hi,

I think i've doen something wrong, because my bo does not reconnect to my teamspeakserver.
I tried to simulate a random disconnect by restarting the server, but the he's not reconnecting.

Some information for you:
- The TS-Server and the bot are not running on the same System, but for now there is now way he would get flood bannen.
- I'm using API-v1.2.0 with Java 8

Maybe i've done something wrong in the code, so here is some code:
- Part of TSBot-Contructor
```
        config.setEnableCommunicationsLogging(true);

        config.setReconnectStrategy(ReconnectStrategy.constantBackoff(60000));

        config.setConnectionHandler(new ConnectionHandler() {

            @Override
            public void onConnect(TS3Query ts3Query) {
                System.out.println("connected!");
                onReConnect(ts3Query.getApi());
            }
            
            @Override
            public void onDisconnect(TS3Query ts3Query) {
                System.out.println("disconnected!");
            }
        });

        query = new TS3Query(config);

        query.connect();

        onFirstConnect(query.getApi());

        query.exit();
```
- onReConnect()
```
    private void onReConnect(TS3Api api) {
        api.login(username, password);
        api.selectVirtualServerById(virtualServerID);

        //Because of getting an Error when setting the same nickname again
        if (!api.whoAmI().getNickname().equals(nickname))
            api.setNickname(nickname);
        api.moveQuery(channelID);

        tMH.setBotID(api.whoAmI().getId());

        api.registerEvent(TS3EventType.TEXT_CHANNEL);
        api.registerEvent(TS3EventType.TEXT_PRIVATE);
        api.registerEvent(TS3EventType.TEXT_SERVER);
    }
```
- onFirstConnect()
```
    private void onFirstConnect(TS3Api api) {
        tMH.setApi(api);

        api.addTS3Listeners(new TS3EventAdapter() {

            @Override
            public void onTextMessage(TextMessageEvent e) {
                tMH.handle(e);
            }

            @Override
            public void onClientMoved(ClientMovedEvent e) {

            }

            @Override
            public void onClientJoin(ClientJoinEvent e) {

            }
        });
    };
```

When I'm restarting the TS-Server the console won't show up the "disconnected!" from `onDisconnect(TS3Query query) {...}` and he won't reconnect after a minute.

My only last idea i have is that the restart of the TS-Server is only restarting the VirtualServer and the query disconnect/reconnect methods are only called when it would disconnect from the real TS-Server.

So I really don't know what i'm doing wrong...

Sry for my bad english and I really hope you can help me D:
BTW thank you for your time and help ^^

**Comment by Tumbledore** [comment]
Hi, maybe you can find your answer in #181.

As mentioned there, there is no possibility to catch a disconnect of Virtual Server. 
Maybe your "restart" is the disconnect and connect to the VirtualServer.

but I think @rogermb can explain it better.

greetings

**Comment by rogermb** [comment]
Hi @Motzkiste!

Your code looks correct, with one small exception: you seem to be calling `query.exit()` right after connecting, which - well - disconnects your query. This looks like it wasn't intended.

And yeah, if your hosting provider only restarts your virtual server, the reconnect system won't do much for you. That was really only intended for complete loss-of-communications events.

However, if only the virtual server is restarted and the server keeps running, you should get a `notifyclientleftview` event with your query's own client ID and with 0 as the target server ID.

To get these events, you'd also need to register for the `TS3EventType.SERVER` event type. (At this point, it might be a good idea to just call `TS3Api#registerAllEvents()`).

Then, you could have some event listener such as this one to re-join the server, re-register for events, set your nickname, choose the channel, and so on. Example:

```
	api.addTS3Listeners(new VirtualServerShutDownListener(api));

	private static class VirtualServerShutDownListener extends TS3EventAdapter {

		private final TS3Api api;

		private VirtualServerShutDownListener(TS3Api api) {
			this.api = api;
		}

		@Override
		public void onClientLeave(ClientLeaveEvent clientLeaveEvent) {
			if (clientLeaveEvent.getClientId() == myClientId && clientLeaveEvent.getClientTargetId() == 0) {
				System.out.println("We were kicked from our virtual server");
				rejoinServer();
			}
		}

		private void rejoinServer() {
			while (true) {
				try {
					onReConnect(api);
					return;
				} catch (TS3CommandFailedException failed) {
					// Ignored
				}

				try {
					Thread.sleep(5_000L);
				} catch (InterruptedException e) {
					return;
				}
			}
		}
	}
```

I hope this helps! 😄

**Comment by Motzkiste** [comment]
Hi, 

thank you for your really fast support 👍 
And yes, my provider is only restarting the VServer... *sigh*

The `query.exit()` was out of this example [ReconnectExample.java](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/v1.2.0/example/ReconnectExample.java).
I thought it would trigger the reconnectstrategy ... my fault :'D

I never thought about catching a VServer-Disconnect, so really thank you ^^

BTW it works ^^ Both reconnects work (tested query reconnect, by switching on vpn) ^^

At least i have two last questions:
The `ReconnectStrategy.exponentialBackoff(...)` has 3 possible values, right?
Are the `startTimeout` and `timeoutCap` milliseconds?
And is the `timeoutCap` the cap for one reconnect or for all tries summed up?

Thank you again ^^

**Comment by rogermb** [comment]
> I never thought about catching a VServer-Disconnect, so really thank you ^^

You're welcome! 😄 

> BTW it works ^^ Both reconnects work (tested query reconnect, by switching on vpn) ^^

Awesome!

> The ReconnectStrategy.exponentialBackoff(...) has 3 possible values, right?

Correct, but you can usually just use the no-args method, which starts with a timeout of 1 second between reconnects and multiplies that by 1.5 after every failed reconnect. The upper time limit between reconnects would be 1 minute.

> Are the startTimeout and timeoutCap milliseconds?

Yeah, they are. I should probably properly document these methods 😅 

> And is the timeoutCap the cap for one reconnect or for all tries summed up?

The cap basically just exists to prevent the timeout between reconnect attempts from growing too large. It doesn't mean that it'll stop trying to reconnect after some time. So with a timeoutCap of 60_000, you'd always try to reconnect at least once per minute, even after hundreds of failed attempts to reconnect.

example: startTimeout = 2_000, multiplier = 2.0, timeoutCap = 10_000
[00:00:00] Disconnected
[00:00:02] 1st attempt to reconnect after 2 seconds
[00:00:06] timeout *= 2 -> waited 4 seconds until trying to connect again
[00:00:14] timeout *= 2 -> waited 8 seconds until trying to connect again
[00:00:24] timeout * 2 > 10_000 -> waited 10 seconds until trying to connect again
[00:00:34] and from here on out...
[00:00:44] ... it's always 10 seconds

**Comment by Motzkiste** [comment]
Wow I love the fast support here.

Some time ago i asked something in Gitter (time of v1.0.12 or 14) and everyone helped me so fast... just awesome 😄

>  Yeah, they are. I should probably properly document these methods 😅

Yes please xD

> The cap basically just exists to prevent the timeout between reconnect attempts from growing too large. It doesn't mean that it'll stop trying to reconnect after some time. So with a timeoutCap of 60_000, you'd always try to reconnect at least once per minute, even after hundreds of failed attempts to reconnect.

Thats awesome!
That means even if my ts-server should go down for ... maybe a day it would reconnect :O

So i'll mark this one here as closed 😄 

Really thank you again 😄
