### ISSUE TITLE
Feature request: Timeout value in config

### ISSUE THREAD

**Issue by phillmac** [TheHolyWaffle/TeamSpeak-3-Java-API#32]
I have an issue where trying to debug from my home internet often fails with a error "Command channellist is not answered in time" on the initial connection stage because of my slow/dodgy connection. Often it fails in what seems to be about 1 second, which is far to short. My teamspeak client sometimes takes 10-30 seconds to get a complete listing. Would it be possible to add a timeout option to the config class so that I can increase the amount of time to wait for replies?

**Comment by TheHolyWaffle** [comment]
sure, send me a pull request.

**Comment by Firedroide** [comment]
Added in a18c7f66315369b71a65b7221efbe26e5052b6c5.

Thank you very much for the feature request.
If there's anything else that you're missing from this API, feel free to open another issue!
