### ISSUE TITLE
Problems starting the jar file

### ISSUE THREAD

**Issue by NewJavaDeveloper** [TheHolyWaffle/TeamSpeak-3-Java-API#320]
The programming is completed in my case so far.
Now I've exported my Eclipse project to a jar file and I want to run it on Windows 10.
However, I always get the following error message:

> Exception in thread "main" java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config
        at de.ragecraft.Main.<clinit>(Main.java:9)
Caused by: java.lang.ClassNotFoundException: com.github.theholywaffle.teamspeak3.TS3Config
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

My first problem was that I had forgotten to set the main manifest attribute, but this problem is already solved.
Strangely enough, I can easily start and run my programming without errors in Eclipse, but not outside of Eclipse for example in cmd.
Please tell me my mistakes because I want to fix them as soon as possible.
I ask for quick response, because this is a very important project.

Yours sincerely,
NewJavaDeveloper

**Comment by NewJavaDeveloper** [comment]
This is the complete code of my main-class:

> package de.ragecraft;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;

public class Main {
	
	public static final TS3Config config = new TS3Config();
	public static final TS3Query query = new TS3Query(config);
	public static final TS3Api api = query.getApi();
	public static String prefix = "[COLOR=#808786][[/COLOR][color=#00aaff]Verifizierungs-Überprüfung[/color][COLOR=#808786]][/COLOR] ";
	public static String status = " [COLOR=#808786][[/COLOR][color=gold]Status[/color][COLOR=#808786]][/COLOR]";
	public static String task = " [COLOR=#808786][[/COLOR][color=gold]Task[/color][COLOR=#808786]][/COLOR]";
	
	public static void main(String[] args) {
		System.out.println("Der Bot wird gestartet...");
		System.out.println("Der Bot wird mit dem Teamspeak-3-Server verbunden...");
		config.setHost("minecraft-schule.de");
		query.connect();
		api.login("Test", "fXVIP38q");
		api.selectVirtualServerById(1);
		api.setNickname("Systembot 2");
		System.out.println("Der Bot wurde erfolgreich mit dem Teamspeak-3-Server verbunden!");
		api.sendServerMessage(Main.prefix + "[color=green]Der Bot wurde erfolgreich mit dem Teamspeak-3-Server verbunden![/color]" + Main.status);
		Events.loadEvents();
	}
	

}

**Comment by rogermb** [comment]
Hi @NewJavaDeveloper!

This is an Eclipse problem and not an issue of our API - you're simply not including our library in the JAR file you're building. Also, both a google search or even a search in the issues of this project for "NoClassDefFoundError Eclipse" would've told you how to fix this issue yourself 😛

Anyway - here's an explanation by @somefriggnidiot of how to fix this issue: https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/247#issuecomment-359785608

Hope this helps! 😄

**Comment by Tumbledore** [comment]
Hi @NewJavaDeveloper ,

maybe you could look up "Building FatJar" at Google.
The FatJar is a normal Jar but it includes all Dependencies.

Greetings
