### ISSUE TITLE
Servergruppen vom offline Client

### ISSUE THREAD

**Issue by TUBEOF** [TheHolyWaffle/TeamSpeak-3-Java-API#321]
Hallo, ich hoffe Sie verstehen Deutsch, andernfalls bitte ich den Google Übersetzter oder anderes zu nutzen. Danke!

Ich habe derzeit über diesen Code abgefragt, ob ein offline Client in einer bestimmten Server-Gruppe ist. (Mittels der ClientDBID und der Group-ID) https://pastebin.com/MxJxPYwZ

Gibt es eine bessere Methode? Ich habe schon alles mögliche Versucht jedoch führten diese alle nicht zum Ziel..

Danke im Vorraus!

**Comment by Tumbledore** [comment]
Hey @TUBEOF ,

i don't see any better way to get the ServerGroup of an Offline Client. all I could thin of are to Ways:

`
public static boolean isDatabaseClientInServerGroup(int ID, int ServerGroupID) {
        (1) return api.getClientInfo(ID).isInServerGroup(ServerGroupID);
             //Only Java 8->
        (2) return api.getServerGroupsByClientId(ID).stream().anyMatch(s-> s.getId() == ServerGroupID);
 }
`

I hope maybe I could help you.

**Comment by FLOODY88** [comment]
Hey @TUBEOF, you could narrow the method down to one `return` statement. This will either return `true` if [`String.contains()`](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#contains(java.lang.CharSequence)) finds any matching entries, `false` otherwise.
```java
public static boolean isDatabaseClientInServerGroup(int clientDatabaseId, int serverGroupId) {
    return api.getServerGroupsByClientId(clientDatabaseId).toString().contains("sgid=" + serverGroupId);
}
```
You could also use the client's unique identifier to check the server groups.
```java
public static boolean isDatabaseClientInServerGroup(String clientUId, int serverGroupId) {
    Client client = api.getClientByUId(clientUId);
    return client.isInServerGroup(serverGroupId);
}
```
However, I would recommend that you take a closer look at the [code conventions](https://www.oracle.com/technetwork/java/codeconventions-135099.html) for naming.

@Tumbledore, GitHub formats your code properly, but you have to use ` ``` ` for a block code. For further reference, please see [GitHub's markdown guide](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code).

**Comment by rogermb** [comment]
Using `toString` on a Wrapper object and then using `String.contains` is *wrong*. Consider a client in server group 11: `"sgid=11".contains("sgid=1")` will return true even though the client is not in server group 1.

Moreover, as @TUBEOF specified, he's interested in the server groups of an *offline* client. Neither `getClientInfo` nor `getClientByUId` work on clients that are offline. `Client` objects represent clients that are online.

@Tumbledore's second proposal works correctly. As this API requires Java 8, I think it's safe to assume that @TUBEOF can use this code. 😄 

```java
private static boolean isDatabaseClientInServerGroup(int clientDbId, int serverGroupId) {
	return api.getServerGroupsByClientId(clientDbId).stream()
	                                                .anyMatch(s -> s.getId() == serverGroupId);
}
```

**Comment by TUBEOF** [comment]
Thanks!
