### ISSUE TITLE
insufficient client permissions which (at least) seem to be given

### ISSUE THREAD

**Issue by Galileon-venta** [TheHolyWaffle/TeamSpeak-3-Java-API#329]
Exception in thread "main" com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "channelcreate" command returned with a server error.
>> insufficient client permissions (ID 2568), failed permission with ID 81

ID 81 is b_channel_info_view which is set to true in Teamspeak Permissions for my query Group...
![image](https://user-images.githubusercontent.com/48894231/58350836-5720a800-7e67-11e9-9773-dfbf606df754.png)

Any Idea?

**Comment by Galileon-venta** [comment]
Fixed it myself;
 
Error appears when i_channel_max_depth is not set. Error reference is wrong. Should be 77 for missing permissions at i_channel_max_depth.

**Comment by rogermb** [comment]
Ah, interesting! Might be a good idea to report this to the TeamSpeak guys. We don't do that "figuring out which permission caused the error" ourselves, we just forward the error message the TS3 server sent us.
