### ISSUE TITLE
Space channel

### ISSUE THREAD

**Issue by TracerYT** [TheHolyWaffle/TeamSpeak-3-Java-API#333]
Hi. Is it possible to make space channel using API? And change its name to e.g. `Clients online : 2`? I'm doing Channel renamer. When user join the server, channel is edited to users count.

**Comment by Jopeeee** [comment]
Just name the Channel like a Spacer e.g. "[cspacer]Clients online: 2" with the Method [createChannel](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L700).
