### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by PrinzKenny1** [TheHolyWaffle/TeamSpeak-3-Java-API#335]
Hello,
if the query is timing out and you have a timer that schedules every second and stops the query after 5 seconds when the thread couldn't be done, the exit function is going to hang up. This happens because in the CommandQueue at the method shutDown in the while loop there should be checked if the connection is still active.

**Comment by rogermb** [comment]
Sorry for taking so long to respond. Had a lot of IRL stuff going on, and it'll probably be another 3-4 weeks until I'll be able to work on this API again.

What version of the API are you using? The latest public release, v1.2.0, doesn't even contain the CommandQueue class yet. Are you on v1.3.0-SNAPSHOT?

Also, keep in mind that `TS3Query#exit()` is *supposed to* block until all commands have been processed. For the query to time out, the command queue must've contained commands and it must not have received any data from the TS3 server for at least `commandTimeout` milliseconds. If the query times out and the default (DISCONNECT) reconnect strategy is used, all commands will be marked as having failed.
