### ISSUE TITLE
API incompatible with the newest version?

### ISSUE THREAD

**Issue by Rindula** [TheHolyWaffle/TeamSpeak-3-Java-API#339]
I noticed, when updated the TS3 Server many commands like create a Channel, move a Client, message a Client and so on don't work anymore. Renaming the Channel still works fine.

Edit: TS Server Version: 3.9.1

**Comment by sgebauer** [comment]
Similar problem here after updating to 3.9.1.
Creating and editing channels mostly works, except when you try to set a channel icon ID:
```
com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "channeledit" command returned with a server error.
>> invalid parameter (ID 1538)
```

**Comment by rogermb** [comment]
@sgebauer If I recall correctly, channel icons on TeamSpeak are not a channel property, but rather a channel permission. Keep in mind that this API is a rather thin wrapper around the Server Query interface.

Example:
```java
api.addChannelPermission(targetChannelId, "i_icon_id", someIconId);
```

**Comment by sgebauer** [comment]
I've used the `CHANNEL_ICON_ID` channel property so far. The 3.9.1 documentation still lists it as changeable, but trying to change it via `api.editChannel` fails now.

Anyway, setting the `i_icon_id` permission instead works. Thank you!

**Comment by rogermb** [comment]
@sgebauer Yeah, I think that's because it works (as a channel property) when first creating the channel, if I recall correctly. Just TeamSpeak things 😛
