### ISSUE TITLE
Slow responses

### ISSUE THREAD

**Issue by DanielAlves123** [TheHolyWaffle/TeamSpeak-3-Java-API#342]
Hi, why bot is waiting long time, sometimes around 30 seconds to take actions, for example respond to private message or send message on join?

**Comment by rogermb** [comment]
Hi!

Keep in mind that there is only one connection to the server. If you're sending multiple commands to the server concurrently, the commands can queue up, which can cause (potentially unbounded) delays.

How long it will take a single command to be sent depends on two factors:
- Flood rate: by default, a TS3 server will temporarily ban any query client that sends more than 10 commands every 3 seconds. To prevent inexperienced users from getting banned immediately, this API respects these limits by default and only sends one command every 350 milliseconds.  
If you need to send commands at a greater rate than that, you'll first have to add the IP of the machine that your query client runs on to the TS3 server's `query_ip_whitelist.txt` (see page 6 of your TS3 server's doc/ts3_serverquery_manual.pdf). Then, tell the API to use the `UNLIMITED` flood rate setting by calling `setFloodRate(FloodRate.UNLIMITED)` on your TS3Config object.
- Ping: In most cases, you need to wait for your command to make its way to the server and back to your query client. If your query client and your TS3 server are running on different machines that are far away, this can take some time. No way to circumvent physics, unfortunately 😄 

You can also turn on the logging of all messages sent and received by your query client by calling `setEnableCommunicationsLogging(true)` on your TS3Config object, which should help debug these kinds of issues. I hope that helps!

**Comment by DanielAlves123** [comment]
@rogermb thanks <3 It works instantly now :D

**Comment by DanielAlves123** [comment]
@rogermb is there a way to let bot have the same clientid? When he reconnects it shows that he is offline when you have open conversation with him.

**Comment by rogermb** [comment]
I'm afraid there isn't, no. This has been a TeamSpeak bug for ages, so you'll likely just have to accept it and work around it :/
