### ISSUE TITLE
Delay at executing Events

### ISSUE THREAD

**Issue by Likqez** [TheHolyWaffle/TeamSpeak-3-Java-API#343]
> Hey, I created myself a small authentication Service witch communicates with Client on an online platform and TeamSpeak. I dont know why but suddenly i got massive Delays from Events that are being excecuted. I Run this code at the JoinEvent : https://hasteb.in/cokipase.java

but this Messages are weirdly sent massive Delay later. Like 3 sometimes 9min. 
Can someone help?

Thanks in advance
Likqez

**Comment by rogermb** [comment]
Hi @Likqez!

That's indeed a strangely long delay! Just to make sure we're not wasting both of our time, could you please first check out [my response](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/342#issuecomment-541437561) to #342, which also dealt with slow responses?

**Comment by Likqez** [comment]
Thanks, I'll try that out and reply if I have more Information

**Comment by Likqez** [comment]
Hey, i have set my Flood to unlimited now and did some testing. The TeamSpeak Server is running on the same machine as the application. It still has those delays.Then I tried to use the async Api only for the events and all the other stuff normal sync. But still having the delays. Any other solution in mind?

Regards Likqez

**Comment by Likqez** [comment]
Hello,
still have the same problem. Tried to only use the Async Api but didnt change a thing, made it worse at some points. I just can't figure out why the events need to much time to handle, as the TeamSpeak server is at the same machince and accessed over locahost.

I need some help

Thanks in advance
Likqez

**Comment by rogermb** [comment]
Hi, sorry for taking so long to reply, I was quite busy this week 😅 

Could you show me the code that you're using to handle your events, as well as the code that you're using to register the event listener? I feel like that might be the easiest way to tackle this issue.

Also, it may be helpful to enable logging of the communication between the TS3 server and the query client by calling `setEnableCommunicationsLogging(true)` on your `TS3Config` object *before* handing that object over to `TS3Query`'s constructor. That way, you'll see what commands and responses are being sent back and forth between the client and the server, which should also help in diagnosing this issue 😃

**Comment by Likqez** [comment]
Hi,
currently i'm registering them like this : 
https://hasteb.in/yatuwuma.lua

and Handling like this: 
https://hasteb.in/judugefu.java

Can you explain me where i would get the Logging output? Didnt found it after searching in my console and the ts log.

**Comment by Likqez** [comment]
I just discovedred something really strage..
Executing my programm on a diffrent machine then the TeamSpeak Server, my development environment this time. The delay is not present wtf.. Yeah i got no message that im flodding, i got no log in my console etc. but why isnt it working on the production environment? I think i', getting trolled by my server xD

**Comment by Likqez** [comment]
Hi, another quick Question: Is the Communication between TeamSpeak and Application resulting in heavy CPU usage? Bc my cores are normally under 5% Load and with the Application its more then 40%?
Does this come from the TsApi?

Thanks in advance
Likqez
