### ISSUE TITLE
Problem with adding group to client

### ISSUE THREAD

**Issue by ololjvNek** [TheHolyWaffle/TeamSpeak-3-Java-API#346]
Ok so. I have this code:
`                            Client c = Main.api.getClientByUId(e.getInvokerUniqueId());
                            Main.api.addClientToServerGroup(2, c.getDatabaseId());`
But they don't work and giving me this error:

`ERROR com.github.theholywaffle.teamspeak3.EventManager - Event listener threw an exception
com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "servergroupaddclient" command returned with a server error.
invalid clientID (ID 512)`

Line of the error is Main.api.addClientToServerGroup(2, c.getDatabaseId());

Anyone can help?

**Comment by yannicklamprecht** [comment]
Use `c.getId()` instead of `c.getDatabaseId()`

**Comment by ololjvNek** [comment]
now error is: >> duplicate entry (ID 2561)

**Comment by yannicklamprecht** [comment]
> now error is: >> duplicate entry (ID 2561)

I assume that the user has the group already.

**Comment by ololjvNek** [comment]
Ahh okay i see the problem. I just wanna add a Server Admin Query to me but this doesn't work
