### ISSUE TITLE
Only working with async

### ISSUE THREAD

**Issue by PhillTV** [TheHolyWaffle/TeamSpeak-3-Java-API#347]
Hello, i have a bot and the bot needs to run with Async

`	public static final TS3Config config = new TS3Config();

	public static final TS3Query query = new TS3Query(config);

	public static final TS3ApiAsync async = new TS3ApiAsync(query);

	public static final TS3Api api = new TS3Api(async); `

this is the code, My friends are able to run it sync. How to fix it?

i use Eclipse Oxygen on Windows 10 x64

**Comment by yannicklamprecht** [comment]
I don't know if that matters but by starting with an object oriented style could help getting initialisation problems fixed.

**Comment by uleqitgod** [comment]
This is my Code.
`public static final TS3Config config = new TS3Config();
	public static final TS3Query ts3query = new TS3Query(config);
	public static final TS3Api api = ts3query.getApi();`

**Comment by rogermb** [comment]
You need to make your changes to `TS3Config` **before** the constructor of `TS3Query` is called.
i.e. don't keep those in public static final fields.
