### ISSUE TITLE
Breaking chanes vs. deprecating methods

### ISSUE THREAD

**Issue by Firedroide** [TheHolyWaffle/TeamSpeak-3-Java-API#35]
How should I handle API changes on this project? Shall I just do the changes, breaking compatibility with older implementations, or shall I try to go for maximum compatibility?

So, for example, there's a method called Client getClientByName(String pattern), which should actually return a collection of Clients instead of a single client, because more than just one client's name can match the pattern "a".

So, should I just change the method to return a Collection<Client> or should I try to maintain backwards compatibility by adding a deprecated redirection method?

    // Maximum compatibility
    public Client getClientByName(String name) {
        return getClientsByName(name).get(0);
    }

    public List<Client> getClientsByName(String name) {
        // get all the clients!
    }

**Comment by TheHolyWaffle** [comment]
I'm fine with you breaking older implementations. This project is not big
enough to worry about such thing in my opinion.

2015-03-07 13:43 GMT+01:00 Firedroide <notifications@github.com>:

**Comment by Firedroide** [comment]
Okay, thank you very much!

I'll still make a list of breaking changes so people know what has changed and what they'll have to change. I'll also keep the deprecated ChannelGroup#getChannelId() in, as the change was mostly cosmetic and it's just a simple getter ^^
