### ISSUE TITLE
Updating client description

### ISSUE THREAD

**Issue by TheRealDomm** [TheHolyWaffle/TeamSpeak-3-Java-API#352]
I just came up with the question if it is possible to set the client description without the need to rejoin so its get updated?

Actually I'm using the following method:

```
public void setDescription(Player player) {
    api.setCustomClientProperty(getClient(player).getDatabaseId(), ClientProperty.CLIENT_DESCRIPTION.name(), "Ingame Name: " + player.getName());
}
```

Thanks in advance.

**Comment by MemeEntwickler** [comment]
THis should work. But where is your Problem, does it never get set or only when you rejoin currently?

**Comment by TheRealDomm** [comment]
> This should work. But where is your Problem, does it never get set or only when you rejoin currently?

It gets set but only after a rejoin

**Comment by MemeEntwickler** [comment]
`api.editClient(client.getId(), Collections.singletonMap(ClientProperty.CLIENT_DESCRIPTION, "Desc Here"));`

This works for me :)

**Comment by rogermb** [comment]
Definitely don't use `setCustomClientProperty` for this. Custom properties are entirely separate from the regular client properties that you want to use.

@MemeEntwickler's `api.editClient(client.getId(), Collections.singletonMap(ClientProperty.CLIENT_DESCRIPTION, "Desc Here"));` code is what you're looking for.
