### ISSUE TITLE
I dont know

### ISSUE THREAD

**Issue by soulleon** [TheHolyWaffle/TeamSpeak-3-Java-API#353]
In a timer in which I query something every 2 minutes (where a client list is requested by TeamSpeak), it always crashes because of this client list. https://prnt.sc/r1vngs https://prnt.sc/r1vntf

**Comment by MemeEntwickler** [comment]
Try to only add the client into your array

**Comment by rogermb** [comment]
I'm pretty sure this is an old and solved issue anyway (likely discussed on Gitter), but just on the off chance that it isn't:
- Make sure the query is actually connected
- Use at least the newest release of the API. It might be better to just use the master branch on GitHub at the moment
- If you are using reconnect handlers, make sure that you are **only** using the `TS3Query` instance that we provide as an argument inside the `onConnect` method, i.e. make sure that no references to that `TS3Query` go into our out of that `onConnect` method
