### ISSUE TITLE
Problem with ClientLeaveEvent

### ISSUE THREAD

**Issue by Kaspek2480** [TheHolyWaffle/TeamSpeak-3-Java-API#354]
Something is wrong with ClientLeaveEvent. When i am using getInvokerUniqueId() from event it return me empty string..
My code:
`@Override
    public void onClientLeave(ClientLeaveEvent clientLeaveEvent) {
        String leaverUID = clientLeaveEvent.getInvokerUniqueId();
        System.out.println("Leaver: " + leaverUID + " " + clientLeaveEvent.getClientFromId() + " " + clientLeaveEvent.getClientTargetId() + " " + clientLeaveEvent.getClientId());`
Output: `Leaver:  1 0 64`
Could anyone help me?

**Comment by rogermb** [comment]
The invoker is the client that caused that event to happen. In the case of a `ClientLeaveEvent`, that is either the client who kicked / banned the client who left, or nobody if the client left on their own volition.

As the server query interface only sends us the client ID of the client who left - which becomes useless after the client has left the server - your only choice is to store the client's data somewhere and to retrieve it when the client leaves.

One way to do that would be to have a `Map<Integer, T>`, which uses the client ID as the key and whatever you want to store about the client (denoted of type "T" here) as the value. When the client joins the server, add their information to the map. If required, periodically update the value. And once the client leaves, retrieve (and simultaneously delete) the information from the map by calling `T somethingINeedToKnow = map.remove(e.getClientId());`.

I hope that helps 😄

**Comment by Kaspek2480** [comment]
> The invoker is the client that caused that event to happen. In the case of a `ClientLeaveEvent`, that is either the client who kicked / banned the client who left, or nobody if the client left on their own volition.
> 
> As the server query interface only sends us the client ID of the client who left - which becomes useless after the client has left the server - your only choice is to store the client's data somewhere and to retrieve it when the client leaves.
> 
> One way to do that would be to have a `Map<Integer, T>`, which uses the client ID as the key and whatever you want to store about the client (denoted of type "T" here) as the value. When the client joins the server, add their information to the map. If required, periodically update the value. And once the client leaves, retrieve (and simultaneously delete) the information from the map by calling `T somethingINeedToKnow = map.remove(e.getClientId());`.
> 
> I hope that helps 😄

Big thanks for answer, i will check it on my own
