### ISSUE TITLE
Problem with ClientLeaveEvent

### ISSUE THREAD

**Issue by Veqtive** [TheHolyWaffle/TeamSpeak-3-Java-API#358]
Hey there,

I'm having a bit of a problem with the ClientLeaveEvent. 
My plan is that if a staff member (currently only server admins) joins the teamspeak server, his/her own channel gets created and if he/she lefts it gets deleted.

The creating process works just fine. But the deletion process does not work. I have to get the channelid by its exact name which is not possible because I am not able to get the name of the user who just left. 

Is there any way I can get the clientname or do I have to rename the Channels to something else?

`			public void onClientJoin(ClientJoinEvent e) {
				int clientid = e.getClientId();
				String clientName = e.getClientNickname();
				ClientInfo info = Load.api.getClientInfo(clientid);
				int clientConnects = info.getTotalConnections();

				

				if(Load.api.getClientInfo(clientid).isInServerGroup(admin)) {
					String ChannelName = "Administration - #" + clientName;
					
					
					
					HashMap<ChannelProperty, String> channelcreate = new HashMap<ChannelProperty, String>();
					channelcreate.put(ChannelProperty.CHANNEL_FLAG_PERMANENT, "1");
					channelcreate.put(ChannelProperty.CHANNEL_MAXCLIENTS, "0");
					channelcreate.put(ChannelProperty.CPID, adminbereich);
					Load.asyncapi.createChannel(ChannelName, channelcreate);
					
					int channel = Load.api.getChannelByNameExact(ChannelName, true).getId();

					Load.asyncapi.addChannelPermission(channel, "i_channel_needed_subscribe_power", 75);
					Load.asyncapi.addChannelPermission(channel, "i_channel_needed_delete_power", 75);
					Load.asyncapi.addChannelPermission(channel, "i_channel_needed_modify_power", 75);
					Load.asyncapi.addChannelPermission(channel, "i_channel_needed_join_power", 75);

				} else {
					return;
				}`

**Comment by DominicFresh** [comment]
Hello!
You can make, for example, an lets say ArrayList and put in the name of the admin / staff.
On leave you can check if the list has the entry y voilà you have your result.

Greetings Dominic.

**Comment by Veqtive** [comment]
Hey thanks, works just fine. But I tried to change the way the channel gets modified. I no longer want the channel to be deleted but to be changed to a temporary channel. I used Channelproperty.CHANNEL_FLAG_TEMPORARY, "1"); but it throws the error:
> [2020-04-24 01:24:59.445] [SEVERE] TS3 command error: {msg=invalid parameter, id=1538}

What am I doing wrong? My code so far:

			`public void onClientLeave(ClientLeaveEvent e) {
				System.out.println("LeaveEvent");
				int clientid = e.getClientId();
				if(online.containsKey(clientid)) {
					String clientName = online.get(clientid);
					System.out.println(clientName);
					String ChannelName = "Administration - " + clientName;
					int channel = Load.api.getChannelByNameExact(ChannelName, true).getId();
					System.out.println("Test1");
					Map<ChannelProperty, String> channeledit = new HashMap<>();
					System.out.println("Test2");
					//channeledit.put(ChannelProperty.CHANNEL_FLAG_PERMANENT, "0");
					System.out.println("Test3");
					channeledit.put(ChannelProperty.CHANNEL_FLAG_TEMPORARY, "1");
					System.out.println("Test4");
					Load.asyncapi.editChannel(channel, channeledit);
					System.out.println("Test5");
				} else {
					System.out.println("[INFO] Teammitglied hat keinen Channel");
				}

				
			} `
