### ISSUE TITLE
SpacerCreation fails

### ISSUE THREAD

**Issue by DominicFresh** [TheHolyWaffle/TeamSpeak-3-Java-API#359]
**Hello my mates!**

I am currently trying to develop a TeamSpeak³ Bot with Java.
As I have finished with the basic stuff, like little commands, I have encountered an problem.
I am trying to create an spacer with the name "BotStatus : Online". As it is an temporary Channel
it will get automatically deleted as soon as the bot starts. So far is no problem, besides the name of the channel. It shows "[cspacer34] BotStatus : Online", but the "cpacer" "markup" isn't working. 

Screenshots:
[https://i.imgur.com/824y7yr.png](url) | TeamSpeak Channel Name

Code:

`
Map<ChannelProperty, String> property = new HashMap<ChannelProperty, String>();
        property.put(ChannelProperty.CHANNEL_FLAG_TEMPORARY, "1");
        property.put(ChannelProperty.CHANNEL_ORDER, "40");
        ChannelInfo channelInfo =
 Load.api.getChannelInfo(Load.api.createChannel("[cpacer12121] Botstatus | Online", property));
        Load.api.addChannelPermission(channelInfo.getId(), "i_channel_needed_join_power", 65);
        Load.api.addChannelPermission(channelInfo.getId(), "i_channel_needed_delete_power", 65);
        Load.api.addChannelPermission(channelInfo.getId(), "i_channel_description_view_power", 10);
        api.editChannel(channelInfo.getId(), property);
`

Can anybody please help me?

Greetings Dominic

**Comment by rogermb** [comment]
Hi! Sorry for taking so long to respond. Real life has been quite busy 😅 

Your issue seems to boil down to a typo: It should be [c**s**pacer12121] instead of [cpacer12121].
I confirmed that this works, at least on my machine and test server 😄 

Again, sorry for taking so long to reply!

**Comment by DominicFresh** [comment]
Hi!

I think something is almost wrong.

https://i.imgur.com/gwuLPpI.png
https://i.imgur.com/FAXt09c.png

**Comment by rogermb** [comment]
Spacer channels may not be temporary. You can try this yourself in your own TS3 client.

```java
Map<ChannelProperty, String> property = new HashMap<>();
property.put(ChannelProperty.CHANNEL_ORDER, "5");
property.put(ChannelProperty.CHANNEL_FLAG_PERMANENT, "1");
int cid = api.createChannel("[cspacer12121] Botstatus | Online", property);
System.out.println("Created channel " + cid);
```
works just fine on my machine and test server.

**Comment by DominicFresh** [comment]
thanks
