### ISSUE TITLE
Registration bot

### ISSUE THREAD

**Issue by BEJUdev** [TheHolyWaffle/TeamSpeak-3-Java-API#360]
Hello I have a problem I wanted to do a registration bot only is a small problem. Because the first part is done and the rest is not.
`Load.api.registerAllEvents();
        Load.api.addTS3Listeners(new TS3Listener() {
            @Override
            public void onTextMessage(TextMessageEvent e) {

                Client c = Load.api.getClientInfo(e.getInvokerId());

                if (!c.isInServerGroup(21) && !c.isInServerGroup(22)) {
                    if (e.getMessage().equalsIgnoreCase("M")) {
                        Load.api.addClientToServerGroup(21, c.getDatabaseId());
                    } else if (e.getMessage().equalsIgnoreCase("K")) {
                        Load.api.addClientToServerGroup(22, c.getDatabaseId());
                    } else {
                        Load.api.sendPrivateMessage(c.getId(), "Podaj prawidłową płeć");
                    }
                }
                Load.api.sendPrivateMessage(c.getId(),"Podaj rok urodzenia(rrrr)");
                if (!e.getMessage().matches("[0-9]+")) {
                    Load.api.sendPrivateMessage(c.getId(), "Podaj liczbe cwelu <3");
                }
                int ob=Integer.parseInt(e.getMessage())-2020;
                if(ob==0){

                }else if(ob>9&&ob<11){
                    Load.api.addClientToServerGroup(24,c.getDatabaseId());
                }else if(ob>12&&ob<13){
                    Load.api.addClientToServerGroup(25,c.getDatabaseId());
                }else if(ob>14&&ob<15){
                    Load.api.addClientToServerGroup(26,c.getDatabaseId());
                }else if(ob>16&&ob<17){
                    Load.api.addClientToServerGroup(27,c.getDatabaseId());
                }else if(ob>18){
                    Load.api.addClientToServerGroup(28,c.getDatabaseId());
                }

                if (!c.isInServerGroup(30) && !c.isInServerGroup(31) && !c.isInServerGroup(32) && !c.isInServerGroup(47) && !c.isInServerGroup(33) && !c.isInServerGroup(34) && !c.isInServerGroup(35) && !c.isInServerGroup(36) && !c.isInServerGroup(37) && !c.isInServerGroup(38) && !c.isInServerGroup(41)&& !c.isInServerGroup(40) || !c.isInServerGroup(42) || !c.isInServerGroup(43) || !c.isInServerGroup(44)) {
                    Load.api.sendPrivateMessage(c.getId(), "W jakim województwie mieszkasz?");
                    Load.api.sendPrivateMessage(c.getId(), "dolnośląskie-1");
                    Load.api.sendPrivateMessage(c.getId(), "kujawsko-pomorskie-2");
                    Load.api.sendPrivateMessage(c.getId(), "lubelskie-3");
                    Load.api.sendPrivateMessage(c.getId(), "lubuskie-4");
                    Load.api.sendPrivateMessage(c.getId(), "łódzkie-5");
                    Load.api.sendPrivateMessage(c.getId(), "małopolskie-6");
                    Load.api.sendPrivateMessage(c.getId(), "mazowieckie-7");
                    Load.api.sendPrivateMessage(c.getId(), "opolskie-8");
                    Load.api.sendPrivateMessage(c.getId(), "podkarpackie-9");
                    Load.api.sendPrivateMessage(c.getId(), "podlaskie-10");
                    Load.api.sendPrivateMessage(c.getId(), "pomorskie-11");
                    Load.api.sendPrivateMessage(c.getId(), "śląskie-12");
                    Load.api.sendPrivateMessage(c.getId(), "świętokrzyskie-13");
                    Load.api.sendPrivateMessage(c.getId(), "warmińsko-mazurskie-14");
                    Load.api.sendPrivateMessage(c.getId(), "wielkopolskie-15");
                    Load.api.sendPrivateMessage(c.getId(), "zachodniopomorskie-16");
                    Load.api.sendPrivateMessage(c.getId(), "nieznane-0");

                    String woj = e.getMessage();
                    int woj1;

                    try {
                        woj1 = Integer.parseInt(woj);
                    } catch (NumberFormatException e1) {
                        woj1 = 0;
                    }

                    switch (woj1) {
                        case 1:
                            Load.api.addClientToServerGroup(30, c.getDatabaseId());
                            break;
                        case 2:
                            Load.api.addClientToServerGroup(31, c.getDatabaseId());
                            break;
                        case 3:
                            Load.api.addClientToServerGroup(32, c.getDatabaseId());
                            break;
                        case 4:
                            Load.api.addClientToServerGroup(47, c.getDatabaseId());
                            break;
                        case 5:
                            Load.api.addClientToServerGroup(33, c.getDatabaseId());
                            break;
                        case 6:
                            Load.api.addClientToServerGroup(34, c.getDatabaseId());
                            break;
                        case 7:
                            Load.api.addClientToServerGroup(35, c.getDatabaseId());
                            break;
                        case 8:
                            Load.api.addClientToServerGroup(36, c.getDatabaseId());
                            break;
                        case 9:
                            Load.api.addClientToServerGroup(37, c.getDatabaseId());
                            break;
                        case 10:
                            Load.api.addClientToServerGroup(38, c.getDatabaseId());
                            break;
                        case 11:
                            Load.api.addClientToServerGroup(39, c.getDatabaseId());
                            break;
                        case 12:
                            Load.api.addClientToServerGroup(40, c.getDatabaseId());
                            break;
                        case 13:
                            Load.api.addClientToServerGroup(41, c.getDatabaseId());
                            break;
                        case 14:
                            Load.api.addClientToServerGroup(42, c.getDatabaseId());
                            break;
                        case 15:
                            Load.api.addClientToServerGroup(43, c.getDatabaseId());
                            break;
                        case 16:
                            Load.api.addClientToServerGroup(44, c.getDatabaseId());
                            break;
                        case 0:
                            //  Load.api.addClientToServerGroup(44, c.getDatabaseId());
                            break;
                        default:
                            return;
                    }
                }
                if (!c.isInServerGroup(13) && !c.isInServerGroup(14) && !c.isInServerGroup(11) && !c.isInServerGroup(12)) {
                    Load.api.addClientToServerGroup(13, c.getDatabaseId());
                    Load.api.addClientToServerGroup(14, c.getDatabaseId());
                    Load.api.addClientToServerGroup(11, c.getDatabaseId());
                    Load.api.addClientToServerGroup(29, c.getDatabaseId());
                }

            }

            @Override
            public void onClientJoin(ClientJoinEvent clientJoinEvent) {
                Client c = Load.api.getClientInfo(clientJoinEvent.getClientId());
                if (!c.isInServerGroup(21)||!c.isInServerGroup(22)) {
                    Load.api.sendPrivateMessage(c.getId(), "Witaj," + c.getNickname() + "nasz system wykrył, że nie posiadasz uprawnień.");
                    Load.api.sendPrivateMessage(c.getId(), "Nasza aplikacja przystąpi do automatycznej rejestracji.");
                    Load.api.sendPrivateMessage(c.getId(), "Informujemy, że na każde pytanie musisz odpowiedzieć zgodnie z prawdą.");
                    Load.api.sendPrivateMessage(c.getId(), "Wybierz swoją płeć:" +
                            "Jeżeli jesteś Mężczyzną wpisz [b]m[/b] " +
                            "Jeżeli jesteś Kobietą wpisz [b]k[/b]");
                }
            }`
Only this is done correctly
`if (!c.isInServerGroup(21) && !c.isInServerGroup(22)) {
                    if (e.getMessage().equalsIgnoreCase("M")) {
                        Load.api.addClientToServerGroup(21, c.getDatabaseId());
                    } else if (e.getMessage().equalsIgnoreCase("K")) {
                        Load.api.addClientToServerGroup(22, c.getDatabaseId());
                    } else {
                        Load.api.sendPrivateMessage(c.getId(), "Podaj prawidłową płeć");
                    }`
the rest goes automatically regardless of everything

**Comment by BEJUdev** [comment]
[2020-04-23 23:01:22.620] [SEVERE] Command sendtextmessage was not answered in time.
[2020-04-23 23:01:22.623] [SEVERE] Command sendtextmessage was not answered in time.
[2020-04-23 23:01:22.631] [SEVERE] Command clientinfo was not answered in time.
[2020-04-23 23:01:22.635] [SEVERE] Command clientinfo was not answered in time.

**Comment by rogermb** [comment]
I think we already discussed and solved this on Gitter. Please feel free to re-open this issue if my memory deceives me.
