### ISSUE TITLE
get Channel Parent

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#363]
Hey,

can i get the Parent Channel white the ChannelID?

**Comment by rogermb** [comment]
Hi!

Yes, you can use [`.getParentChannelId()`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/68807a93de23cd3fde1efdf36c29823992fd72ce/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/ChannelBase.java#L42-L44) on any channel object, which you can get by calling methods like [`TS3Api#getChannels`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/68807a93de23cd3fde1efdf36c29823992fd72ce/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1860-L1872) or [`TS3Api#getChannelInfo`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/68807a93de23cd3fde1efdf36c29823992fd72ce/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1824-L1840).

**Comment by CheeseTastisch** [comment]
Ok,
what is, if the Channel hasn't any Parent?

**Comment by rogermb** [comment]
In that case, `.getParentChannelId()` will return 0.
