### ISSUE TITLE
informations on client disconnect

### ISSUE THREAD

**Issue by LUF3N** [TheHolyWaffle/TeamSpeak-3-Java-API#364]
Hey,
is there a way to get informations of an disconnect?
I want to check if a client disconnect is a intended or a timeout.

Thanks for reply! :)

**Comment by yannicklamprecht** [comment]
https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/ClientLeaveEvent.java

https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/68807a93de23cd3fde1efdf36c29823992fd72ce/src/main/java/com/github/theholywaffle/teamspeak3/api/event/BaseEvent.java#L93-L116


The reason ID gives you the reason why the client disconnected.

**Comment by LUF3N** [comment]
Thank you very much! Saved my day ;D
