### ISSUE TITLE
How to make my own Version

### ISSUE THREAD

**Issue by pluginyaml** [TheHolyWaffle/TeamSpeak-3-Java-API#365]
I want to do my own version with this API (Connecting to a Database and create Methods in Client to get Informations from the Database)
How do i do that? I downloaded the Source-Code, opened the Folder with the pom-xml, but it doesnt work if i want to use it in my Java-Project

**Comment by Tumbledore** [comment]
Hey, the Answer to that is quite easy:
if you are using Maven to Build your Project (my Preferred Way) use:
```
<dependency>
    <groupId>com.github.theholywaffle</groupId>
    <artifactId>teamspeak3-api</artifactId>
    <version>...</version>
</dependency>
```
otherwise download the Jar and put it into the Classpath.
This is also described in the ReadMe ;)
