### ISSUE TITLE
Question about implementation of ClientInfo#getDefaultChannel()

### ISSUE THREAD

**Issue by Firedroide** [TheHolyWaffle/TeamSpeak-3-Java-API#37]
Implemented [here](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/ClientInfo.java#L98-99).

Why is it that we're only taking the first integer from the default channel property and turning that into an integer? I stumbled upon that while more or less throwing out the StringUtil parsing methods that should be implemented in the Wrapper class.

**Comment by TheHolyWaffle** [comment]
Sorry, can't remember much from what I did initially.

**Comment by Firedroide** [comment]
Okay, figured it out.

For some reason, TeamSpeak thinks it's a good idea to prefix this channel id with a forward slash. -.-

It's stuff like this that makes me want to switch to Mumble. An up-to-date, feature-complete and well-documented protocol, as well as open source code that is actively being worked on.

**Comment by TheHolyWaffle** [comment]
You're right, the ts3query docs haven't been updated since 2012. The only
mentioned the query changes in the changelog since then.

2015-03-13 16:51 GMT+01:00 Roger Baumgartner <notifications@github.com>:
