### ISSUE TITLE
Event Priority

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#371]
Is ther an system, whitch Event ist first called or is this random?
Can i change this Priority?

**Comment by rogermb** [comment]
Events are always called in the exact order that they are sent by the TS3 server. There is no way to prioritize some events over others.

For each individual event listener object, all of these events are called sequentially. Your event listener returning from event N *happens-before* your event listener getting called for event N+1.

Multiple different event listener objects are **not** synchronized with each other, though, and can run in parallel.
