### ISSUE TITLE
Moved by ClientMovedEvent

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#372]
Is there any way, to geht how moved the client in the ClientMovedEvent?

**Comment by TAXSET** [comment]
If I understand your question correctly: 

I don't think the ClientMovedEvent was designed to be used that way. It fires whenever a client "moves" to another channel (eg. double clicks on a channel). You can try to get the instigator/invoker of the event who might be the client who moved another client.

Please bear in mind that all of the above is just guesswork as I've never tried to do what you want to achieve.

**Comment by CheeseTastisch** [comment]
Thanks for your answer. I will try it whit the invoker

**Comment by CheeseTastisch** [comment]
I tryed it out now.
I don't know why, but the InvokerName, ... aren't set.

Any other Idees?

**Comment by TAXSET** [comment]
I'm afraid I don't have any other ideas. Sorry.

**Comment by rogermb** [comment]
If the client moved on their own, `getReasonId()` returns 0 and the invoker fields are unset (-1, empty string, whatever).

If the client was moved by another client, `getReasonId()` returns a non-zero value and the invoker fields let you figure out which client (if any) caused the other client to move. There's some documentation on known reason IDs in the Javadoc of `getReasonId()`
