### ISSUE TITLE
TextMessage

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#375]
Hey,
if i try to send a message to the bot, there is an message:
`This ServerQuery client did not register for the private text message event using "servernotifyregister event=textprivate". The text message was not received.`

I have used the `api.registerAllEvents();` method.
Is there any way to fix this?

And there is also the message:
`Chat partner disconnected out of view.`
how fix this?

**Comment by TAXSET** [comment]
Never had the first issue, but I think I can help with the second one as this caused some confusion on a project of mine:

If the chat window displays the `Chat partner disconnected out of view.` message, it means that the Query has disconnected after the chat window was opened by the client. To fix this, close the chat window and send the client a new message via your bot.

Every time your bot connects to the server it gets a new ID, therefore, if a client has an old chat window open and types a message, that message is sent to an outdated client ID of the query and therefore can not be received.

**Comment by crackscout123** [comment]
How did you fixed the first issue?
