### ISSUE TITLE
Socket Timeout Exception: Read timed out

### ISSUE THREAD

**Issue by MartinWagenbach** [TheHolyWaffle/TeamSpeak-3-Java-API#377]
Guten Morgen,

ich habe das Problem, dass mein Bot nach einer gewissen Zeit die Verbindung verliert.

Mit freundlichem Gruß,
Martin Wagenbach

**Fehlermeldung**

https://pastebin.com/uBK80vDk

**Code**

_de.mimnu.daddeleckets3bot.support.SupportChannel:_ https://pastebin.com/HvZdHZ1D

_de.mimnu.daddeleckets3bot.afkmover.AfkMover:_ https://pastebin.com/Hm0LBkix

**Comment by Kakifrucht** [comment]
That's simply a timeout and doesn't give any further information about what went wrong. If you were connected on localhost a timeout really shouldn't happen, but still could.

Best thing you can do is add reconnect listeners to your bot to stop the Timer tasks after a disconnect happens, and after a successful reconnect restart them.

See this example: https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/example/ReconnectExample.java

**Comment by Likqez** [comment]
Also provide code snippets as a gisthub [gist](https://gist.github.com) so it does not invalidate after time. The pastebin links dont work anymore :)
