### ISSUE TITLE
Hard Stop

### ISSUE THREAD

**Issue by EzxD** [TheHolyWaffle/TeamSpeak-3-Java-API#379]
Hello
is there a way to har stop the api? Like a restart od the java application
This doesn´t work for me:
```java
      ts3Api.unregisterAllEvents();
      ts3Api.logout();
      ts3Query.exit();
```

**Comment by Kakifrucht** [comment]
``ts3Query.exit()`` should do it and works on my end. Are you sure you have shut down any other active threads you spun up, like task schedulers?

**Comment by EzxD** [comment]
Ah yeah thanks
