### ISSUE TITLE
Successfully Logedin?

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#382]
Hey,

if i use
`api.login("username", "password");`
is there any method to check, if the login wus successfully?

**Comment by RMrenex** [comment]
Hi, If the connection is not successful you will have an error

**Comment by CheeseTastisch** [comment]
Yes, ther is an error, but you can't catch it whit and try-catch.

**Comment by RMrenex** [comment]
If why we couldn't?

```java
try {
     api.login("username", "password");
 } catch(TS3CommandFailedException e){
     your code ...
}
```

**Comment by CheeseTastisch** [comment]
they don't throw an Exeption.
I tryed it whit 
`
try {
     api.login("username", "password");
 } catch(Exception e){
     e.printStackTrace()
}
`

but ther wasn't any output at the console.

**Comment by RMrenex** [comment]
What idea do you use?

**Comment by CheeseTastisch** [comment]
i use intelij but I executed it whit 
`java -jar tsbot.jar`
in the Windows-CMD

**Comment by RMrenex** [comment]
It's your problem normally he should give you a mistake.
![Capture](https://user-images.githubusercontent.com/49162612/100254145-3b0d3380-2f42-11eb-9ad7-08df8e1d69ff.JPG)

**Comment by CheeseTastisch** [comment]
But it dosn't give me a mistake!
Becouse of this, i asked if there is any other way to go.

**Comment by RMrenex** [comment]
Unfortunately I don't think there is another solution. When you run on intellij you have no error in the console?

**Comment by CheeseTastisch** [comment]
> in the Windows-CMD

not in IntelliJ!

**Comment by rogermb** [comment]
Hi. In old versions of this API, commands used to return a `boolean` to indicate whether they succeeded or failed, which wasn't the best design as it didn't help you figure out what exactly went wrong. The `boolean` return values were replaced with throwing exceptions in version 1.1.0. Make sure the API version you're using is up to date @CheeseTastisch.

**Comment by CheeseTastisch** [comment]
Thanks! I have used the 1.0.14 and don't know, that the 1.2.0 is allrady out.
