### ISSUE TITLE
TeamSpeak 3 ServerQuery interface

### ISSUE THREAD

**Issue by CheeseTastisch** [TheHolyWaffle/TeamSpeak-3-Java-API#383]
Every time is start a .jar file, with the TeamSpeak-API, it shows they TeamSpeak 3 ServerQuery interface:
Hier is an screen:
![Screenshot](https://user-images.githubusercontent.com/56408700/100710082-762ebd00-33af-11eb-9f95-43d158250312.PNG)
How to fix this?

**Comment by PrzemoVi** [comment]
Show your code
