### ISSUE TITLE
Get client ping

### ISSUE THREAD

**Issue by lehmenkuehler** [TheHolyWaffle/TeamSpeak-3-Java-API#385]
Is there a way to read a client's ping? There are getter functions for almost everything in the Client class but oddly not for the ping...

**Comment by rogermb** [comment]
Hi. Sorry about the insane delay, I haven't really had time for any open-source work in almost a year. Feel free to ignore this issue if you no longer care about this issue.

No, from what I've been able to gather, the TeamSpeak3 Server Query interface currently doesn't offer any way to query the client's ping. This is a limitation of the Server Query interface and not of this API.
