### ISSUE TITLE
Get server group by its name

### ISSUE THREAD

**Issue by MitoCodeGithub** [TheHolyWaffle/TeamSpeak-3-Java-API#387]
Hello there,

how can I get the server group (e.g. the server group ID) by its name?

Thank you,
Mito

**Comment by rogermb** [comment]
There is no server query command to do that directly, but you can use `TS3Api#getServerGroups` to get a list of all server groups, and then just iterate over that list until you find a server group whose name matches what you're looking for.

**Comment by MitoCodeGithub** [comment]
Hello again,

I've the following code:
`List<ServerGroup> servergroups = new ArrayList<>();
servergroups.addAll(ts3Api.getServerGroups());`

And for example server group id 1 returns:
**{iconid=0, savedb=0, sortid=0, name=Guest Server Query, n_member_removep=0, sgid=1, type=2, n_member_addp=0, namemode=0, n_modifyp=100}**

How can I iterate to the name? Can you send me an example code? It would help me a lot.

Thank you,
Mito

**Comment by astrolamb-gaming** [comment]
Probably best to ask questions in the gitter chat: https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API
To answer your question though, you can use the ServerGroup#getName() function.
