### ISSUE TITLE
Cant get client information on client leave

### ISSUE THREAD

**Issue by NewJavaDeveloper** [TheHolyWaffle/TeamSpeak-3-Java-API#388]
Hey!

I would like to edit a channel when a client who obtains a specified server group leaves the server.
I am not able to get some required client information like the clientID, clientDbID or invokerName/InvokerUID/InvokerID.
Every "invoker stuff" returns "0" or "-1" or something else that is not helpful.

Here is my code:
https://pastebin.com/cJjCd6cB

And here is my log:
https://pastebin.com/xVXymAHw

I hope someone can help me.
How to fix these problems?

**Comment by rogermb** [comment]
See [this FAQ entry](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#why-does-clientleaveevent-only-provide-getclientid-but-not-getclientuniqueid-or-getclientnickname) as well [this FAQ entry](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#what-is-the-difference-between-an-events-client-and-invoker). Alternatively, search for issues including [ClientLeaveEvent](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues?q=is%3Aissue+ClientLeaveEvent).
