### ISSUE TITLE
onChannelDeleted not firing?

### ISSUE THREAD

**Issue by Kakifrucht** [TheHolyWaffle/TeamSpeak-3-Java-API#39]
Hi, I'm not sure if I am missing something, but I used TS3Api.registerAllEvents() and the api works fine generally, however the onChannelDeleted event never fires. Same applies to onChannelCreate event.

**Comment by Firedroide** [comment]
Sorry for the long delay, I'm puzzled by this report. At least on my end, everything works.

Could you tell me which version of the API you are using? There have been some changes to TS3Api.registerAllEvents, which is why I need to know.

**Comment by Kakifrucht** [comment]
I don't exactly know how to get the version number from the API?
I know for sure that there were quite some commits, many by you, so I'm not on the newest build.

**Comment by Firedroide** [comment]
Ah, so you're on the latest release then. I think in that release, the register method was still kinda broken. Basically, it didn't really register all server notifications for all events, so onChannelCreate and onChannelDeleted would never fire. (note to self: "create" but "deleted"? ...)

As there's no current release and I don't assume you want to switch off maven as a version control system, you'll need to implement some kind of workaround. I've gone ahead and thrown it together real quick for you.

	public void registerAllEvents(TS3Api api) {
		api.registerEvent(TS3EventType.SERVER);
		api.registerEvent(TS3EventType.TEXT_SERVER);
		api.registerEvent(TS3EventType.CHANNEL, 0);
		api.registerEvent(TS3EventType.TEXT_CHANNEL, 0);
		api.registerEvent(TS3EventType.TEXT_PRIVATE);
	}

Sorry again for the long delay, it was a long week for me ^^

**Comment by Kakifrucht** [comment]
You don't have to apologize for maintaining this project ;)

Thanks, but I actually currently don't need the event. I just noticed that it wouldn't fire, I already worked around my issue I guess. I'll wait for a compiled fixed build.

**Comment by Firedroide** [comment]
Okay :D

I'll go ahead and close this issue then.
