### ISSUE TITLE
Publish version including SSH support to maven central

### ISSUE THREAD

**Issue by chamelopi** [TheHolyWaffle/TeamSpeak-3-Java-API#391]
Hi,

could you please publish a version that supports SSH connections to maven central repository? The newest version that is currently available over there does not support `setProtocol` unfortunately, and thus does not work with servers that have disabled the legacy telnet-based query interface.

Your library seems great, I would appreciate not having to build it locally myself though :D

**Comment by astrolamb-gaming** [comment]
Yes, this would be great. The SSH commit was ages ago https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/commit/4030271905bbee72246a371b3009615acc075b32

**Comment by rogermb** [comment]
I agree, a new release was long overdue. Here's [v1.3.0](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/releases/tag/v1.3.0) 😄 

The update should be automatically uploaded to Maven Central shortly.
