### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by TruaYT** [TheHolyWaffle/TeamSpeak-3-Java-API#394]
Heyy
i try to start the bot..

https://i.imgur.com/FjMt9eM.png <. The Error

pom.xml <- https://i.imgur.com/iRtwVBd.png 

https://pastebin.com/kudjUFvu <- Main

what i make wrong?

**Comment by yannicklamprecht** [comment]
1. scope provided is likely not what you want. Provided means that you provide the dependency separately.
2. Instead use scope compile and the maven shade plugin or maven assembly plugin
