### ISSUE TITLE
Install on Linux

### ISSUE THREAD

**Issue by DG5S** [TheHolyWaffle/TeamSpeak-3-Java-API#397]
Hey, I have a Linux server with my Teamspeak on. 
How can I install the ts3 bot on them? 
Is there also a way to start and stop the bot?

**Comment by Tumbledore** [comment]
Hey Mate, i think you missunderstood something here. 
this is not a working Bot to just install, this is an Application Programming Interface written and useable in the Language Java.
With this you could write your own Bot

**Comment by DG5S** [comment]
Hey, I understood it. I have to programm my own Bot with api, I know it. But how can I run a java Bot on Linux?

**Comment by Tumbledore** [comment]
You install Java JRE on your Linux System, create a JAR of your Bot, transfer it on your Linux Machine and start it there?

**Comment by DG5S** [comment]
okay thanks, Im new in this theme. I try it
