### ISSUE TITLE
Issues setting Client Server Groups

### ISSUE THREAD

**Issue by Tythus** [TheHolyWaffle/TeamSpeak-3-Java-API#40]
I am a bit cinfused I'm getting a [DEBUG] [clientedit] < error id=1538 msg=invalid\sparameter
[DEBUG] [SEVERE] [ERROR] {msg=invalid parameter, id=1538} error and as far as I can tell I am inputting the correct hasmap here is the code in effect.

api.editClient(e.getClientId(), ClientValues(ClientProperty.CLIENT_SERVERGROUPS, "8"));

protected HashMap<ClientProperty, String> ClientValues(ClientProperty property,
			String value) {
		HashMap<ClientProperty, String> hm = new HashMap<ClientProperty,String>();
		hm.put(property, value);
		return hm;
	}

**Comment by Firedroide** [comment]
>  as far as I can tell I am inputting the correct hasmap

Yes and no ^^
Unfortunately, TS3Api.editClient or even TS3Api.updateClient can only be used with very few ClientProperties. The server groups property is not one of them.

Instead, you should use the actual API methods for server groups.

First of all, assuming you know the client's **database** ID, you can use TS3API.getServerGroupsByClientId(clientDatabaseId) to get a list of all server groups the client is in (yes, a client can be in multiple server groups). Using the normal *session* ID won't work, you need to use the client's database ID (Client.getDatabaseId() or ClientInfo.getDatabaseId()).

Then, remove the client from all of these server groups by calling TS3Api.removeClientFromServerGroup(serverGroupId, clientDatabaseId). Then, finally, you can call TS3Api.addClientToServerGroup(serverGroupId, clientDatabaseId) to add the client to the server group. Again, client **database** ID in both methods.

I'm afraid this seems so complicated, but this API directly encapsulates the commands offered by the TeamSpeak server query interface to expose as many functions as possible to our users.

**Comment by Tythus** [comment]
riiiggghtt that makes sense it ould be nice if you could have some kind of pointer on hat i can actually edit ^_^' although thankyou for the help

**Comment by Tythus** [comment]
hmm I have having another issue ^_^' I can't seem to grab a leaving users UID is there any method you can think on that?

**Comment by Firedroide** [comment]
Already answered in #38. The UID is not transmitted, therefore we cannot give it to you. Best thing is to have a Map set up. When a client joins, map his client ID to his UID, when he leaves, remove the entry with his client ID (thereby getting his UID).

As far as documentation goes: It's actually documented [here](http://ci.stutzfam.ch/job/TeamSpeak-3-Java-API/javadoc/com/github/theholywaffle/teamspeak3/TS3Api.html#editClient-int-java.util.Map-). We hadn't had the javadocs at the time of the last release, though. So, sorry for the inconvenience.

**Comment by Tythus** [comment]
Yeah I figured that was the method I would have to go down. The only thing I wwould like to add is if you could have it on the property editors just a list of properties that it can't actually edit would save so much confusion.

**Comment by Firedroide** [comment]
As I already mentioned, documentation has already been added to this method.
