### ISSUE TITLE
TS3Api#renameServerGroup() returns invalid group ID error

### ISSUE THREAD

**Issue by astrolamb-gaming** [TheHolyWaffle/TeamSpeak-3-Java-API#401]
```
            List<ServerGroup> serverGroups = api.getServerGroups();
            System.out.println("Beginning for loop over Server groups");
            for (ServerGroup group : serverGroups) {
                int id = group.getId();
                if (group.getName().equals("GroupNameHere")) {
                        try {
                            System.out.print(group);
                            api.renameServerGroup(group, "NewGroupName");                  /// Line 8
                            //api.renameServerGroup(id, "NewGroupName");                      /// Line 9
                            //api.renameServerGroup(group.getId(), "NewGroupName");    /// Line 10
                        } catch (TS3CommandFailedException e) {
                            System.out.println("invalid group ID: " + group.getName());
                        }
             }
```

Given the above code, `api.renameServerGroup(group, "NewGroupName")` throws an invalid group ID error.

If I comment out line 8, and uncomment line 9, no errors are thrown.
Similarly if I comment out line 9 and uncomment line 10, no errors.

I was having a further issue where even with the int version of the function, my code would throw an exception, but then I realized there could be other errors instead of just the invalid group ID error. So I removed the try-catch, which dutifully caused an invalid group ID error with line 8, but caused no issues with lines 9 or 10. I replaced the try-catch, and since then have been unable to replicate exceptions for lines 9 and 10. So, not sure what that was about.

Regardless, the ServerGroup version of `api.renameServerGroup()` continues to throw an invalid group ID error.
I have checked that the group's sgid is correct by manually comparing the sgid printed with the group's ID on teamspeak.

**Comment by Shadow-Devil** [comment]
The TS3Api references the Async API:
```	
public void renameServerGroup(ServerGroup serverGroup, String name) {
	asyncApi.renameServerGroup(serverGroup, name).getUninterruptibly();
}
```
and there the renameServerGroup calls the renameChannelGroup method, not the renameServerGroup:
```
public CommandFuture<Void> renameServerGroup(ServerGroup serverGroup, String name) {
	return renameChannelGroup(serverGroup.getId(), name);
}
```

**Comment by rogermb** [comment]
Ah, good catch, I hadn't even noticed! Thank you very much for finding and fixing the issue @Shadow-Devil 😄
