### ISSUE TITLE
api.getServerGroups().get(10).getName() returns wrong GroupName

### ISSUE THREAD

**Issue by qeinz** [TheHolyWaffle/TeamSpeak-3-Java-API#407]
For whatever reason I have to calculate the GroupID which the client has - 4 and then query the Groupname with the new number, so I then get the associated name.

Is this an error on my part?

**Comment by astrolamb-gaming** [comment]
So I _think_ this is what's going wrong:
`api.getServerGroups()` returns a list. The `get()` function on a list gets the item at the specified location in the list, not the servergroup with the specified number. So, assuming the servergroup of interest has an ID of 10, you're trying to get the 10th item in the list, which probably does not correlate to the ID of the servergroup. What you might want to do is iterate over the list to find the servergroup with the desired ID:
```
ArrayList<ServerGroup> groups = api.getServerGroups();
for (ServerGroup g : groups) {
   if (g.getId() == 10) { // Could also check against the name directly if you want
      // do whatever
   }
}
```

**Comment by astrolamb-gaming** [comment]
Also for questions like this I recommend using gitter [repository chat](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API)

**Comment by qeinz** [comment]
Thx so much.
