### ISSUE TITLE
[Dependency] Dependency org.bouncycastle:bcprov-jdk15on

### ISSUE THREAD

**Issue by FlorianWip** [TheHolyWaffle/TeamSpeak-3-Java-API#414]
Your dependency org.bouncycastle:bcprov-jdk15on:1.68 contains a vulnerability (https://devhub.checkmarx.com/cve-details/Cxa9261daf-3755/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea). Is it possible to upgrade to 1.69 or later?

**Comment by rogermb** [comment]
Hi @FlorianWip!

Thanks for bringing this to our attention. We've updated our dependency on SSHJ (which included the transitive dependency on the vulnerable version of BouncyCastle) and have released a new version of the API that includes the fix, v1.3.1.

Cheers 🎉
