### ISSUE TITLE
is there a way to clear avatar from client

### ISSUE THREAD

**Issue by qeinz** [TheHolyWaffle/TeamSpeak-3-Java-API#417]
is there a way to clear an avatar from a client, i know there is a way to get the current avatar, but did not find a way to clear this

**Comment by rogermb** [comment]
Hi @qeinz 

As far as I'm aware, there is no way to modify a client's avatar using a server query.

This appears to be a limitation of the TS3 server query interface itself, see [this thread](https://forum.teamspeak.com/threads/120318-Set-avatar-of-user-via-server-query) on the TS3 forum 🙂

**Comment by qeinz** [comment]
hm okay, cuz i saw the option "delete" in YATQA
