### ISSUE TITLE
how to add query login and get login data

### ISSUE THREAD

**Issue by qeinz** [TheHolyWaffle/TeamSpeak-3-Java-API#419]
hello, how can i add a querylogin and get the login credentials afterwards?

```JAVA
        try {
            final String UID = Utils.getUIDFromSeckey(seckey);
            final int DBID = Main.api.getDatabaseClientByUId(UID).getDatabaseId();
            final String login_password = Main.api.addServerQueryLogin(UID, DBID).getQueryClientLoginPassword();
            System.out.println("logind login_password" + login_password);
            System.out.println("logind dbid" + DBID);
            System.out.println("logind uid" + UID);
            //update("INSERT INTO ");

        } catch (Exception exception) {
            System.out.println("ERROR " + exception);
        }
```

this is my current setup, but im only facing some spicy errors 

```JSON
2024-03-10T20:42:50.227560347Z ERROR com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "queryloginadd" command returned with a server error.
2024-03-10T20:42:50.227605824Z >> invalid parameter size (ID 1541)
```

**Comment by rogermb** [comment]
Hi @qeinz!

The only way I managed to reproduce an `invalid parameter size (ID 1541)` error with the "queryloginadd" command was when the `loginName` argument was null, an empty string, or a string of length greater than 20. It does not appear that this size constraint is documented anywhere in the TS3 documentation...

Could you please check whether your `UID` string fits within these constraints? Considering that you appear to be generating your query login name, I could well imagine its size being longer than 20 characters 😄

**Comment by rogermb** [comment]
Awesome, great to hear that! 🥳 🎉
