### ISSUE TITLE
[Question] Is there a way to control the volume of clients?

### ISSUE THREAD

**Issue by playajames** [TheHolyWaffle/TeamSpeak-3-Java-API#42]
I'm working on a plugin for a Minecraft server. What I'm trying to achieve is a way to make a players voice become lower as the player moves away from the listening client. Is it possible to control input volume for a client with different volumes per player that is near.

PS: This is not an issue I clicked a link that says to ask you questions and it took me here, hope you don't mind.

**Comment by Kakifrucht** [comment]
Afaik the Teamspeak 3 Server is not capable of this feature. Volume and position of players is only settable locally per user, 100% client sided.

**Comment by Firedroide** [comment]
Yup, as @Kakifrucht said: There's currently no such feature available to TeamSpeak server queries.

Volume is not controlled by the server and cannot be set globally. The only volume control there is is a per-user client setting. And even there, you cannot use "positional audio" directly; you need a client plugin for that.

So if you really depend on this feature, you have only two options (I could think of):

- Force all players to install a client plugin
- Use mumble instead, which has positional audio built-in.

**Comment by playajames** [comment]
That's okay, I'm loving this api otherwise, thanks for the help guys.
