### ISSUE TITLE
client change event

### ISSUE THREAD

**Issue by qeinz** [TheHolyWaffle/TeamSpeak-3-Java-API#422]
is there a way to make an event for client change things, like name change or talk change?

or is teamspeak so limited in events? D:

i dont want to use timers every time

**Comment by astrolamb-gaming** [comment]
Yeah unfortunately TS isn't the best on that regards. I think the entire list of usable events are implemented in EventManager.java: https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src%2Fmain%2Fjava%2Fcom%2Fgithub%2Ftheholywaffle%2Fteamspeak3%2FEventManager.java#L51-L63

**Comment by rogermb** [comment]
Correct, we unfortunately only have access to the events that TeamSpeak gives us
