### ISSUE TITLE
Chat Command Delay?

### ISSUE THREAD

**Issue by Pieter905** [TheHolyWaffle/TeamSpeak-3-Java-API#49]
Im writing an Bot to verfiy my Minecraft Server Players with the Minecraft Server.

But wehn i test the TextMessageEvent, i got an delay between send an answer from ~8 seconds.

Here is my Config:
https://gist.github.com/Pieter905/9c68205ce1828829add5

Here is my Event:
https://gist.github.com/Pieter905/9c68205ce1828829add5

**Comment by Firedroide** [comment]
I suppose you're using a SNAPSHOT version. What you're reporting here is an old issue which has already been fixed.

Please update to the latest SNAPSHOT and report back whether this has fixed your issue.

**Comment by Firedroide** [comment]
Closed due to inactivity - bug has probably already been fixed.

**Comment by Pieter905** [comment]
Thanks, that fixed my issue.
