### ISSUE TITLE
Invalid group ID

### ISSUE THREAD

**Issue by Mauricius17** [TheHolyWaffle/TeamSpeak-3-Java-API#50]
Hi,

I got an error message as I tested your api. I tried to add my client an servergroup. But I got an error. The console returned me that the server group ID was wrong.  

Here is the error: http://hastebin.com/qupikoruta.tex

I used the code : http://hastebin.com/funonovili.avrasm

I hope you can help me. 

Maurice

**Comment by Firedroide** [comment]
Cannot reproduce locally, everything works fine for me.

There are two things, however, that seem strange about your example:

- First of all, all your console output is duplicated. Why is that? Have you made any special changes to the logging system?
- And secondly, in your code you're trying to call `addClientToServerGroup(7, id)`, but what the query actually does is `servergroupaddclient sgid=0 cldbid=2`. No server group with the ID of 0 exists, thus the error is thrown.

    I looked through the code to see if we somehow missed a variable and put in a `0` instead when creating the command, but no such bugs were present. I even went through the commit history, but this was never an issue. The console output you sent us simply doesn't reflect the code you sent us.

So, the only suggestion I can give you is try to figure out why you're trying to add a client to the server group with the ID of 0, which does not exist.

**Comment by Mauricius17** [comment]
So I use this to connect to TeamSpeak.  

http://hastebin.com/ejifefiyiw.avrasm

Maybe I did anythink wrong?

**Comment by Firedroide** [comment]
By the way, looking at your TeamSpeak plugin, there's no reason why you couldn't just include our API in your plugin. Our license is quite permissive when it comes to that.

> Permission is hereby granted, free of charge, to [...] copy, modify, merge, publish, **distribute**, sublicense, ...

Requiring that your users download the API separately is way more complicated than it needs to be.

**Comment by Firedroide** [comment]
As long as you don't get any errors there, no, you're fine.

Really, you're just not passing that `7` to the API there, but `0` instead. You need to figure out why you're telling the API to add that user to group 0.

**Comment by Mauricius17** [comment]
Okay thank you. I founded the error. You were right. I used 0 as group ID. It was a simple error, but hard to find.

thx:D

Maurice
