### ISSUE TITLE
Where to download recent builds?

### ISSUE THREAD

**Issue by Kakifrucht** [TheHolyWaffle/TeamSpeak-3-Java-API#55]
The linked CI seems to not store the builds, is there anyway without compiling myself to get a more recent build than 1.0.11?

**Comment by Firedroide** [comment]
Currently you can get snapshot builds
a) by using Maven
b) by getting them directly from the [mvn-repo branch](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo) of this repository

If you want to download the build manually, you have to navigate to the [folder with the snapshots](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo/com/github/theholywaffle/teamspeak3-api) and then find the one with the latest build date. Currently, that would be [this file](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/raw/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.12-SNAPSHOT/teamspeak3-api-1.0.12-20150812.204416-11.jar) here.

**Comment by Kakifrucht** [comment]
Thanks, the repo branch works for me!
