### ISSUE TITLE
How can I get a Client by Id

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#59]
Question is in the title
i tried
		for(Client c : api.getClients()) {
			if(c.getId() == id) {
				return c;
			}
		}

but that was slow and buggy

**Comment by Firedroide** [comment]
Use [.getClientInfo](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1671) on either TS3Api or TS3ApiAsync.

Note that the client ID is not persistent and will change once a client disconnects and reconnects. If you need to identify a client across multiple sessions, consider using the Unique ID :)
