### ISSUE TITLE
NoClassDefFoundError: client?

### ISSUE THREAD

**Issue by dekros** [TheHolyWaffle/TeamSpeak-3-Java-API#61]
Hello have this error : http://scr.hu/1det/p8tow
my dependencies

```
    <dependencies>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.36</version>
        </dependency>
        <dependency>
            <groupId>com.github.theholywaffle</groupId>
            <artifactId>teamspeak3-api</artifactId>
            <version>[1.0.0,2.0.0)</version>
        </dependency>    
    </dependencies>
```

what i do bad?

**Comment by Kakifrucht** [comment]
You apparently didn't compile correctly. You need to extract the library in your exported

**Comment by dekros** [comment]
i can't use maven to this?

**Comment by Kakifrucht** [comment]
Yes you can, but you have to configure it properly. I'm afraid I can't tell you how.

**Comment by Firedroide** [comment]
Yes you can, you just need to use the correct build plugins :smile:

You're currently probably using just the default `maven-compiler-plugin`, but this will only compile all your Java source files and put them into a Jar file.

To include the classes from our API in your Jar file, you need to use `maven-shade-plugin` (official site [here](https://maven.apache.org/plugins/maven-shade-plugin/)). This plugin will basically just take our Jar, open it up, take out the class files and integrate them into your Jar file.

**Comment by dekros** [comment]
this is my pom.xml what is bad? and can you repair this?
http://pastebin.com/H1FYgq2S

**Comment by Firedroide** [comment]
@Kakifrucht I removed your other comment. Just telling others that "probably yes, but I don't know right now" doesn't help anyone and just creates noise. It's basically the equivalent of Reddit's "this." and "came here to say this" :smiley_cat:

I otherwise very much appreciate you commenting on these issues and helping others, so please don't take this as a general "fuck you" or anything like this.

**Comment by Firedroide** [comment]
@dekros Top response on the [StackOverflow question I linked](http://stackoverflow.com/questions/1729054/including-dependencies-in-a-jar-with-maven) should probably help. Copy the section from `<plugin>` to `</plugin>` into the already existing `plugins` section in your pom.xml file.

**Comment by dekros** [comment]
@Firedroide  when i replace this
maven-jar-plugin to maven-shade-plugin
i have this error
no main manifest attribute, in channelBOt

**Comment by Firedroide** [comment]
You can't just replace them, you need both. I'd suggest you read the tutorials on [how to use Apache Maven](https://maven.apache.org/guides/getting-started/index.html).

**Comment by dekros** [comment]
ok i will read but when i make project without maven and i import teamspeak3-api-1.0.12
and i have this same error;/

**Comment by Firedroide** [comment]
Then you probably need to correctly set up your IDE to export this library, too.

I just checked and can confirm that the issue is not on our side. The API is working as intended.
