### ISSUE TITLE
Insufficient client permission!

### ISSUE THREAD

**Issue by Freakey** [TheHolyWaffle/TeamSpeak-3-Java-API#64]
I have a problem when I try to add a client to a server group:
My code:
//In a TextMessageEvent
api.addClientToServerGroup(getConfig().getInt("Utility.Promote Group ID"), e.getInvokerId());

My error message:
{msg=insufficient client permissions, id=2568, failed_permid=172}

How can I fix this?

**Comment by Firedroide** [comment]
Well, you have to make sure you actually have that permission :smile:

* If you're not logging in yet (because you forgot or anything else):
        - Log in! Use `serveradmin` or a server query login you created yourself
        - To do that, use `TS3Config.setLoginCredentials` or login manually by calling `TS3API.login`

* If you're using a server query login you created yourself:
        - Make sure **your TS3 client** has the permission to do what you requested.

* If you're using the serveradmin login:
       - Option A: You're using a wrong login. Check the log for errors.
       - You're trying to modify something the server vendor set in place for you. Then you probably shouldn't modify that.

**Comment by Freakey** [comment]
Thanks, it's working now, but now I get a invalid clientID. How can I fix this? (id=512)

**Comment by Firedroide** [comment]
You need to use the client's database ID, not their session ID. Please read the Javadoc (or just the parameter names) to prevent these errors.

If you only have access to the client's session ID, you can call `api.getClientInfo` to get a ClientInfo object on which you can call `client.getDatabaseId` to get the database ID.

**Comment by Freakey** [comment]
And when I create a new Server Query login, how could I give it some permissions?

**Comment by Firedroide** [comment]
The server query receives the permissions of your client. When you change your own permissions you implicitly change the server query's permissions.

**Comment by Freakey** [comment]
Aah, thank you very much, thats all :)

**Comment by Firedroide** [comment]
Okay, I hope I was able to help! :smile:

If you have any other questions, feel free to ask them here or over at [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API).

I'll close this issue now.
