### ISSUE TITLE
Throw Exceptions

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#67]
Hello!
Can you please throw all exceptions for error processing? I already made a custom jar but I don't like doing something like that. So. Are you able to throw Exceptions like TS3ConnectionFailedException?

**Comment by Firedroide** [comment]
Heyo!

* A `TS3ConnectionFailedException` is thrown when you call `TS3Query.connect` and a connection could not be established.
* In the synchronous API, no other exceptions are thrown *on purpose*. The intent is to keep your program running even if, for example, a client logs off right before you send them a message.
* There is, however, an asynchronous version of the API, which includes exceptions and failure handling. Check out `TS3ApiAsync` and `CommandFuture`.
* In the future, the asynchronous API will also include a method to register a default failure listener. 
* Reconnecting has also not yet been implemented. If you'd like to give that a try, go ahead. We're always looking forward to pull requests :smile:

**Comment by Scrumplex** [comment]
but in the github repository there is an try catch.

**Comment by Firedroide** [comment]
Uhm, where exactly?

The only try-catch clauses in the whole API that are not just to filter out interrupts are
* in TS3Query.connect we catch IOExceptions and re-throw them as TS3ConnectionFailedException
* an ignored IOException in TS3Query.disconnect
* proper handling of IOExceptions in SocketReader, SocketWriter and LogHandler
* catching and printing of exceptions caused by SuccessListeners, FailureListeners and Callbacks passed in by users.

**Comment by Scrumplex** [comment]
ok. but the throws TS3ConnectionFailedException expression is not there

**Comment by Firedroide** [comment]
[Sure is](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Query.java#L95-L97).

I think you need to rephrase your issue and tell me more precisely what you're experiencing problems with and what you'd like me to do to fix that.

**Comment by Scrumplex** [comment]
So if I try to connecto to locaaaaalhoust (unknown host) i cant process the error in my java app. It just prints to console

**Comment by Scrumplex** [comment]
```java
`	public TS3Query connect() {
		// exit();
		try {
			socket = new Socket(config.getHost(), config.getQueryPort());
			if (socket.isConnected()) {
				out = new PrintStream(socket.getOutputStream(), true, "UTF-8");
				in = new BufferedReader(new InputStreamReader(socket.getInputStream(), "UTF-8"));
				socketReader = new SocketReader(this);
				socketReader.start();
				socketWriter = new SocketWriter(this, config.getFloodRate().getMs());
				socketWriter.start();
				keepAlive = new KeepAliveThread(this, socketWriter);
				keepAlive.start();
			}
		} catch (final IOException e) {
			throw new TS3ConnectionFailedException(e);
		}
```
needs
```java
`	public TS3Query connect() throws TS3ConnectionFailedException {
		// exit();
		try {
			socket = new Socket(config.getHost(), config.getQueryPort());
			if (socket.isConnected()) {
				out = new PrintStream(socket.getOutputStream(), true, "UTF-8");
				in = new BufferedReader(new InputStreamReader(socket.getInputStream(), "UTF-8"));
				socketReader = new SocketReader(this);
				socketReader.start();
				socketWriter = new SocketWriter(this, config.getFloodRate().getMs());
				socketWriter.start();
				keepAlive = new KeepAliveThread(this, socketWriter);
				keepAlive.start();
			}
		} catch (final IOException e) {
			throw new TS3ConnectionFailedException(e);
		}
```

**Comment by Firedroide** [comment]
`TS3ConnectionFailedException` is an unchecked exception. Just wrap your call to `TS3Query.connect` in a try-catch.

Learn more about unchecked exceptions [here](https://docs.oracle.com/javase/tutorial/essential/exceptions/).

**Comment by Scrumplex** [comment]
oh sorry for my superficial knowledge

**Comment by Firedroide** [comment]
Nah, it's not your fault, I'm just kinda grumpy today.

Please forgive my rudeness and feel free to contact us here again or over on our [Gitter repository chat](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API).
