### ISSUE TITLE
How to run the built project

### ISSUE THREAD

**Issue by Punny123** [TheHolyWaffle/TeamSpeak-3-Java-API#71]
This is question is a bit embarrassing, but how do I run the program after I built it. I can run the program in netbeans but I want to know how to run it through cmd

**Comment by Firedroide** [comment]
1. Tell Netbeans to export your project as a .jar file.
2. Open the folder where your jar file is located.
3. Open a command prompt in that folder (Ctrl + right click in the explorer window --> open command prompt here in Windows)
4. "java -jar YourJarFileNameHere.jar"
5. Enjoy :D

**Comment by Punny123** [comment]
It says "no main manifest attribute"

**Comment by Firedroide** [comment]
Then you need to edit your project settings / exporting settings / something completely else.
You need to tell it to generate a manifest file that includes the Main-Class attribute.
(I have no idea how Netbeans works and am actually surprised it doesn't do that on its own.)

**Comment by Firedroide** [comment]
I found these two links, maybe they help you solve this problem.
[Netbeans "exercise"](https://netbeans.org/kb/articles/javase-deploy.html), [Stackoverflow](http://stackoverflow.com/questions/2848642/how-to-setup-main-class-in-manifest-file-in-jar-produced-by-netbeans-project).

**Comment by Punny123** [comment]
Ok how would you compile the java file you created without netbeans?

**Comment by Firedroide** [comment]
To be honest, I'd always use an IDE over the command prompt. Being able to just click a button to compile the whole file without having to first compile and then package all your files saves just so much time.

But, to answer your question, you'd use [javac](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html) to compile individual .java files into .class files and then package everything together using the [jar](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jar.html) tool.

If NetBeans just doesn't suit your needs, be sure to check out IntelliJ IDEA or Eclipse. Both are very capable IDEs (though I must say I prefer IntelliJ IDEA by quite a bit :smile:)

**Comment by Punny123** [comment]
Yeah I also prefer an IDE but I created a bot with the api and I want to put it on my server. so running it would just be easier with a command line

**Comment by Firedroide** [comment]
Uh, yeah, you're not intended to run the jar file from the IDE on the server, the IDE is just for development. When you've compiled the jar file and copied it onto the server, you only need to execute "java -jar jarfile.jar" at startup / whenever needed.

**Comment by Punny123** [comment]
yup, so I just need to get this main manifest fixed

**Comment by Punny123** [comment]
But thanks a lot for the help.

**Comment by Firedroide** [comment]
You're welcome!

If any other questions arise, feel free to ask them here or over on [gitter, which is basically a chat room for a repository on GitHub](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API). :smile:
