### ISSUE TITLE
How to change Channel Description

### ISSUE THREAD

**Issue by b3zman41** [TheHolyWaffle/TeamSpeak-3-Java-API#74]
I don't think there's a way to change the description of a channel. When looking at the TS Query Guide, you can do a channel update. I just don't see access in the API. Thanks so much.

**Comment by Scrumplex** [comment]
It is `api.editChannel(channelid, properties);` where properties is a Map with the Key ChannelProperty and the Value String. After you created the Map just put the following in there: `properties.put(ChannelProperty.CHANNEL_DESCRIPTION, "First Line\nSecond Line...");`

**Comment by b3zman41** [comment]
Thanks so much! Sorry for bugging you about it.

**Comment by Firedroide** [comment]
If you have any other questions, feel free to ask us again and we'll try to answer as soon as possible.

Just gets difficult if we're still asleep at 5am :stuck_out_tongue:

![image](https://cloud.githubusercontent.com/assets/1472572/12012173/7e2eaad0-ace9-11e5-8aaa-b154323dad20.png)
