### ISSUE TITLE
How to change required power for serveradmin

### ISSUE THREAD

**Issue by Tythus** [TheHolyWaffle/TeamSpeak-3-Java-API#75]
I'm wanting to allow users to send messages to the server admin so they can request certain things but I keep getting this message

insufficient client permissions (failed on i_client_needed_private_textmessage_power)

is there any way I can lower the server admin required power?

**Comment by Scrumplex** [comment]
https://github.com/Scrumplex/Sprummlbot/blob/master/src/main/java/ga/codesplash/scrumplex/sprummlbot/ServerOptimization.java An example of permission editing (the void permissions())

**Comment by Firedroide** [comment]
Actually, you could just set a single user permission to lower `i_client_needed_private_textmessage_power` instead of having to change the server group's permissions.

By default, guests on your server have `i_client_private_textmessage_power` set to 0 and normal users have it set to 50. So, in this example, let's lower the needed `i_client_needed_private_textmessage_power` to 50 to allow all normal users and admins to message the server query directly.

    int databaseID = api.whoAmI().getDatabaseId();
    api.addClientPermission(databaseID, "i_client_needed_private_textmessage_power", 50, true);

**Comment by Scrumplex** [comment]
Yes my code changed the permission for the complete server admin query group

**Comment by Tythus** [comment]
my only other question is it possible to make the query client visible?

**Comment by Firedroide** [comment]
Yes, but only to users who set `Show ServerQuery clients` in their bookmarks. You can't make server queries visible to everyone on your server by default.

Apart from that, the client who's supposed to see the query also needs a `i_client_serverquery_view_power` higher than the queries `i_client_needed_serverquery_view_power`. This usually requires changing your or the queries permissions, especially if the query is using the `serveradmin` account.

I found a good [article on how to making server queries visible](http://wot-rusty.com/content/making-bot-visible-teamspeak).

If this answers your question, feel free to close this issue :smile:

**Comment by Tythus** [comment]
my only last question is if I set the client permission i_client_private_textmessage_power on the server admin client would that only stick to that serveradmin for this session? as in if I were to stop the bot then start it up I would need that to run again? otherwise thankyou for answering all my Q's

**Comment by Firedroide** [comment]
The permission system uses database IDs (and not one-session client IDs), meaning these permissions will persist.

**Comment by Tythus** [comment]
for (Channel c: api.getChannels()){
			api.registerEvent(TS3EventType.TEXT_CHANNEL, c.getId());
		}

I presume I can't just listen to all channels chat by doing this and have to have a bot in each channel?

**Comment by Firedroide** [comment]
Exactly. The Holy Law of TeamSpeak dictates that  you can only listen to the chat of one channel at a time, for whatever reason. Everything else works for the whole server. This is not a restriction of this API but the ServerQuery interface.

Sorry for the short, low-quality responses, I'm travelling and on mobile at the moment.

**Comment by Tythus** [comment]
thats fine this is going to be brutal on my client cap on the server

**Comment by Firedroide** [comment]
In most cases, you should just use the global server chat if you're trying to make the bot respond to commands everywhere.

Or send a private message to all / selected users when they join the server and have people send commands via private messages.

Having one query for each channel is usually a bad idea. You might be able to monitor all channel chats by reading the server's log files locally.

**Comment by Tythus** [comment]
yeah I don't want it in global chat as I know in 5 seconds it'll be filled with spam the issue with PM is if the player closes the PM they can't contact the bot I suppose I could try and read logs but that feels hacky at best I wish there was a more correct way of doing this. How would I chat chat logs I don't see it under SQL or on the logs folder?

**Comment by Firedroide** [comment]
Not my area of expertise; but I'm pretty sure you can find information on the TS forums.

**Comment by Tythus** [comment]
oh last thing I took your advice for this

int databaseID = api.whoAmI().getDatabaseId();
api.addClientPermission(databaseID, "i_client_needed_private_textmessage_power", 50, true);

it doesn't seem to be sticking

**Comment by Firedroide** [comment]
As long as you're using the same login on the same server every time, it _should_ stick around.

You should join your server, open up the 'clients' tab of the permissions window and check if the entry you've just created with the API actually exists.

0 or multiple entries means I fucked up and got sonething totally wrong.
1 entry and it should work, but for some reason still doesn't. :P

**Comment by Firedroide** [comment]
Closed due to inactivity.
