### ISSUE TITLE
Filelist and file upload

### ISSUE THREAD

**Issue by kevcodez** [TheHolyWaffle/TeamSpeak-3-Java-API#76]
I could not find support for uploaded files in channels or uploading files. Any help here?

**Comment by Firedroide** [comment]
Not yet implemented. Might be implemented at a later date, but no guarantees as of yet.

The file upload component of TeamSpeak is not used very often, especially with server queries. I do wonder, what are you trying to use it for? :stuck_out_tongue:

**Comment by kevcodez** [comment]
I am currently building a management interface (web) and I am just trying to cover everything, but I will skip the file management for now :P

**Comment by Firedroide** [comment]
Kay :smile:

I'll leave this issue open and if the feature is ever implemented, I'll notify you here and close the issue.

**Comment by Firedroide** [comment]
Just to let you know, a recent commit (165739aa9b0d2255f3e48a4d0137ed7e6ad8c53a) has added the ability for file transfers. This includes listing, uploading, downloading and deleting of files and icons, as well as moving files around.

As this is only a snapshot build, you'll have to [download it directly from the build repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/raw/mvn-repo/com/github/theholywaffle/teamspeak3-api/1.0.14-SNAPSHOT/teamspeak3-api-1.0.14-20160828.145049-8.jar). To get this build via Maven, you'll have to enable snapshot builds.

Once this feature makes it to an official release, this issue will be closed.

**Comment by rogermb** [comment]
1.0.14 has been released, closing this issue.

Thanks for suggesting this feature! 😄
