### ISSUE TITLE
Listen to chat in one or more channels

### ISSUE THREAD

**Issue by styler2go** [TheHolyWaffle/TeamSpeak-3-Java-API#79]
When trying to listen in a channel, the onTextMessage Event is not being fired.
Is this an issue with Teamspeak or an issue with this Java API?

**Example:**
````
// Either {
api.registerAllEvents();
//  } Or {
List<Channel> chanList = api.getChannels();
Iterator<Channel> it = chanList.iterator();
while(it.hasNext()){
    Channel chan = it.next();
    api.registerEvent(TS3EventType.TEXT_CHANNEL, chan.getId());
}
//  }

api.addTS3Listeners(new TS3EventAdapter() {
            @Override
            public void onTextMessage(TextMessageEvent e) {
                super.onTextMessage(e);
                String message = e.getMessage().trim();
                System.out.println(message);
            }
}
```
**Result:**

Console will only print serverwide messages. Channel messages are not being print.

**Comment by Kakifrucht** [comment]
I'm pretty sure that you can only listen to text chat from one channel at a time. Otherwise you would be spying on your users.

**Comment by styler2go** [comment]
Hmm.. That's what i kind of want to do. I can't think of any other solution to have "global chatcommands" for a little teamspeak bot.

Also: Sending messages to any channel works...

**Comment by Firedroide** [comment]
More specifically, you can only listen to the channel your server query is currently "talking" in.

> Also: Sending messages to any channel works...

No, not really, actually :smile:
The TS3 command `sendtextmessage` does accept a `target` parameter with which you're supposed to be able to specify a target channel to send a message to - but this doesn't actually work. (TS3 sometimes...)

If you check out the API method [sendChannelMessage(int, String)](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L3303-L3305), you'll notice that the API first **moves you** into the channel and then sends the actual command.

We just worked around this known bug in our implementation.

---

Seeing how there is no actual issue with the API here and this whole issue could have been resolved by reading the TS3 server query manual and the API documentation, I'll go ahead and close this issue.
