### ISSUE TITLE
setLoginCredentials() is undefinded

### ISSUE THREAD

**Issue by PhilippMiller** [TheHolyWaffle/TeamSpeak-3-Java-API#80]
"The method setLoginCredentials() is undefinded for the type TS3Config" I've tryed to create a Config as the example shows it up.

`final TS3Config config = new TS3Config();`
`config.setHost("77.77.77.77");`
`config.setDebugLevel(Level.ALL);`
`config.setLoginCredentials("serveradmin", "serveradminpassword");`

In the TS3Config.java there isn't a function "setLoginCredentials()".

**Comment by PhilippMiller** [comment]
Sry I've seen to late that the example now looks different.

`final TS3Config config = new TS3Config();`
`		config.setHost("77.77.77.77");`
`		config.setDebugLevel(Level.ALL);`
``
`		final TS3Query query = new TS3Query(config);`
`		query.connect();`
``
`		final TS3Api api = query.getApi();`
`		api.login("serveradmin", "serveradminpassword");`

Sry for that issue. Sincerely.

**Comment by Firedroide** [comment]
You're actually correct; not for the examples, but for the readme file :smile:

I completely forgot to change these ^^

Fixed in 998abf0c8dec1ebfb5d4baf73015a317bdf59b6b (and 799654f91a2b0c9544c1811072e3ad2378fb2bc0 cause I'm a derp) :stuck_out_tongue:
