### ISSUE TITLE
query is not connecting

### ISSUE THREAD

**Issue by awsdcrafting** [TheHolyWaffle/TeamSpeak-3-Java-API#84]
The query is not connecting and i cant find the error
code:
package soundonjoin;

import java.awt.List;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;
import com.github.theholywaffle.teamspeak3.api.TextMessageTargetMode;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventAdapter;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventType;
import com.github.theholywaffle.teamspeak3.api.event.TextMessageEvent;
import com.github.theholywaffle.teamspeak3.api.wrapper.Client;
import com.github.theholywaffle.teamspeak3.api.wrapper.ServerGroupClient;

public class PoJ {

	public static void tsPoJ() throws InterruptedException {
        final TS3Config config = new TS3Config();
        config.setHost("ts-address-without-port");
        config.setLoginCredentials("username", "password");
        final TS3Query query = new TS3Query(config);
        query.connect();
        final TS3Api api = query.getApi();
        api.selectVirtualServerByPort(12200);
        api.setNickname("PutPutBot");
        int client_ID;
        for(ServerGroupClient client : api.getServerGroupClients(18713)){
        client_ID = client.getClientDatabaseId();
        api.pokeClient(client_ID, Main.name + "joined the server");
        Thread.sleep(10000);
        api.logout();
        Thread.sleep(10000);
        query.exit();
        }

	}

}

**Comment by TheMolkaPL** [comment]
Which stack trace do you receive?

**Comment by awsdcrafting** [comment]
i found an error in the log: java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config

**Comment by TheMolkaPL** [comment]
You need to compile this library into the JAR you create.

**Comment by awsdcrafting** [comment]
ah ok thx
im coding with eclipse and I cant compile it into the jar. I tried it with "export as runnable jar" but then the error "no resource selected" pops up

**Comment by TheMolkaPL** [comment]
You can copy and paste this into your source directory.

**Comment by awsdcrafting** [comment]
im trying this now thx for your help
