### ISSUE TITLE
ts3 poke client convert error

### ISSUE THREAD

**Issue by awsdcrafting** [TheHolyWaffle/TeamSpeak-3-Java-API#85]
bot is connecting now and tries to send a message and two pokes all three times the error 
"msg=convert error id=1540" pops up
code:
        int client_ID;
        for(ServerGroupClient client : api.getServerGroupClients(18713)){
        client_ID = client.getClientDatabaseId();
        api.pokeClient(client.getClientDatabaseId(),""+Main.name+"joined the server");
        api.sendPrivateMessage(client_ID, ""+Main.name+"joined the server");
        api.pokeClient(66940, ""+Main.name+"joined the server");

if you need more code I will post it.

**Comment by TheMolkaPL** [comment]
```java
int client_ID;
for(ServerGroupClient client : api.getServerGroupClients(18713)){
    client_ID = client.getClientDatabaseId();
    api.pokeClient(client.getClientDatabaseId(),""+Main.name+"joined the server");
    api.sendPrivateMessage(client_ID, ""+Main.name+"joined the server");
    api.pokeClient(66940, ""+Main.name+"joined the server");
}
```

You need to have clients ID, not the database ID.

**Comment by awsdcrafting** [comment]
oh... I am using server querys and I just used the false id... ok thanks.

**Comment by awsdcrafting** [comment]
How can i get the client id?

**Comment by Firedroide** [comment]
Stop abusing the GitHub issues system and wasting everyone's time, @awsdcrafting. :angry:

For your Java issues, use Google and StackOverflow.
For this project, first read the readme page and then take a look at the [examples](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/master/example).
Using the search function inside `TS3Api` and the objects you get back from the API is also a great way to achieve your goal.

For your current problem, I'd suggest you use `TS3Api.getClients` and for each client check whether `Client.getServerGroups` contains the wanted server group ID.
