### ISSUE TITLE
Function ClientMovedEvent getInvokerUniqueId() not working ?

### ISSUE THREAD

**Issue by Zangdar1111** [TheHolyWaffle/TeamSpeak-3-Java-API#88]
hey there,

I was trying to retrieve the unique id of an invoker client based on a ClientMovedEvent (in a  onClientMoved listener), however the function getInvokerUniqueId() return me a void string (confirmed by debugger).

Does this happen to other people ?

**Comment by Firedroide** [comment]
The invoker is not the client that moved, but the client who moved another client, e.g. by kicking / moving them. So the invoker UUID will only return a non-empty string if the client doesn't move by themselves.

**Comment by somefriggnidiot** [comment]
Are you intending to get the ID of the user who moved? getInvokerUniqueId() returns the ID of the "mover," not the user being moved.

**Comment by Zangdar1111** [comment]
Oh ok, i understand, didn't noticed the difference between client and invoker.
Thanks for the very quick answer !
