### ISSUE TITLE
clientjoin

### ISSUE THREAD

**Issue by Hakens** [TheHolyWaffle/TeamSpeak-3-Java-API#91]
Hello.
Can someone show me how do that:
When someone join to channel(channelId) bot send him a private message

**Comment by FlDutchman** [comment]
This should do it :)
		

		final TS3Config config = new TS3Config();
		config.setHost("77.77.77.77");
		config.setDebugLevel(Level.SEVERE);

		final TS3Query query = new TS3Query(config);
		query.connect();

		final TS3Api api = query.getApi();
		api.login("serveradmin", "serveradminpassword");
		api.selectVirtualServerById(1);
		api.setNickname("PutPutBot");
		api.sendChannelMessage("PutPutBot is online!");

		api.registerAllEvents();

		api.addTS3Listeners(new TS3Listener() {

			@Override
			public void onClientMoved(ClientMovedEvent arg0) {
				int clientId = arg0.getClientId();
				if (api.getClientInfo(clientId).getChannelId() == 20) {
					api.sendPrivateMessage(clientId, "Hello in Channel with ID = 20");
				}

			}

			@Override
			public void onTextMessage(TextMessageEvent arg0) {
			}

			@Override
			public void onServerEdit(ServerEditedEvent arg0) {
			}

			@Override
			public void onClientLeave(ClientLeaveEvent arg0) {
			}

			@Override
			public void onClientJoin(ClientJoinEvent arg0) {
			}

			@Override
			public void onChannelPasswordChanged(ChannelPasswordChangedEvent arg0) {
			}

			@Override
			public void onChannelMoved(ChannelMovedEvent arg0) {
			}

			@Override
			public void onChannelEdit(ChannelEditedEvent arg0) {
			}

			@Override
			public void onChannelDescriptionChanged(ChannelDescriptionEditedEvent arg0) {
			}

			@Override
			public void onChannelDeleted(ChannelDeletedEvent arg0) {
			}

			@Override
			public void onChannelCreate(ChannelCreateEvent arg0) {
			}
		});

**Comment by Firedroide** [comment]
@FlDutchman Your version works, but it has several flaws.

- You don't need to call `api.registerAllEvents()` for just channel joins, calling `api.registerEvent(TS3EventType.CHANNEL)` would suffice.

- You should prefer [`TS3EventAdapter`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/TS3EventAdapter.java) over `TS3Listener`. That way you can only override the methods you actually need and don't end up with so many empty method stubs.

- While calling `api.getClientInfo(clientId).getChannelId()` inside the event handler works, it is not necessary and adds more latency. Just call [`event.getTargetChannelId()`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/event/ClientMovedEvent.java#L46). If you're using a release build (i.e. not a snapshot build), that method is still called `event.getClientTargetId()`, if I recall correctly.

- Setting the logging level to `Level.SEVERE` is usually a bad idea. The API emits warning messages for a reason. If you don't want the communication between client and server to be "leaked" to the console, just set the level to `Level.WARNING` (which is the default setting anyways).

-------

@Hakens: 
Did @FlDutchman's and my response answer your question?

**Comment by FlDutchman** [comment]
public static void main(String[] args) {
		final int channel = 10;

		final TS3Config config = new TS3Config();
		config.setHost("77.77.77.77");

		final TS3Query query = new TS3Query(config);
		query.connect();

		final TS3Api api = query.getApi();
		api.login("serveradmin", "serveradminpassword");
		api.selectVirtualServerById(1);
		api.setNickname("PutPutBot");
		api.sendChannelMessage("PutPutBot is online!");

		api.registerEvent(TS3EventType.CHANNEL, channel);
		api.addTS3Listeners(new TS3EventAdapter() {

			@Override
			public void onClientMoved(ClientMovedEvent event) {
				int newChannel = event.getClientTargetId();
				
				//or in newer versions:
				//int newChannel = event.getTargetChannelId();
				
				
				if (newChannel == channel) {
					api.sendPrivateMessage(event.getClientId(), "Hello in Channel with ID = 20");
				}

			}
		});
	}

@Hakens here is the "better" version
@Firedroide I also added the channelId to the registerEvent function.

**Comment by Firedroide** [comment]
@FlDutchman Awesome! Thanks for your help :smile:

**Comment by Hakens** [comment]
I will check that on my code and write reply, thx for your time!

**Comment by Hakens** [comment]
seems bot do nothing;/ not work for me or i do something wrong

**Comment by FlDutchman** [comment]
@Hakens as @Firedroide already stated: you don't need the registerAllEvents() if you only have a Listener for this scenario. I would recommend registerEvent(TS3EventType.CHANNEL, channel)
