### ISSUE TITLE
Listen to multiple channels (TextMessageEvent)

### ISSUE THREAD

**Issue by DevCubeHD** [TheHolyWaffle/TeamSpeak-3-Java-API#92]
How can I listen to multiple channels with the api?
I hear it wont work but maybe there is a method...

**Comment by TheMolkaPL** [comment]
You can't. TeamSpeak 3 Query doesn't provide method to listen to more than one channel.

**Comment by DevCubeHD** [comment]
api.registerEvent(TS3EventType.TEXT_CHANNEL, ID);
so why can I the do this with a channel id?

**Comment by TheMolkaPL** [comment]
You can only subscribe to one channel.

**Comment by DevCubeHD** [comment]
so is there any other method how to solve it? like connecting one query per channel? this would s**ck because I need to make all that users

**Comment by TheMolkaPL** [comment]
You would be interested in this thread: http://forum.teamspeak.com/threads/122734-Server-Query-Receive-Text-from-any-channel

> This is not possible. You can only listen or read, when you are in the channel.
Please do not use our software as a SpyTool.
