### ISSUE TITLE
GetChannelByID

### ISSUE THREAD

**Issue by DevCubeHD** [TheHolyWaffle/TeamSpeak-3-Java-API#93]
Would be nice to get a channel by id (or is it already included?)

**Comment by TheMolkaPL** [comment]
This API is based on the TeamSpeak 3 Server Query queries. You can read the manual [here](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf).

If you would to get informations about the channel, you could use the `channelinfo` query. You can read more about it on page 19.

> **CHANNELINFO**
Displays detailed configuration information about a channel including ID, topic, description, etc.
For detailed information, see Channel Properties.

> **Permissions:**
`b_channel_info_view`

> **Syntax:**
`channelinfo cid={channelID}`

> __Example:__
Query: `channelinfo cid=1`
Response: `channel_name=Default\sChannel channel_topic=Default\sChannel\shas\sno\s[b]topic[\/b] channel_description=This\sis\sthe\sdefault\schannel …`
`error id=0 msg=ok`

**Comment by Firedroide** [comment]
Thank you very much @TheMolkaPL :smile:

@DevCubeHD The API implements this method under the name [`TS3Api#getChannelInfo(int)`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L1536).

**Comment by DevCubeHD** [comment]
But thats only a ChannelInfo not a Channel

**Comment by TheMolkaPL** [comment]
There isn't any class named `Channel`.

**Comment by Firedroide** [comment]
Sure there is a class named [`Channel`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/Channel.java). [`ChannelInfo`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/ChannelInfo.java) just happens to include some different information, but both `Channel`` and `ChannelInfo` extend a common superclass named `ChannelBase` and can be used more or less interchangeably.

**Comment by DevCubeHD** [comment]
ChannelBase then.. I solved it because there is a moveClient method with channel and client id

**Comment by DevCubeHD** [comment]
Thank you :) sorry for keep von wiriting after closed thread :) have a nice day

**Comment by Firedroide** [comment]
moveClient and moveQuery both use ChannelBase, so they'll accept both Channel and ChannelInfo :stuck_out_tongue:
