### ISSUE TITLE
How can I create a subchannel under a channel

### ISSUE THREAD

**Issue by DevCubeHD** [TheHolyWaffle/TeamSpeak-3-Java-API#94]
Question in the title... didnt find a method :c
thank you guys!

**Comment by TheMolkaPL** [comment]
Yes, you can!

If you read both [the manual](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf) (page 44) and [this API](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/ChannelProperty.java#L59) you will see that you can use the `CPID` (**C**hannel **P**arent **ID**) to set the parent channel ID.

**Comment by Firedroide** [comment]
@DevCubeHD Before you open up any more issues, I'd like to ask to actually read the official documentation manual and the documentation we provide with this API.

Furthermore, none of the issues you asked about are new or obscure, and could easily be solved by searching this project's issues and / or by using google.
