### ISSUE TITLE
How to get list of clients 

### ISSUE THREAD

**Issue by Hakens** [TheHolyWaffle/TeamSpeak-3-Java-API#95]
How to get list of clients of specific group and send to they privmessage on client join to specific channel
Example:
someone join to channel(id=2339) and bot poke all clients on specific group(id=211)
i use that code what i make but not work
`if(newChannel==2339){
	            		int ilosc_botreki = api.getServerGroupClients(211).size();
	            		
	            		
	            		for (int i=0;i<ilosc_botreki;i++){
	            			String wiaddoadmiID=api.getServerGroupClients(211).get(i).getUniqueIdentifier();
	            			int admsids = api.getClientByUId(wiaddoadmiID).getId();
	            			api.sendPrivateMessage(admsids, "TEST");
	            		}
	            	}`

I try much more ways maybe im too poor in java;/

**Comment by FlDutchman** [comment]
Hello since you said you aren't quite familiar with java, I wrote a solution for you with detailed. Please try to understand it and don't just use it ;) 
[Get it from here](https://gist.github.com/FlDutchman/9116bc5b3ff5338f91eb04671bb85b62)

**Comment by Hakens** [comment]
Hello, work but this isnt that what i need, thx to You @FlDutchman now i know how to check everyone on server and now i can do that:
```
@Override
public void onClientMoved(ClientMovedEvent event) {
int whatchannel=IdOfChannelOnWhatNewUsersJoinWhenWantHelpAdmins;
int servergroup = IdOfRanksAdmins;
if(newChannel==whatchannel){
              List<Client> clients = api.getClients();
              for (Client client : clients) {
	            			if (client.isInServerGroup(servergroup)) {
	    						api.sendPrivateMessage(client.getId(), "Message!");
                                                                                                       }
	            	                              }
	            	                      }
```
This will be send a private message to all users in group when someone join to specific channel.

Thanks once more time @FlDutchman !
