### ISSUE TITLE
ChannelProperty for delay for deleting temporary channels

### ISSUE THREAD

**Issue by Linnun** [TheHolyWaffle/TeamSpeak-3-Java-API#99]
With the client you can set a delay (in seconds) for a temporary channel. Only after that delay of being empty, that channel will be deleted.

Using this API I couldn't figure out how to set this option. Is there a ChannelProperty missing?

**Comment by Linnun** [comment]
Just found out the property is called "channel_delete_delay"

More info here: http://forum.teamspeak.com/threads/92655-Channel-Delete-Delay-(a-little-explanation-about-this-feature)

Can someone add this to this api?

**Comment by Scrumplex** [comment]
That is a VirtualServer Flag not a Channel Flag.

**Comment by Linnun** [comment]
> - channelcreate can be used for template delete delay from the server or with your own values for the delete delay.
- i_channel_create_modify_with_temp_delete_delay is needed to create a channel with a custom deleay.
- channel_name=test1 channel_delete_delay=22 would create a channel with 22 seconds of delay.

**Comment by Linnun** [comment]
I have made this part of my open pull request #97. It's fully implemented and working (tested).
